Feature/kin 80/layout section contact main page front end
loopcrack-org/Kinub pull request #10
Opened 2023-08-24 09:51 UTC by Oswaldo-Chan

## Summary

### Problem

The project requires a way for the user to communicate with the company.

### Solution

The implementation of a contact form that will send the obtained information via email.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] The form must contain a button to send the information.
- [ ] The form must be responsive
- [ ] The form must display alerts for errors generated in the form.
- [ ] The form should display a modal message in case the form has been submitted successfully.

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Fill out the form
- [ ] Test it on different screen sizes

## Resources

## Demo

2023-08-24 16:31 UTC, Cristianpan requested changes
There is an error with the sweet alert, please check and make the changes.

2023-08-24 17:04 UTC, Cristianpan submitted a review, later dismissed

2023-08-24 23:33 UTC, Mauriciocr207 requested changes
Try to delete all .map files because they are adding size to your pull request or wait to bug pull request

2023-08-25 07:31 UTC, Cristianpan approved these changes

2023-08-25 16:12 UTC, closed without merging