KIN-288 - Integration of the token expiration feature on the database
loopcrack-org/Kinub pull request #100
Opened 2023-10-31 19:24 UTC by CarlosJCD

## Summary

### Problem

The current database schema does not support the intended token expiration functionality

### Solution

Integrate the database components needed for the token expiration functionality

## Acceptance Criteria

### Requirements checklist

- [x] The database needs to have a table for the user tokens

- [x] The table must have columns for:
  - [x] The token id
  - [x] The token number
  - [x] The expiry date of the token
  - [x] A foreign key for the user id
- [x] The token column on the user entity must be removed.
- [x] The user seeder must be changed

### Testing

- [x] Run `php spark migrate:refresh` to empty the database on your CLI.
- [x] Then run `php spark db:seed InitSeeder` on your CLI.
- [x] See that the `user_tokens` table on the database has a touple with a foreign key to the user with `userId = 2`.

2023-11-01 05:14 UTC, Oswaldo-Chan approved these changes
Good job @CarlosJCD, but Joachin and I have a question. We noticed that there's a migration for Emails, but it doesn't have a corresponding seeder since the 'EmailSeeder' file was deleted. Are you planning to recreate that seeder in another ticket, or was it removed by mistake?

2023-11-01 05:15 UTC, FernandoJoachin approved these changes

2023-11-01 05:24 UTC, Oswaldo-Chan approved these changes

2023-11-01 17:10 UTC, Mauriciocr207 approved these changes

2023-11-01 17:11 UTC, LUGAMAFE requested changes
@CarlosJCD  this Pr should not be open as we need to complete the merge of this PR https://github.com/loopcrack-org/Kinub/pull/99 first. And when we merge this branch to main it will probably break the site. Because you are changing the token logic in the database maybe you will need to fix that logic on this ticket too.

2023-11-04 22:03 UTC, CheloChidoone requested changes
@CarlosJCD We only tested the DB changes for this ticket because that is the goal of this ticket, we saw you also started functionality changes for change password and confirm email but those are supposed to be on a different ticket, just be sure to keep everything in order, We left a couple of other comments.

CC: @CarlosMay7

2023-11-04 22:03 UTC, CheloChidoone commented on app/Database/Seeds/MainTestSeeder.php
> +        $this->call('UserTokensSeeder');
@CarlosJCD You made this change in the wrong seeder, this isn't the `InitSeeder` this is `MainTestSeeder`, please remove this and put this change on `InitSeeder`.

CC: @CarlosMay7

2023-11-04 23:23 UTC, CarlosJCD commented
> @CarlosJCD We only tested the DB changes for this ticket because that is the goal of this ticket, we saw you also started functionality changes for change password and confirm email but those are supposed to be on a different ticket, just be sure to keep everything in order, We left a couple of other comments.
> 
> CC: @CarlosMay7

I had to made some changes on the backend so that the existing logic does not break. However thanks for the observations!

2023-11-04 23:25 UTC, CarlosJCD commented on app/Database/Seeds/MainTestSeeder.php
> +        $this->call('UserTokensSeeder');
As a suggestion of @Cristianpan, I changed the `InitSeeder` name to `MainTestSeeder`.

2023-11-05 01:15 UTC, CheloChidoone commented on app/Database/Seeds/MainTestSeeder.php
> +        $this->call('UserTokensSeeder');
Ok @CarlosJCD, when you make changes like that specify on your PR description about those changes, and also on the Testing part change it to `MainTestSeeder` if that is the case because it still says `InitSeeder` on the Testing steps.

2023-11-05 01:46 UTC, CarlosJCD commented on app/Database/Seeds/MainTestSeeder.php
> +        $this->call('UserTokensSeeder');
Ok, i will fix it right away. Thanks!

2023-11-06 17:39 UTC, FernandoJoachin approved these changes
Nice Job!

2023-11-07 00:19 UTC, Mauriciocr207 approved these changes

2023-11-07 00:19 UTC, CheloChidoone approved these changes
Good job @CarlosJCD

2023-11-07 16:49 UTC, Cristianpan approved these changes
Please make the changes before merging

2023-11-07 16:49 UTC, Cristianpan commented on app/Controllers/CtrlLogin.php
> +            exit();
Please remove this sentence

2023-11-07 16:49 UTC, Cristianpan commented on app/Controllers/CtrlLogin.php
> +                exit($errors);
Please remove this sentence

2023-11-07 16:50 UTC, CarlosMay7 approved these changes

2023-11-08 23:53 UTC, CheloChidoone commented
@LUGAMAFE This PR is blocking the merge because apparently you still requested changes, is that correct or should this be approved for merge?

2023-11-09 01:42 UTC, LUGAMAFE commented
Still need changes I need to talk with @CarlosJCD

2023-11-09 17:37 UTC, LUGAMAFE approved these changes

2023-11-11 18:07 UTC, LUGAMAFE reviewed
I rechecked the code since I saw that you created new commits @CarlosJCD everything works fine but I left a couple of Nitpicks for you :)

2023-11-11 18:07 UTC, LUGAMAFE commented on app/Controllers/CtrlUser.php
> +        return $tokenData['userToken'];
We have to places where we use this exact same code @CarlosJCD `CtrlEmail` and `CtrlUser` maybe create another method inside the `TokenGenerator` class and include a static method called `createNewUserToken($userId)` and include the exact same code that you have here inside `newToken($userId)` 

With that we can reuse this code inside `CtrlEmail`
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/4d44784e-f3b3-49c5-9c54-fbf13b57b411)

2023-11-14 02:02 UTC, LUGAMAFE approved these changes

2023-11-14 04:31 UTC, merged