KIN-214 Filepond configuration from server
loopcrack-org/Kinub pull request #104
Opened 2023-11-09 00:50 UTC by Mauriciocr207

## Summary

### Problem

It is needed to generate the filepond configuration for filepond inputs from the server

### Solution

Create a generic configuration for filepond library for the manage of files on cliente side and server.

## Acceptance Criteria

### Requirements checklist

- [x] The server must create a filepond configuration for the client side
- [x] It must create a view for test this feature
- [x] This filepond configuration must be sended trough the view
- [x] It must generate a filepond javascript configuration on client side.
- [x] The filepond javascript must get the configuration for filepond from the view
- [x] The filepond configuration must have the configuration for all inputs that use the filepond library in the view
- [x] The script in javascript must iterate on all inputs and configurate the filepond instances with the filepond configuration obtained from server
- [x] The script must manage all alerts and information messages for the user.
- [x] It must allow the basic functionality between filepond and the files API (without file chunks )
- [x] It must not allow to submit the form if the user is uploading files
- [x] It should display an informative alert if the user has updated the maximum allowed files

### Testing

You need to make sure to go to route `/admin/testFiles/crear` and make `npm install` to install al filepond dependencies. 
- [x] Verify that the alert messages are showed correctly
- [x] Verify that files are uplodaded correctly

## Demo

https://github.com/loopcrack-org/Kinub/assets/70463645/a30ce535-97f9-44e4-9a0e-578c37143e04

2023-11-10 04:33 UTC, CarlosMay7 reviewed
I think everything is fine overall. I just noticed one thing, when I tried to drag more than 3 images it doesn't show me any error or warning message that says the maximum is 3

2023-11-10 05:14 UTC, LUGAMAFE reviewed
Asu esta muy duro este codigo. Pero no voy a mentir tambien esta complicado de leer en una hora @Mauriciocr207 creo que va hacer una sesion en donde expliques a todos como funciona esto paso a paso.

2023-11-10 18:45 UTC, Mauriciocr207 commented
> I think everything is fine overall. I just noticed one thing, when I tried to drag more than 3 images it doesn't show me any error or warning message that says the maximum is 3

The script doesn´t show explicitly that the maximum is three files, but show this:
![Captura de pantalla (1424)](https://github.com/loopcrack-org/Kinub/assets/70463645/431108a9-68f6-40b0-a08e-4e536f890660)

2023-11-10 19:04 UTC, Mauriciocr207 commented
> Asu esta muy duro este codigo. Pero no voy a mentir tambien esta complicado de leer en una hora @Mauriciocr207 creo que va hacer una sesion en donde expliques a todos como funciona esto paso a paso.

I made the suggested corrections @LUGAMAFE

2023-11-10 19:13 UTC, Mauriciocr207 commented on src/admin/js/pages/plugins/filepond/filepond-general-config.js
> +const inputsConfig = JSON.parse(document.querySelector('#config').value);
It was planned to make the filepond script only for one form. Doing it for multiple forms requires a little more complexity. Do you consider it necessary to change the name of the script in order it could be more descriptive?

2023-11-11 01:58 UTC, CheloChidoone reviewed
@Mauriciocr207 I'll leave this just as a comment for now before the meeting where you will explain everything to remind you to check these things we talked about:

- Add the missing validation that May told you about when trying to upload more files than the maximum allowed
- Change the text that appears in english in the file uploaders to spanish

2023-11-11 05:39 UTC, Mauriciocr207 commented
> I think everything is fine overall. I just noticed one thing, when I tried to drag more than 3 images it doesn't show me any error or warning message that says the maximum is 3

@CarlosMay7 , @CheloChidoone , told me what was the error. I fix it, try again please.

2023-11-11 06:36 UTC, CarlosMay7 approved these changes

2023-11-12 20:49 UTC, CheloChidoone requested changes
It looks very good and works well @Mauriciocr207, I left a couple of comments about small improvements.

2023-11-12 20:49 UTC, CheloChidoone commented on app/Controllers/CtrlTestFiles.php
> +        return view('admin/test/testFilesCreate', ['config' => $this->filepondConfig]);
Here like Luis recommended I think we should call the config we send `filepondConfig` and use it in the views as `$filepondConfig` to make it more specific

2023-11-12 20:49 UTC, CheloChidoone commented on src/admin/js/pages/plugins/filepond/_validations.js
> +        : `Ha intentado ingresar más archivos de los permitidos. Por favor, intente con una menor cantidad de archivos`,
Here I see you have access to the max files and current file number so the error message could be more complete like this, you can rephrase this but the important thing is to give the user the information about the permitted files limits since we have it there:
```suggestion
        : `Ha intentado ingresar más archivos de los permitidos. El máximo de archivos permitidos es de ${pond.maxFiles}, puede ingresar hasta ${pond.maxFiles - numPondFiles} archivos más`,
```

2023-11-13 03:53 UTC, CarlosJCD approved these changes

2023-11-13 04:54 UTC, Mauriciocr207 commented on app/Controllers/CtrlTestFiles.php
> +        return view('admin/test/testFilesCreate', ['config' => $this->filepondConfig]);
@CheloChidoone, ready this correction

2023-11-13 04:54 UTC, Mauriciocr207 commented on src/admin/js/pages/plugins/filepond/_validations.js
> +        : `Ha intentado ingresar más archivos de los permitidos. Por favor, intente con una menor cantidad de archivos`,
Thanks, it is a better message

2023-11-13 09:08 UTC, FernandoJoachin approved these changes

2023-11-13 22:50 UTC, CheloChidoone approved these changes

2023-11-14 01:43 UTC, merged