KIN-264 create certificate table
loopcrack-org/Kinub pull request #105
Opened 2023-11-13 02:22 UTC by FernandoJoachin

## Summary

### Problem

As an admin panel user, I want in the admin panel to see all the certificate records, edit those records, delete certificates and create new ones so that I can manage the certificates that will be displayed in the public view. .

### Solution

Make a page where you can view all certificate records, edit those records, delete certificates, and create new ones so you can manage the certificates that will be displayed in public view. .

## Acceptance Criteria

### Requirements checklist

- [ ] It must display the certificates records on a table, where it would display the following info: Certificate Name, Certificate image preview and Edit and delete buttons on the same column.
- [ ] It must have a search bar that filters by name.
- [ ] It must have a create button above the table of the records

### Testing

- [ ] Go to the next route: http://kinub.cm/admin/certificados

## Demo

[![imagen-2023-11-12-202200868.png](https://i.postimg.cc/CxWhtNYF/imagen-2023-11-12-202200868.png)](https://postimg.cc/hX1RQVfw)

2023-11-13 17:36 UTC, Oswaldo-Chan requested changes
I was reviewing the files with @Cristianpan and we noticed that this view implements styles in the HTML when it can use bootstrap classes.

2023-11-13 17:36 UTC, Oswaldo-Chan commented on app/Views/admin/certificates/Certificates.php
> +                        <table id="certificates-table" class="table nowrap dt-responsive align-middle table-hover table-bordered" style="width:100%">
Please remove the style line and replace it by adding the `w-100` class

2023-11-13 17:36 UTC, Oswaldo-Chan commented on app/Views/admin/certificates/Certificates.php
> +                                                <a href="/admin/certificados/editar/<?= $certificate['certificateId']; ?>" class="btn btn-primary btn-icon waves-effect waves-light mb-2" style="width:
Please remove the style line and replace it by adding the `w-100` class

2023-11-13 17:36 UTC, Oswaldo-Chan commented on app/Views/admin/certificates/Certificates.php
> +                                                <a href="#" class="btn btn-danger btn-icon waves-effect waves-light" data-bs-toggle="modal" style="width: 100%;"><i class="ri-delete-bin-5-line ri-lg">
Please remove the style line and replace it by adding the `w-100` class

2023-11-13 18:11 UTC, Cristianpan requested changes
Good job @FernandoJoachin , however I have noticed along with @Oswaldo-Chan some details in the design, mainly in the galaxy fold view. 
As you can see, when you want to see more details of the certificate, the table overflows.
![image](https://github.com/loopcrack-org/Kinub/assets/91033040/a5f683d8-87b0-48dc-af39-25e80b4ca01b)

Likewise, it's something very subtle but the aspect ratio of the image doesn't correspond to the original proportion, so it looks deformed. 
![image](https://github.com/loopcrack-org/Kinub/assets/91033040/f7028c32-520c-47da-aed2-24d5278e53a1)

I have left the suggestion so that you can correct those details.

2023-11-13 18:11 UTC, Cristianpan commented on app/Views/admin/certificates/Certificates.php
> +                                                <img src="<?= $certificate['fileRoute']; ?>" alt="Imagen del certificado " . <?= $certificate['certificateId']; ?> width="200" height="100">
Add the "mw-100h-auto" classes
```suggestion
                                                <img class="mw-100 h-auto" src="<?= $certificate['fileRoute']; ?>" alt="Imagen del certificado " . <?= $certificate['certificateId']; ?> width="200" height="100">
```

2023-11-14 02:58 UTC, LUGAMAFE approved these changes
Replace all `style="width:100%"`  with `w-100` as @Oswaldo-Chan mention 

And don´t worry about this overflow its a problem with datatables  ![image](https://github.com/loopcrack-org/Kinub/assets/24960025/8a8fd58b-74ff-4a7c-aa36-639dfd9855ae)

2023-11-15 02:31 UTC, Mauriciocr207 approved these changes

2023-11-15 02:31 UTC, FernandoJoachin commented
> Nice work!, we just saw a little problem with the certificate images. At resolutions 600px wide or smaller the images start to deform. We thought you could activate the mobile view at 600px or make the image resize when reaching 600px.
> 
> CC: @CheloChidoone

I already solved the problem. Add the following to the image: object-fit-contain

2023-11-15 02:33 UTC, Mauriciocr207 commented
> > Nice work!, we just saw a little problem with the certificate images. At resolutions 600px wide or smaller the images start to deform. We thought you could activate the mobile view at 600px or make the image resize when reaching 600px.
> > CC: @CheloChidoone
> 
> I already solved the problem. Add the following to the image: object-fit-contain CC: @Mauriciocr207

Wee see that if you set the image with the property :
```css
object-fit: content
```
the image mantain itsaspect

2023-11-15 16:42 UTC, LUGAMAFE approved these changes

2023-11-15 16:43 UTC, CarlosMay7 approved these changes

2023-11-16 04:21 UTC, Oswaldo-Chan approved these changes

2023-11-16 04:21 UTC, Cristianpan approved these changes

2023-11-16 16:20 UTC, CarlosJCD approved these changes

2023-11-16 16:35 UTC, merged