KIN-98: Modal Product Form Window
loopcrack-org/Kinub pull request #106
Opened 2023-11-13 09:44 UTC by Oswaldo-Chan

## Summary

### Problem

"The user would like to obtain more information about a product.

### Solution

A contact form has been implemented that appears when a user clicks the 'more info' button. This way, the user can make a direct request for a specific product.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ]The form must appear when clicked the “view more“ button
- [ ]The modal window of the form must be closed via a quit button, by clicking outside the window or by pressing the escape key.
- [ ]The form of the modal window must be the same as the contact form of the home page, but with the product field already filled.
- [ ]The form of the modal window must follow the same behavior as the form of the home page.

### Testing

Describe any tests (manual or automated) executed to verify your changes

First, run 'npm install' to add the tingle.js library

- [ ] Test responsive design
- [ ] Test modal functionality

## Resources

[Mock-up](https://drive.google.com/file/d/1OCkHMqtnTJrGSnf7XMAXHb069FtjrW4L/view?usp=sharing)

## Demo

[VIDEO DEMO](https://clipchamp.com/watch/aXN9AcbJ1oH)

2023-11-14 00:55 UTC, CarlosMay7 commented on src/public/js/product.js
> +  onOpen: function () {
```suggestion
```
Delete this function please

2023-11-14 00:56 UTC, CarlosMay7 commented on src/public/js/product.js
> +  onClose: function () {
```suggestion
```
This one too

2023-11-14 01:17 UTC, CarlosMay7 commented on src/public/sass/UI/product/_modal-form.scss
> +    }
```suggestion
    }
    &__content {
      padding: 3rem 3rem 0;
    }
```
Also add this, but make sure that on the mobile view the button is still aligned with the inputs

2023-11-14 01:24 UTC, CarlosMay7 commented on src/public/sass/UI/product/_modal-form.scss
> +.modal-form {
The window should be a little smaller and you should see the "x" button to close in all sizes.

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/5cfdde34-e64c-4aa1-9791-7709e1596f3c)
For example here in the phone size I can barely see the "x"

2023-11-14 01:33 UTC, CarlosMay7 commented on src/public/sass/UI/product/_modal-form.scss
> +    font-size: 1.5rem;
The size of the titles are different than those of the mockup
```suggestion
    font-size: 2.5rem;
```

You can change to this value and modify de mobile view to make it look like this

2023-11-14 01:33 UTC, CarlosMay7 commented on src/public/sass/UI/product/_modal-form.scss
> +      font-size: 2.5rem;
```suggestion
      font-size: 4rem;
```
Here too

2023-11-14 01:40 UTC, CarlosMay7 commented on src/public/sass/UI/product/_modal-form.scss
> +
You're using a background dimming, that doesn't appear in the mockup, I like it but it is not in the mockup so I don't know if it must be like that

I'm also not a big fan of the mouse turning into an "x" when exiting the form but that's my personal preference.

2023-11-14 01:41 UTC, CarlosMay7 requested changes
I left you some comments and suggestions.

2023-11-14 06:48 UTC, Cristianpan requested changes
![image](https://github.com/loopcrack-org/Kinub/assets/91033040/d6e2ed7d-f531-44f2-b396-6d22ec15c3af)

You should add a `margin-bottom` and correct that the color where the button is located is the same as the rest of the form container. 

I've also left you other comments and suggestions.

2023-11-14 06:48 UTC, Cristianpan commented on app/Views/public/product.php
> +            <input class="modal-form__product" type="text" name="product" value="Medidor de nivel de radar 80G">
This input must be disabled so that the user cannot modify it. Likewise, you have forgotten to add a hidden input for the product model, this is based on RF-14

2023-11-14 16:47 UTC, LUGAMAFE commented
Things are missing to make the modal look like the original design:

- The modal is not as large in desktop views.
- The modal has a blue border
- The modal has a border radius that is not present.
- The Medidor de nivel de radar 80G text should not be editable. 
- The modal background should be more transparent and not so black. While I like the way it looks now, make it more transparent please.
- Correct this first before I make a complete revision.

![image](https://github.com/loopcrack-org/Kinub/assets/24960025/49fedc7b-8c62-4c50-ac30-314e4d7f1933)

![image](https://github.com/loopcrack-org/Kinub/assets/24960025/72cbdf73-93cc-40b0-9f9c-4160599ad6ee)

2023-11-14 17:11 UTC, CarlosJCD requested changes
We detected some other issues on this modal form:
- We think that the font and color for the other inputs of the modal form should not be the same as the product name input.
- The product name input should not be editable.
- When typing on the form inputs, the cursor should be on the left instead of being centered
- The submit button does not have the same backgroudn color as in the mockup
- The submit button text must be in _italic_ and must be bolder.

CC: @CheloChidoone

2023-11-17 03:02 UTC, Mauriciocr207 reviewed
I left you some comments, please check and comment us about the close button
CC: @FernandoJoachin

2023-11-17 03:02 UTC, Mauriciocr207 commented on src/public/sass/UI/product/_modal-form.scss
> +      visibility: hidden;
In your demo appear a close button, but when I prove, it never appear. Maybe is is because of this property
```css
visibility: hidden
```

2023-11-17 10:02 UTC, Oswaldo-Chan commented on src/public/sass/UI/product/_modal-form.scss
> +      visibility: hidden;
Hi @Mauriciocr207, I chose to keep the close button for the modal on mobile devices because the modal occupies most of the screen space, making it easier for users to exit. However, I noticed there is no button in the mockup for larger devices, so I removed it since there are other exit options, such as clicking outside the modal or using the 'Escape' key. Is it better if I reintroduce the button?

2023-11-17 17:03 UTC, CarlosMay7 commented
Hey @Oswaldo-Chan you must update your demo every time you make changes so we can see the current design

2023-11-17 17:26 UTC, LUGAMAFE approved these changes
Nice work @Oswaldo-Chan it looks better just correct the nitpicks that i added please before merging

2023-11-17 17:26 UTC, LUGAMAFE commented on src/public/sass/UI/product/_modal-form.scss
> +  background-color: rgb(1 1 1 / 0.3);
```suggestion
  backdrop-filter: blur(1.5px);
  background-color: transparent;
```
-webkit prefix is not necessary since we have a gulp task that help us to add those prefixes in the final css. 

We me and @CarlosMay7 decided to completly remove the color of the backgorund and make it transparent. 
And reduce de amount of blur. That should do a better match with the mockups.

2023-11-17 17:26 UTC, LUGAMAFE commented on src/public/sass/UI/product/_modal-form.scss
> +    box-shadow: 0px 0px 25px 8px rgba(0, 0, 0, 0.51);
```suggestion
    box-shadow: 5px 5px 12px 5px #00000082;
```
Again prefixes not needed and please change the box shadow with this one.

2023-11-17 17:26 UTC, LUGAMAFE commented on src/public/sass/UI/product/_modal-form.scss
> +      padding: 2rem;
```suggestion
      padding: 2rem 3rem;
```

2023-11-18 03:52 UTC, Mauriciocr207 commented on src/public/sass/UI/product/_modal-form.scss
> +      visibility: hidden;
I think that if you dont need to use the button, maybe it is better delete it from the html and css

2023-11-18 18:42 UTC, Cristianpan approved these changes

2023-11-18 19:44 UTC, CarlosJCD approved these changes
Looks a lot better now, nice job.

2023-11-18 19:44 UTC, CheloChidoone commented on src/public/sass/UI/product/_modal-form.scss
> +      visibility: hidden;
@Mauriciocr207 I think the close button is needed but only for mobile devices when the modal covers all the screen, for desktop I think @Oswaldo-Chan followed the design correctly since the mockup doesn't have a close button so it's fine like this.

2023-11-18 19:45 UTC, CheloChidoone approved these changes
Good job @Oswaldo-Chan .

2023-11-20 16:48 UTC, CarlosMay7 approved these changes
Nice job! Just update your branch and it's all set

2023-11-20 17:51 UTC, merged