KIN-299 File chunks implementation
loopcrack-org/Kinub pull request #107
Opened 2023-11-14 02:52 UTC by Mauriciocr207

## Summary

### Problem

It is needed a way to deal with big files uploaded by the users.

### Solution

Implement chunk files for bigger files uploaded by the users

## Acceptance Criteria

### Requirements checklist

- [x] The routes must have a route where the filepond script can be able to send patch request
- [x] The CtrlApiFiles must manage the patch request where can be able to manage big files in chunks.
- [x] The FileManager class must have a method that merge all fragments of a file sended in chunks.

### Testing

- [x] Remember install all dependencies with `npm install` and run the project with `npm run dev:admin`
- [x] Into the filepond configuration setted from the class CtrlTestFiles you can see the values `chunkUploads = true` and `chunkSize = 100000` that means that now filepond can try to process files bigger than the `chunkSize` setted in bytes. 
- [x] Try to upload a file you know is bigger than `100000 bytes`, then you can see how the file is uploading. 

## Resources

[Reference Filepond Chunks](https://pqina.nl/filepond/docs/api/server/#process-chunks) 

## Demo

https://github.com/loopcrack-org/Kinub/assets/70463645/cf1eadb5-6d8b-48b7-b348-7eab09868c4f

2023-11-14 22:02 UTC, LUGAMAFE requested changes
Same problem as @CheloChidoone 
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/dbe2af7d-df92-4797-864d-cba6bfb7334a)

2023-11-14 22:02 UTC, LUGAMAFE commented on app/Controllers/CtrlApiFiles.php
> +            return $this->response->setStatusCode(500, json_encode('Ha ocurrido un error mientras se cargaba el archivo'));
```suggestion
             return $this->response->setStatusCode(Response::HTTP_NO_CONTENT);
        } catch (Throwable $th) {
            return $this->response->setStatusCode(Response::HTTP_INTERNAL_SERVER_ERROR , json_encode('Ha ocurrido un error mientras se cargaba el archivo'));
        }
```
Suggestion for better code readability and maintenance
@Mauriciocr207, I recommend using constant variables for HTTP status codes throughout this file. 
This approach not only enhances code readability but also makes the reasons behind each status code more clear.
Ensure to import the `use CodeIgniter\HTTP\Response;` class.

2023-11-15 03:25 UTC, Mauriciocr207 commented
> @Mauriciocr207, We encountered an error, it shows us this error on console while uploading a big file and just stays processing it, and also it doesn't let us click to cancel it. Please check if you have any errors or let us know if we missed a step to test, we followed your test instructions so we don't think we missed anything. ![image](https://user-images.githubusercontent.com/38699927/282868836-dfa8c071-3c7b-4db5-ad7a-683fc924c191.png)
> 
> CC: @CarlosJCD

Sorry, I forgot to say that you need to set the project on production mode, if you don´t, the xmlHttpRequest includes the html of the codeigniter button, and the request fail.

Here the error:
![Captura de pantalla (1445)](https://github.com/loopcrack-org/Kinub/assets/70463645/dade9e77-8014-4e33-abb0-90932440e288)

Here the correcto way to do it
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/a58d7144-7774-49d5-91c0-b382a3f3ac42)

2023-11-15 17:07 UTC, LUGAMAFE approved these changes
Hey @Mauriciocr207 is working now! Nice! But please make the changes about the http response codes in all the file begore merging please

2023-11-15 17:07 UTC, CarlosMay7 approved these changes

2023-11-16 04:11 UTC, Oswaldo-Chan approved these changes
Good job @Mauriciocr207!

2023-11-16 16:43 UTC, CarlosJCD approved these changes

2023-11-16 16:43 UTC, CheloChidoone approved these changes

2023-11-16 23:00 UTC, merged