KIN-300 File Validations
loopcrack-org/Kinub pull request #114
Opened 2023-11-17 06:05 UTC by Mauriciocr207

## Summary

### Problem

It is needed to validate the files given by the users through the CtrlApiFile

### Solution

Define and integrate validations rules on the files given by the users

## Acceptance Criteria

### Requirements checklist

- [x] There must be a File validations object
- [x] The file validation must be integrated on the files API
- [x] Must validate only one file at once according the way the CtrlApiFiles receives the files
- [x] There is a class with set of file validations rules defined and used into the validation services provided by codeigniter.

### Testing

Recommended testing by following:

- [x] Rememeber do `npm install` and `npm run dev:admin` and run the project on production mode
- [x] Go to the controller CtrlTestFiles, and you can see that there is some properties on the filepondConfiguration that are commented, that is in order you can test only the validation from server and filepond doesn´t interfere with the validation
- [x] put your screens like following:
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/e2ec3048-ac8e-4d1a-8ea1-39a66b526029)
- [x] Now you can use the following image to upload on filepond box and test this pull request:
- specifications:
   - size: 158 Kb
   - dims: 1920 x 1080
   - ext: .png
   - mime type: image/png
![3](https://github.com/loopcrack-org/Kinub/assets/70463645/b75939b7-2a62-4189-a73c-f1d40918252f)

- [x] With the specification provided you know how to modify the validation rules on CtrlTestFiles, to prove every rule on validation.
- [x] For example, if you want to prove the maxSize rule, you can set `maxSize[100,kb]` in order the validation fails, because of the file size is 158 kb. you can set `maxSize[200,kb]` in order the validation pass.
- [x] you can do the above with the other validation rules.

## Resources
## Demo

2023-11-18 19:49 UTC, Oswaldo-Chan reviewed
Hi @Mauriciocr207 I left you some comments in the `FileRules.php` file

2023-11-18 19:49 UTC, Oswaldo-Chan commented on app/Libraries/fileValidation/FileRules.php
> +     * @param File  $file   the instance of file
This parameter doesn't correspond to what the function actually accepts; it should be an array called 'files' representing the number of files

2023-11-18 19:49 UTC, Oswaldo-Chan commented on app/Libraries/fileValidation/FileRules.php
> +     * @param File  $file   the instance of file
This parameter doesn't correspond to what the function actually accepts; it should be an array called 'files' representing the number of files

2023-11-18 20:46 UTC, CheloChidoone requested changes
@Mauriciocr207 The file extension validations are not working correctly, testing with Carlos we were able to upload different files that were not images like .csv and .zip, please check that out.

CC: @CarlosJCD

2023-11-18 20:57 UTC, CarlosJCD requested changes
Hi @Mauriciocr207 while reviewing this PR we detected that although the files size are validated, when it comes to the files extensions some extension passes the validations even when they are not supposed to. We tested with a .csv and a .r as you can see in the image.
<img width="1006" alt="Screenshot 2023-11-18 at 14 43 59" src="https://github.com/loopcrack-org/Kinub/assets/89323622/9bf0a782-e311-4292-8251-11b8094c44f1">

Also, for some reason when I upload some kind of files [the page instantly refreshes when the upload reaches 100%](https://drive.google.com/file/d/1O5ERD3GCF0fwy4WwyY0psLchs-RWHl22/view?usp=sharing). This happened with .zip, .docx and some .pdf files. I am not sure if it is a problem with my environment but I resolved that it was worth to mention in the case you could knew why this happens.
 

CC: @CheloChidoone

2023-11-19 01:16 UTC, Mauriciocr207 commented
> @Mauriciocr207 The file extension validations are not working correctly, testing with Carlos we were able to upload different files that were not images like .csv and .zip, please check that out.
> 
> CC: @CarlosJCD

I change the validation on CtrlApiFiles, please, check again. There was problems on validatino of files that are not uploaded by chunks.

2023-11-19 01:19 UTC, Mauriciocr207 commented
> Hi @Mauriciocr207 while reviewing this PR we detected that although the files size are validated, when it comes to the files extensions some extension passes the validations even when they are not supposed to. We tested with a .csv and a .r as you can see in the image. <img alt="Screenshot 2023-11-18 at 14 43 59" width="1006" src="https://user-images.githubusercontent.com/89323622/284022381-9bf0a782-e311-4292-8251-11b8094c44f1.png">
> 
> Also, for some reason when I upload some kind of files [the page instantly refreshes when the upload reaches 100%](https://drive.google.com/file/d/1O5ERD3GCF0fwy4WwyY0psLchs-RWHl22/view?usp=sharing). This happened with .zip, .docx and some .pdf files. I am not sure if it is a problem with my environment but I resolved that it was worth to mention in the case you could knew why this happens.
> 
> CC: @CheloChidoone

Sorry, I didn´t mention this but, that is due to the Browser sync. It reload the page sometimes. You could try using a virtual host.

2023-11-19 01:19 UTC, Mauriciocr207 commented on app/Libraries/fileValidation/FileRules.php
> +     * @param File  $file   the instance of file
I did the corrections

2023-11-20 01:46 UTC, CarlosJCD approved these changes
Nice, now it works fine.

2023-11-20 17:00 UTC, CarlosMay7 approved these changes

2023-11-20 17:00 UTC, CheloChidoone approved these changes
Good Job @Mauriciocr207, It works well now.

2023-11-20 17:48 UTC, Oswaldo-Chan approved these changes

2023-11-20 20:25 UTC, merged