KIN-120 create products page layout
loopcrack-org/Kinub pull request #116
Opened 2023-11-17 11:57 UTC by FernandoJoachin

## Summary

### Problem

As a user of the admin panel i need to visualize the registered products so that i can manage them according to the company needs.

### Solution

Create a table to view the registered products and manage them according to the company's needs.

## Acceptance Criteria

### Requirements checklist

- [ ] It must be displayed the product records in a table. The table must have the following columns: Product Name, Product Model Number, Product Category, Product Representative Image, Edit and delete buttons on the same column.
- [ ] It must have a search bar that filters by name.
- [ ] It must have a create button above the records table.

### Testing
- [x] Run `php spark migrate:refresh` to empty the database on your CLI.
- [x] Then run `php spark db:seed MainTestSeeder` on your CLI.
- [ ] Go to the route: http://kinub.cm/admin/productos

2023-11-18 22:15 UTC, Mauriciocr207 requested changes

2023-11-18 22:15 UTC, Mauriciocr207 commented on app/Controllers/CtrlProduct.php
> +        $products          = $productFilesModel->select('productId, productName, productModel, categoryName, fileRoute')->join('products', 'products.productId = product_files.pfProductId')->join('fil
I think is better to male the consult from the product table and create a method on ProductModel to get all products because the consult on controller is too large

2023-11-20 17:17 UTC, CheloChidoone approved these changes
Good job @FernandoJoachin it looks good, just correct this little nitpicks before merging

2023-11-20 17:17 UTC, CarlosMay7 approved these changes

2023-11-20 17:17 UTC, CheloChidoone commented on app/Views/admin/products/Products.php
> +                                    <th>Categorías</th>
This should be `Categoría` instead of `Categorías` because there will always be only one category per product

2023-11-20 17:17 UTC, CheloChidoone commented on app/Views/admin/products/Products.php
> +                                    <th>Categorías</th>
This should be `Categoría` instead of `Categorías` because there will always be only one category per product

2023-11-20 18:35 UTC, Oswaldo-Chan approved these changes
Good job @FernandoJoachin!

2023-11-21 02:28 UTC, Mauriciocr207 approved these changes

2023-11-22 04:54 UTC, LUGAMAFE approved these changes
Nice Job @FernandoJoachin just a small nitpick

2023-11-22 04:54 UTC, LUGAMAFE commented on app/Views/admin/products/Products.php
> +                                                <img class="mw-100 object-fit-contain" src="<?= $product['fileRoute']; ?>" alt="Imagen del certificado " . <?= $product['productId']; ?> height="150">
```suggestion
                                                <img class="mw-100 object-fit-contain" src="<?= $product['fileRoute']; ?>" alt="<?= 'Imagen del certificado' . $product['productId']; ?>" height="90">
```

Syntax error and can we reuce please the height of the image please. 🙏
To be honest i think maybe we should reduce the size of other table entities too.

2023-11-22 16:21 UTC, CheloChidoone approved these changes

2023-11-23 02:12 UTC, merged