KIN-208: Create Measurement Solution Functionality [Without Files Management]
loopcrack-org/Kinub pull request #121
Opened 2023-11-20 05:22 UTC by CarlosJCD

## Summary

### Problem

It is needed a functionality to create new measurement solution entities on the system.

### Solution

Attached a functionality to the create measurement solution view so that new measurement solutions are actually created. 

## Acceptance Criteria

### Requirements checklist

- [x] It must validate the inputs to not be empty

- [x] In case the inputs are correct, it must store a new register of the measurement solution on the database

- [x] It must return a response to the view indicating success or error.

### Testing

- [x] Create a new measurement record by filling the measurement solution title and description input. 
    - The icon and image inputs will be validated on another PR, for the moment those are ignored on this ticket.]
- [x]  Verify that a new record was created on the database and it is visible on the measurement solutions page

## Demo

2023-11-20 18:57 UTC, Oswaldo-Chan approved these changes
Good job @CarlosJCD! I only noticed some minor changes regarding accentuation. I left you the suggestions just in case, but I'm not sure if they are of much relevance

2023-11-20 18:57 UTC, Oswaldo-Chan commented on app/Controllers/CtrlSolution.php
> +                throw new Exception('Algo salio mal al registrar la solución de medición. Por favor, inténtalo de nuevo.');
```suggestion
                throw new Exception('Algo salió mal al registrar la solución de medición. Por favor, inténtalo de nuevo.');
```

2023-11-20 18:57 UTC, Oswaldo-Chan commented on app/Validation/SolutionValidation.php
> +            'required'    => 'Por favor, ingrese el titulo de la solución de medición',
```suggestion
            'required'    => 'Por favor, ingrese el título de la solución de medición',
```

2023-11-20 18:57 UTC, Oswaldo-Chan commented on app/Validation/SolutionValidation.php
> +            'regex_match' => 'El titulo de la solución de medición solo debe contener caracteres alfabéticos y espacios',
```suggestion
            'regex_match' => 'El título de la solución de medición solo debe contener caracteres alfabéticos y espacios',
```

2023-11-20 18:57 UTC, Oswaldo-Chan commented on app/Views/admin/typeSolutions/Solutions.php
> +                                    <th>Titulo</th>
```suggestion
                                    <th>Título</th>
```

2023-11-20 18:57 UTC, Oswaldo-Chan commented on src/admin/js/pages/form-file-upload-measurementSolution.init.js
> +  labelFileTypeNotAllowed: 'Archivo no valido',
```suggestion
  labelFileTypeNotAllowed: 'Archivo no válido',
```

2023-11-20 18:57 UTC, Oswaldo-Chan commented on src/admin/js/pages/form-file-upload-measurementSolution.init.js
> +    'Arrastra y suelta tu icono o <span class="filepond--label-action"> Selecciona </span>',
```suggestion
    'Arrastra y suelta tu ícono o <span class="filepond--label-action"> Selecciona </span>',
```

2023-11-21 02:44 UTC, FernandoJoachin commented on app/Controllers/CtrlSolution.php
> +            $errors = $validateMeasurementSolution->getErrors();
This element should not be left in the pull request
@Mauriciocr207

2023-11-21 02:51 UTC, FernandoJoachin commented on app/Validation/SolutionValidation.php
> +        'msName'        => 'required|regex_match[^[A-Za-zÁáÉéÍíÓóÚúÜüÑñ\s\']+$]',
We have a question. Can measurement solution titles have numbers? Because if they can, that regular expression doesn't allow for that.
@Mauriciocr207

2023-11-21 02:57 UTC, FernandoJoachin requested changes
You should also include in this pull request displaying the errors generated in the backend on the measurement solution creation form.
@Mauriciocr207

2023-11-22 08:52 UTC, Cristianpan approved these changes
Nice Job! But I left you some suggestions.

2023-11-22 08:52 UTC, Cristianpan commented on app/Controllers/CtrlSolution.php
> +                throw new InvalidInputException($measurementSolutionDataValidator->getErrors(), '');
It's not necessary that you set the second argument with a empty String because it's the default value in the constructor

2023-11-22 08:52 UTC, Cristianpan commented on app/Controllers/CtrlSolution.php
> +        }
Maybe it's a good idea that when there is an error, the application redirects to the same form so that the user can try to submit the form again. And if that weren't the case, that withInput() would be unnecessary

2023-11-22 16:50 UTC, CheloChidoone requested changes
Good Job @CarlosJCD, just make sure to check Cristian's comments before merging and I also left a change you missed

2023-11-22 16:50 UTC, CheloChidoone commented on app/Views/admin/typeSolutions/Solutions.php
> +                                    <th>Título</th>
Here you changed this to `Título` at the top of the table but you forgot to also change it at the bottom, it still says `Nombre` at the bottom, please change that too

2023-11-23 03:57 UTC, LUGAMAFE approved these changes
Nice @CarlosJCD do the requested changes before merge

2023-11-25 04:14 UTC, CarlosMay7 approved these changes

2023-11-25 04:14 UTC, CheloChidoone approved these changes
Good Job @CarlosJCD

2023-11-25 04:49 UTC, FernandoJoachin approved these changes

2023-11-25 17:21 UTC, merged