KIN-278 delete emails functionality email page
loopcrack-org/Kinub pull request #122
Opened 2023-11-20 23:39 UTC by FernandoJoachin

## Summary

### Problem

As an user of the admin panel, I wish to delete an email record so that in case of being needed it can be deleted permanently.

### Solution

Make sure that when you click the delete button, the email in the database is deleted

## Acceptance Criteria

### Requirements checklist

- [ ] It must delete the record from the database
- [ ] It must return a response indicating success or failure on deleting the email record.

### Testing

- [ ] Click the delete button
- [ ] Verify that the record was deleted in the database

2023-11-21 03:29 UTC, Mauriciocr207 approved these changes

2023-11-21 17:25 UTC, CarlosJCD approved these changes

2023-11-21 17:37 UTC, Cristianpan commented on app/Controllers/CtrlAdminEmail.php
> +        $emailId    = $POST['emailId'];
```suggestion
        $emailId       = $this->request->getPost('emailId');
```
You can get the email id directly from the post and it would be good if you use a try catch for database exception handling

2023-11-21 17:37 UTC, Cristianpan approved these changes

2023-11-22 06:31 UTC, LUGAMAFE approved these changes

2023-11-22 16:58 UTC, CheloChidoone requested changes
Good job @FernandoJoachin but we found a bug, once the confirm button is clicked on the delete modal you should block the button because we can click on it many times and even though the delete works it returns an error message because we click it many times, please check that before merging.

2023-11-25 04:19 UTC, CheloChidoone approved these changes

2023-11-25 04:20 UTC, CarlosMay7 approved these changes

2023-11-25 04:47 UTC, merged