KIN-259: Delete measurement solutions Functionality [Without Files Logic]
loopcrack-org/Kinub pull request #123
Opened 2023-11-21 02:42 UTC by CarlosJCD

## Summary

### Problem

It is needed the functionality of the delete measurement solution alert so that the record can be actually deleted

### Solution

Implement the delete logic for the measurement solutions entity.

## Acceptance Criteria

### Requirements checklist

- [x] It must delete the measurement solution record from the database

- [x] It must return a response with a message indicating success on deleting the measurement solution or failure in the process

### Testing

- [ ] Click on the confirm delete button of the delete modal alert.
- [ ] See the response indicating success on the measurement solutions page
- [ ] See how the record was deleted from the database and it is not displayed on the table.

## Resources

## Demo

2023-11-22 06:33 UTC, LUGAMAFE approved these changes

2023-11-22 17:02 UTC, CheloChidoone requested changes
Good job @CarlosJCD but this delete modal has the same bug we found in this other delete PR [KIN-278](https://github.com/loopcrack-org/Kinub/pull/122), once the confirm button is clicked on the delete modal you should block the button because we can click on it many times and even though the delete works it returns an error message because we click it many times, please check that before merging.

2023-11-23 16:40 UTC, Cristianpan approved these changes
I approve this on the assumption that the correction mentioned by @CheloChidoone  will be made at a later date.

2023-11-28 02:22 UTC, CheloChidoone approved these changes

2023-11-28 05:00 UTC, Mauriciocr207 approved these changes

2023-11-28 16:13 UTC, merged