Feature/kin 200 create category functionality
loopcrack-org/Kinub pull request #127
Opened 2023-11-22 08:10 UTC by Cristianpan

## Summary

### Problem

What problem does this pull request aim to solve? Include relevant motivation and context.

### Solution

How does this pull request solve that problem? List any dependencies that are required for this change.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] Requirement A
- [ ] Requirement B

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Test A
- [ ] Test B

## Resources

- [Technical Design Document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/$END_POINT)

## Demo

If applicable, include screenshots and/or screen recordings associated with your solution

2023-11-24 05:21 UTC, LUGAMAFE requested changes
We need to show a error message in the tags input when is not filled @Cristianpan 

https://github.com/loopcrack-org/Kinub/assets/24960025/de1d5292-44ca-46d9-a341-c2acc94f1826

2023-11-25 05:26 UTC, Mauriciocr207 approved these changes

2023-11-25 05:30 UTC, FernandoJoachin approved these changes

2023-11-25 06:21 UTC, CheloChidoone approved these changes
Good Job @Cristianpan

2023-11-25 19:56 UTC, LUGAMAFE approved these changes

2023-11-27 15:23 UTC, merged