KIN-303 create certificate functionality [no files functionality yet]
loopcrack-org/Kinub pull request #128
Opened 2023-11-22 15:49 UTC by FernandoJoachin

## Summary

### Problem

As an administrator of the admin panel, I want to register the company certificates so that they can be displayed on the certificates page of the public view

### Solution

Create a page to register company certificates so that they can be displayed on the certificates page in public view.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] It must validate the form inputs to not be empty
- [ ] If it passes all the validations, the certificate record must be stored in the database
- [ ] It must return a response to the view indicating success on storing the certificate or failure in the process
- [ ] For the moment, the files inputs will be ignored and when storing on the database, it will be used a hardcoded value.

### Testing

- [ ] Go to the route: http://kinub.cm/admin/certificados/crear and create a certificate.
- [ ] Check that it was saved correctly in the database.

2023-11-24 05:33 UTC, LUGAMAFE requested changes
Hey @FernandoJoachin it works but can you please check this PR just to try to follow the same pattern that @Cristianpan is doing 

https://github.com/loopcrack-org/Kinub/pull/127/files#diff-9950aada403367d801a1824368fa2b807f2df03b92f2be0d709a23bc9b37503a

2023-11-25 05:28 UTC, Mauriciocr207 approved these changes
This not correspond to this ticket but I have a comment about the file `/app/Models/FileModel` where there is something like this:

```php
protected function getFileEntity(array $data)
    {
        $uuid                               = $data['data']['uuid'];
        $outputFolder                       = './uploads/' . $uuid;
        $sourceFolder                       = './files/tmp/' . $uuid;
        $filePath                           = scandir($sourceFolder)[2];
        $data['data']['fileRoute']          = "{$outputFolder}/{$filePath}";
        $data['data']['fileDirectoryRoute'] = $outputFolder;
        $data['data']['fileName']           = $filePath;

        return $data;
    }
```

On the `$sourceFolder ` and `$outputFolder ` the route was saved on database like a relative route, that cause an error when you try to load the imagen on the view. 
Here with error
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/216a4095-35d7-452c-84ac-d38c93388460)

Here correct
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/e3cced0b-f762-4ce8-8c00-ba1e56275fb0)
 

@LUGAMAFE , @CheloChidoone , @Cristianpan  this can be changed on this ticket?

2023-11-25 06:28 UTC, CheloChidoone commented
> This not correspond to this ticket but I have a comment about the file `/app/Models/FileModel` where there is something like this:
> 
> ```
> protected function getFileEntity(array $data)
>     {
>         $uuid                               = $data['data']['uuid'];
>         $outputFolder                       = './uploads/' . $uuid;
>         $sourceFolder                       = './files/tmp/' . $uuid;
>         $filePath                           = scandir($sourceFolder)[2];
>         $data['data']['fileRoute']          = "{$outputFolder}/{$filePath}";
>         $data['data']['fileDirectoryRoute'] = $outputFolder;
>         $data['data']['fileName']           = $filePath;
> 
>         return $data;
>     }
> ```
> 
> On the `$sourceFolder ` and `$outputFolder ` the route was saved on database like a relative route, that cause an error when you try to load the imagen on the view. Here with error ![image](https://private-user-images.githubusercontent.com/70463645/285567014-216a4095-35d7-452c-84ac-d38c93388460.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4OTM3NjUsIm5iZiI6MTcwMDg5MzQ2NSwicGF0aCI6Ii83MDQ2MzY0NS8yODU1NjcwMTQtMjE2YTQwOTUtMzVkNy00NTJjLTg0YWMtZDM4YzkzMzg4NDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA2MjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NDhlNjQ4MWUyOGYyNGFiMTFiZjMzMzUzNTdhNzRiOWFjZmY4YTg5MzBkYmUxMWIyOWM4M2MyZTVhYjY2OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I38vUMJ9ZP0i8LIdi6R8-9BfstqSp8cGF2XpLXyP5hs)
> 
> Here correct ![image](https://private-user-images.githubusercontent.com/70463645/285567041-e3cced0b-f762-4ce8-8c00-ba1e56275fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4OTM3NjUsIm5iZiI6MTcwMDg5MzQ2NSwicGF0aCI6Ii83MDQ2MzY0NS8yODU1NjcwNDEtZTNjY2VkMGItZjc2Mi00Y2U4LThjMDAtYmExZTU2Mjc1ZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA2MjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYzk4M2M2ZGQyMjRlZTRkZWJlZWE3NTdjYzk0M2M3ZWI0ZjNkYjI0NDNkNzE5Y2I3NzY5N2M1MmVlMzM1NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q6nyavIcd7SwB4uu9KreV5F1PS-6TnbxpfdcuwfbHP4)
> 
> @LUGAMAFE , @CheloChidoone , @Cristianpan this can be changed on this ticket?

Thanks for noticing this @Mauriciocr207, I think it is a good idea to fix it here since we see it directly starts affecting the certificates table view because it shows the images

2023-11-25 17:05 UTC, Cristianpan approved these changes
Nice job, just make the changes requested by @Mauriciocr207  and take into account the one I've left you

2023-11-25 17:05 UTC, Cristianpan commented on app/Controllers/CtrlCertificate.php
> +            $certificateData['certificatefileId']    = '4fe307c224811d55048d72b5696895eb';
That hash code represents the identifier of a temporary folder, so add a folder with that identifier and its associated file or use the existing one, for example: `3ea307c224811d55048d72b5696895eb`, otherwise it generates an error. 
```suggestion
            $certificateData['certificatePreviewId'] = '3ea307c224811d55048d72b5696895eb';
            $certificateData['certificatefileId']    = '3ea307c224811d55048d72b5696895eb';
```

2023-11-25 19:59 UTC, LUGAMAFE approved these changes
Same comment as @Cristianpan

2023-11-28 05:25 UTC, merged