KIN-311 refactor styles product catalog page
loopcrack-org/Kinub pull request #132
Opened 2023-11-24 06:24 UTC by CarlosMay7

## Summary

### Problem

With the new CSS architecture, it is needed to integrate it into the existing public pages.

### Solution

Integrate ITCSS and Atomic design on the product catalog page styles

## Acceptance Criteria

### Requirements checklist

- [ ] The product catalog page styles must follow the ITCSS and Atomic design established rules.

### Testing

- [ ] Manually Tested responsiveness

## Resources

Pull request #125 

## Demo

2023-11-25 06:54 UTC, CheloChidoone requested changes
I think it looks good @CarlosMay7 but I have a comment and a question:

- We need to rename the `grifo` image because the production server is case sensitive with files and on the page you use lowercase on the `src`, so the file name should be in lowercase to match that correctly
- Did you leave one image `src` as `https://cdn-icons-png.flaticon.com/512/6152/6152273.png` to show how a different one looks or is this an error?, if it is an error please correct it also

2023-11-25 06:54 UTC, CheloChidoone commented on public/assets/images/Grifo.png
Rename to `grifo.png` instead of `Grifo.png`

2023-11-25 16:38 UTC, Cristianpan approved these changes
All good, just make the requested change

2023-11-25 20:08 UTC, CarlosMay7 commented
> I think it looks good @CarlosMay7 but I have a comment and a question:
> 
> * We need to rename the `grifo` image because the production server is case sensitive with files and on the page you use lowercase on the `src`, so the file name should be in lowercase to match that correctly
> * Did you leave one image `src` as `https://cdn-icons-png.flaticon.com/512/6152/6152273.png` to show how a different one looks or is this an error?, if it is an error please correct it also

I left that image in order to show how a PNG would look like

2023-11-25 20:25 UTC, LUGAMAFE commented
@CarlosMay7 remember always add a demo video or images

2023-11-25 20:34 UTC, CheloChidoone approved these changes

2023-11-25 21:07 UTC, Oswaldo-Chan approved these changes
Good Job @CarlosMay7

2023-11-25 21:22 UTC, FernandoJoachin approved these changes

2023-11-25 21:25 UTC, LUGAMAFE requested changes
Nice work @CarlosMay7 just please can you add more image products with different aspect ratios, size and shapes just to confirm that all images look good in this view. 

And correct all the nitpciks I left you.

2023-11-25 21:25 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/category/_category.scss
> +@use 'sass:color';
third party imports go first

2023-11-25 21:25 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/category/_product.scss
> +@use 'sass:color';
third party imports go first

2023-11-25 21:25 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/category/_product.scss
> +  box-sizing: border-box;
It is not necessary because we have already defined the box-sizing property for all elements in this file, it is part of the css reset: 

`src\public\sass\ITCSS\03_generic\_box-sizing.scss`

2023-11-26 00:52 UTC, LUGAMAFE approved these changes
Good work @CarlosMay7  just analyze if you think my proposed change could be easier for the product images sizes.

2023-11-26 00:52 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/category/_product.scss
> +  }
I think we can improve the code and aspect ratio of the images using this code @CarlosMay7 
```suggestion
  &__image {
    width: 70%;
    aspect-ratio: 10 / 12;
    object-fit: contain;
    transition: transform 300ms ease;
  }
```

2023-11-27 00:20 UTC, merged