KIN 312: refactor styles of product page
loopcrack-org/Kinub pull request #133
Opened 2023-11-25 20:29 UTC by Oswaldo-Chan

## Summary

### Problem

With the new CSS architecture, it is needed to integrate it into the existing public pages.

### Solution

 Integrate ITCSS and Atomic design on the product page.

## Acceptance Criteria

### Requirements checklist

- [x] The product page styles must follow the ITCSS and Atomic design rules stablished.

### Testing

- [x] Manually Tested responsiveness

## Resources

- [Product page mock-up](https://www.figma.com/file/tYsUcIlsoqhexMLD0FfjHW/KINUB%2FWEB?type=design&node-id=9%3A617&mode=design&t=xU4LowJvKTOfp2Jn-1)

## Demo

2023-11-27 17:04 UTC, CheloChidoone approved these changes
Good job @Oswaldo-Chan, it looks better, we only have one slight issue we would like to see if you can solve at some point which is for the video you put on the carrousel, the preview image doesn't match the video, it should match the video so we should have a way to get an image from the video that can be used as the preview image on the carrousel

CC: @Cristianpan

2023-11-27 22:31 UTC, CheloChidoone requested changes
I rechecked everything and found these errors @Oswaldo-Chan, please check them and solve them

2023-11-27 22:31 UTC, CheloChidoone commented on src/public/sass/ITCSS/06_components/pages/product/_details.scss
> +    color: color.adjust($color-gray-60, $lightness: 5%);
Add this color to the colors file in 01_settings and use it from there instead of using it like this, I see you use this adjusted color multiple times so replace it wherever you use it by just using the color you define in the colors file

2023-11-27 22:31 UTC, CheloChidoone commented on src/public/sass/ITCSS/06_components/pages/product/_details.scss
> +    font-weight: 800;
Don't use standalone font-weight values, use the variables from `src/public/sass/ITCSS/01_settings/_fonts.scss` instead, do this for all the font-weights you used

2023-11-27 22:31 UTC, CheloChidoone commented on src/public/sass/ITCSS/06_components/pages/product/carousel/_glide.scss
> +    border: 1px solid $color-aqua-blue;
Avoid using pixels, change the unit to rem or em with the value that should correspond

2023-11-27 22:31 UTC, CheloChidoone commented on src/public/sass/ITCSS/06_components/pages/product/carousel/_glide.scss
You should use Non-Nested approach for the media queries and other selectors in this file since it is longer than 100 lines by a lot

2023-11-27 22:31 UTC, CheloChidoone commented on src/public/sass/ITCSS/06_components/pages/product/carousel/_glide.scss
> +    /* stylelint-disable-next-line plugin/selector-bem-pattern */
Why did you have to disable these checks and break the BEM methodology?, Try to change all these selectors so you follow the BEM methodology and there are no disabled checks

2023-11-27 22:31 UTC, CheloChidoone commented on src/public/sass/ITCSS/06_components/pages/product/modal-form/_custom-modal-form.scss
> +    box-shadow: 0.3125rem 0.3125rem 0.75rem 0.3125rem #00000082;
Try not to use colors that are not defined in `src/public/sass/ITCSS/01_settings/_colors.scss`, check if any of the already defined colors fit your needed color here, and if not then add it to the colors

2023-11-28 06:04 UTC, Mauriciocr207 requested changes

2023-11-28 06:04 UTC, Mauriciocr207 commented on src/public/sass/ITCSS/06_components/pages/product/carousel/_carousel.scss
> +    }
I think here, you can create a new breakpoint on your `src/public/sass/ITCSS/02_tools/_breakpoints.scss` and use it here

2023-11-28 15:27 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/product/carousel/_carousel.scss
> +    }
we actually have mixin called device() if we need to use custom sizes like this one @Mauriciocr207 @Oswaldo-Chan

2023-11-28 15:28 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/product/modal-form/_custom-modal-form.scss
> +  .tingle-modal-box {
`.tingle-modal` should be in his own file since this code is from another library

2023-11-29 00:16 UTC, Oswaldo-Chan commented on src/public/sass/ITCSS/06_components/pages/product/modal-form/_custom-modal-form.scss
> +  .tingle-modal-box {
I have created a class that will modify each element of the modal to have a customized design. In JavaScript, I pass this class to the library so that it can apply it to the modal.

2023-11-29 01:51 UTC, Tort9994 commented on src/public/sass/ITCSS/06_components/pages/product/modal-form/_custom-modal-form.scss
> +  .tingle-modal-box {
@Oswaldo-Chan i tried to put this classes on his own file on the same directory and it still works, they are still being apply and i think its a little bit easer,also you will not use stylelint-disable-next-line plugin/selector-bem-pattern. If you still need it you can change it, but if not thats fine

2023-11-29 03:22 UTC, Tort9994 requested changes
![capturaa](https://github.com/loopcrack-org/Kinub/assets/108017207/f76f1a07-a4b6-42af-879c-2353ff975f9d)
i think the divaders are so huge compared to others we use on the page on mobile sizes, 
![captura-a](https://github.com/loopcrack-org/Kinub/assets/108017207/84ffaaae-865c-4547-a26e-eea0d75e4649)
even if these are accordions arent they supposed to be underlined according to figma design? 
![cap](https://github.com/loopcrack-org/Kinub/assets/108017207/39eceedd-d003-4bf9-b384-b8648f1cb99a)
it only happens on fold but the first input looks different from the others in height. 
it is just that but i think this page was harder than mine and it looks so well on different sizes, so good job @Oswaldo-Chan

2023-11-29 03:22 UTC, Tort9994 commented on src/public/sass/ITCSS/06_components/pages/product/modal-form/_modal-form.scss
> +    &--big {
```suggestion
    &--large {
```
i think using the word big is not the best option, it would be better if you use large or level 1 or something similar to other examples

2023-11-29 03:22 UTC, Tort9994 commented on src/public/sass/ITCSS/06_components/pages/product/product-info/_product-info.scss
> +      font-weight: 700;
```suggestion
      font-weight: $weight-bold;
```
remember to change numbers on font-weight for variables and try to not create colors on component files, and check it on all files of product page

2023-11-30 22:43 UTC, FernandoJoachin commented on src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
> +@use '../../../02_tools/mixins' as *;
`@use '../../../02_tools/mixins' as *;`
The same comment, is it necessary? If not, remove it.

2023-11-30 22:47 UTC, FernandoJoachin commented on src/public/sass/ITCSS/06_components/pages/product/_tags.scss
> +@use '../../../02_tools/mixins' as *;
"The same comment, remove the imports you're not using.

2023-12-12 17:09 UTC, CheloChidoone approved these changes
Great Job @Oswaldo-Chan, it looks much better now, I only found one detail to fix on the modal in galaxy fold size, just make the font a little smaller for the product name because it hides as you can see, everything else is much better. 
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/a5ccb186-6f9a-42d0-aa10-d4ee0d5f058a)

2023-12-13 17:25 UTC, Mauriciocr207 approved these changes
Nice work! I just made a suggestions
CC: @Cristianpan

2023-12-13 17:25 UTC, Mauriciocr207 commented on src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
> +    line-height: 1.2;
Here, I think you can use the mixin `font-size()`, on `src/sass/ITCSS/02_tools/_mixins.scss`

2023-12-13 17:29 UTC, Cristianpan approved these changes

2023-12-14 03:37 UTC, LUGAMAFE approved these changes
Nice @Oswaldo-Chan!

2023-12-14 03:39 UTC, LUGAMAFE commented
@FernandoJoachin @Tort9994 help me checking this PR we need to merge this tomorrow in the morning so @CarlosMay7 can continue working

2023-12-14 16:07 UTC, Tort9994 approved these changes
i see everything good, nice work @Oswaldo-Chan !

2023-12-14 16:55 UTC, FernandoJoachin approved these changes

2023-12-14 17:03 UTC, merged