KIN-306 delete product alert products page
loopcrack-org/Kinub pull request #136
Opened 2023-11-27 09:59 UTC by FernandoJoachin

## Summary

### Problem

As a company I would like that when its going to be deleted a product, an alert is displayed as a warning so that I can be sure to delete the product and avoid confusions or mistakes on missclick. 

### Solution

Create a modal window to delete the record

## Acceptance Criteria

### Requirements checklist

- [ ] It must show a modal window with a warning message saying that once the product is deleted, there is no way to recover it, and that deleting a product involves deleting its related files and product tags as well.
- [ ] It must have a cancel button
- [ ] It must have a confirm button
- [ ] It must show a response window after confirming the action, this response must indicate if the product was deleted successfully or not.

### Testing

- [ ] Delete a product

2023-11-28 16:40 UTC, CarlosJCD requested changes
For some reason the products records does not display on the products view, making us unable to test the delete product alert. Please check if it is something with your changes or we are missing something.

CC: @CarlosMay7

2023-11-30 02:26 UTC, CheloChidoone commented
> For some reason the products records does not display on the products view, making us unable to test the delete product alert. Please check if it is something with your changes or we are missing something.
> 
> CC: @CarlosMay7

This doesn't happen to me @CarlosJCD @CarlosMay7, you should try running `php spark migrate:refresh` and `php spark db:seed MainTestSeeder` again

2023-11-30 02:34 UTC, CheloChidoone approved these changes
Good Job @FernandoJoachin, just check my comment about how you could modify the modal message

2023-11-30 02:34 UTC, CheloChidoone commented on app/Views/admin/products/Products.php
> +                <?= view('templates/admin/deleteModalElement', ['idModal' => 'deleteProductsModal', 'message' => 'Eliminar el producto resultará en la eliminación permanente del elemento. Esta acción
I think the message looks better like this:

```suggestion
                <?= view('templates/admin/deleteModalElement', ['idModal' => 'deleteProductsModal', 'message' => 'Eliminar el producto resultará en la eliminación permanente del elemento. Esta acción no se puede deshacer e implica la eliminación de los archivos y los tags asociados al producto.', 'action' => '/admin/productos/borrar', 'inputName' => 'productId']); ?>
```

2023-11-30 03:23 UTC, Cristianpan approved these changes

2023-11-30 04:22 UTC, Mauriciocr207 approved these changes

2023-11-30 04:31 UTC, Oswaldo-Chan reviewed
![image](https://github.com/loopcrack-org/Kinub/assets/92545103/00f3b633-6529-4119-a665-f9947ca75bf1)

I think the text should be shorter because the box looks more longer.

2023-11-30 16:37 UTC, CarlosMay7 approved these changes

2023-11-30 16:37 UTC, CarlosJCD approved these changes
Nice, it works now. Just check @Oswaldo-Chan comments

2023-11-30 16:41 UTC, LUGAMAFE approved these changes

2023-11-30 16:44 UTC, LUGAMAFE approved these changes

2023-11-30 16:45 UTC, merged