KIN-314 refactor styles certificates page
loopcrack-org/Kinub pull request #139
Opened 2023-11-27 20:40 UTC by Tort9994

[![KIN-314](https://badgen.net/badge/JIRA/KIN-314/blue)](https://loopcrack.atlassian.net/browse/KIN-314) ![Medium](https://badgen.net/badge/PR%20Size/Medium/yellow) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

## Summary

### Problem

equipments page needed a refactor on CSS arquitecture

### Solution

This PR includes changes on CSS whit ITCSS, BEM and atomic design patterns for a better CSS arquitecture

## Acceptance Criteria

### Requirements checklist

- [x]  The equipments page must need to follow the ITCSS, BEM and atomic design patterns
### Testing

- [x] Test responsive manually

[KIN-314]: https://loopcrack.atlassian.net/browse/KIN-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-28 16:55 UTC, CarlosJCD approved these changes
Nice work, just check the comments of @CarlosMay7. Also when creating a PR don't forget to add the reviewers and if possible to attach demo videos and/or images. :)

2023-11-28 16:56 UTC, CarlosMay7 commented on src/public/sass/ITCSS/06_components/pages/certificates/certificate.scss
> +    object-fit: cover;
```suggestion
    object-fit: cover;
    transition: all 500ms ease;
```

I think you could add this property in order to have a more smooth presentation.

2023-11-28 16:58 UTC, CarlosMay7 requested changes
It looks good overall, just check the comment I left you

2023-11-29 00:13 UTC, CheloChidoone requested changes
Good Job @Tort9994, it is much better, just check the comment May left and also my comment is that almost every size looks fine but on the title `Certificados` looks like the font is too big on the smallest sizes like galaxy fold and it looks strange.

![image](https://github.com/loopcrack-org/Kinub/assets/38699927/6924c161-2d92-46af-b059-b63ccc0348b3)

2023-11-29 01:38 UTC, CheloChidoone approved these changes

2023-11-30 03:58 UTC, Cristianpan approved these changes

2023-11-30 16:56 UTC, CarlosMay7 approved these changes

2023-11-30 17:19 UTC, LUGAMAFE requested changes
Some nitpicks please review

2023-11-30 17:19 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/certificates/certificate.scss
> +      max-height: 12rem;
Again @Tort9994 don use `max-height` and `max-width` for images just use `width: 100%` for the base selector with just  `max-width` on breakpoints and combine with aspect ratio please

2023-11-30 17:19 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/certificates/certificate.scss
> +    max-width: 17rem;
```suggestion

```
Not necessary since the width should be provided by the grid parent or container

2023-11-30 17:19 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/certificates/certificate.scss
> +    max-width: 13rem;
```suggestion

```
Not necessary since the width should be provided by the grid parent or container

2023-11-30 17:19 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/certificates/certificate.scss
> +    max-width: none;
```suggestion

```
Not necessary since the width should be provided by the grid parent or container

2023-11-30 17:19 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/certificates/certificate.scss
> +  box-sizing: border-box;
```suggestion
```
Not necesary this is alredy setted on this file  `src\public\sass\ITCSS\03_generic\_box-sizing.scss`

2023-11-30 17:19 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/certificates/_certificates.scss
> +    @include grid(1, 1.5rem);
Please on galaxy fold show 2 columns
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/fc707f6f-6cc4-4dad-991b-b52262a513d1)

2023-12-03 23:30 UTC, LUGAMAFE commented on src/public/sass/ITCSS/01_settings/_global.scss
> +$base-border-medium: 0.1875rem;
@Tort9994 should be 
`$base-border-width-medium: 0.1875rem;`
not 
`$base-border-medium: 0.1875rem;`

2023-12-04 00:05 UTC, LUGAMAFE requested changes

2023-12-04 00:05 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/certificates/_certificates.scss
> +
@Tort9994  remove empty spaces please!

2023-12-04 00:05 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/certificates/_certificates.scss
> +    margin: 2rem;
I think is better to use percentages here @Tort9994 fold and phones designs look really bad.
Try to use more width.
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/5390da10-839b-49e6-a394-3fefd9c3acbd)

2023-12-04 00:34 UTC, Mauriciocr207 commented on src/public/sass/ITCSS/06_components/pages/certificates/certificate.scss
> +@use '../../../02_tools/mixins' as *;
The name of file like `certificate.scss` must be named like `_certificate.scss`.

2023-12-04 00:38 UTC, Mauriciocr207 commented on src/public/sass/ITCSS/06_components/pages/certificates/certificate.scss
> +  }
This padding values can be rewriten as the global spacing defined on `_global.scss`
```suggestion
  @include fold {
    padding: $spacing-md $spacing-sm;
  }

  @include phone {
    padding: $spacing-lg;
  }
  @include tablet {
    padding: $spacing-xl;
  }
```

2023-12-06 05:37 UTC, LUGAMAFE approved these changes

2023-12-06 05:37 UTC, LUGAMAFE commented on src/public/sass/Pages/certificates.scss
>  //TODO
Remove this TODO line

2023-12-12 01:52 UTC, merged