KIN-163 Routing Login Page
loopcrack-org/Kinub pull request #14
Opened 2023-08-26 17:56 UTC by Mauriciocr207

## Summary

### Problem

In order to get control over the access to panel section, is necessary create a login page where users need to verificate their identity in order to acces to panel section.

### Solution

Was added all necesary routes (according to project documentation), a controller and views ready to begin the front of the login section. 

## Acceptance Criteria

### Requirements checklist

- [ ] All the routes defined for the login page must work
- [ ] Controller class wich methods would be associated to a route and http method.
- [ ] The correspond views according to documentation.

### Testing

- [ ] Manual testing  entering to any route. 

## Resources
## Demo

2023-08-26 19:22 UTC, Oswaldo-Chan submitted a review, later dismissed

2023-08-26 20:08 UTC, Cristianpan requested changes
Add the post route to send the password reset instructions

2023-08-26 20:40 UTC, Cristianpan approved these changes

2023-08-27 00:52 UTC, CarlosJCD approved these changes

2023-08-27 00:53 UTC, Oswaldo-Chan approved these changes

2023-08-27 00:55 UTC, CheloChidoone approved these changes

2023-08-27 00:56 UTC, merged