KIN-219 Add delete category functionality without files management
loopcrack-org/Kinub pull request #143
Opened 2023-11-29 10:46 UTC by Cristianpan

## Summary

### Problem

The admin user needs to delete a category so that in case there is no longer needed it can discarded by the system

### Solution

Implement the delete category functionality

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] It must delete the register from the database

For the moment, the files inputs will be ignored and when storing on the database, it will be a hardcoded value.
NOTES: The files functionality will be integrated late
### Testing

Manual testing
- [ ] Select a category and delete it from the administration panel and check that the category data has been removed from the database along with its associated tags and files.

## Resources
## Demo

2023-11-30 04:45 UTC, Mauriciocr207 commented on app/Controllers/CtrlCategory.php
> +        (new CategoryModel())->deleteCategory($categoryId);
Here is not neccesary verify if the register was deleted and send a response according to that. Is not neccesary to consider where the delete return `false`?

2023-11-30 05:01 UTC, Oswaldo-Chan approved these changes
👍 approved

2023-11-30 05:22 UTC, Mauriciocr207 approved these changes

2023-11-30 17:08 UTC, CarlosMay7 reviewed
It works fine but when we checked the database the products related to the deleted category were still there when those were supposed to be deleted as well. Please check it out

2023-12-01 17:07 UTC, Cristianpan commented
> It works fine but when we checked the database the products related to the deleted category were still there when those were supposed to be deleted as well. Please check it out

That is because of how the test categories have been created, if you look at the seeders you can see that there are only 3 files created and those same files are associated to any entity that needs them, then when you delete the category, because of these associations between files, is what "fails" however in a normal flow that wouldn't happen, you can try creating a new category and you will see that everything works normally.

2023-12-12 01:50 UTC, LUGAMAFE requested changes

2023-12-12 01:50 UTC, LUGAMAFE commented on app/Models/CategoryModel.php
> +<<<<<<< HEAD
@Cristianpan beware of these errors when resolving merge conflicts
```suggestion

```

2023-12-12 01:50 UTC, LUGAMAFE commented on app/Models/CategoryModel.php
> +=======
same
```suggestion
```

2023-12-12 01:50 UTC, LUGAMAFE commented on app/Models/CategoryModel.php
> +>>>>>>> 51ecbe590e18479386d7c3b8d914ab2236ef7dad
same
```suggestion
```

2023-12-12 01:56 UTC, LUGAMAFE requested changes

2023-12-12 01:56 UTC, LUGAMAFE commented on app/Models/CategoryModel.php
> +<<<<<<< HEAD
@Cristianpan beware of these errors when resolving merge conflicts, you didn't choose which version to use, right
```suggestion
```

2023-12-12 02:58 UTC, Cristianpan commented on app/Models/CategoryModel.php
> +<<<<<<< HEAD
Is right, I didn't see that conflict,  so sorry.

2023-12-12 17:11 UTC, CheloChidoone approved these changes
Good Job @Cristianpan

2023-12-13 06:13 UTC, CarlosMay7 commented on app/Controllers/CtrlCategory.php
> +            return redirect()->to('admin/categorias')->with('response', $response);
Maybe you can move his line outside of the try catch and everything should work fine

2023-12-13 06:13 UTC, CarlosMay7 commented on app/Controllers/CtrlCategory.php
> +            return redirect()->to('admin/categorias')->with('response', $response);
Because is the same statement as before

2023-12-13 06:16 UTC, CarlosMay7 commented on app/Models/CategoryModel.php
> +            $this->db->transComplete();
Check the suggestion you did about the change from transComplete to transCommit

2023-12-13 06:17 UTC, CarlosMay7 requested changes
Hey @Cristianpan, we checked and everything looks good overall, just a few comments. 

Also we have a question, shouldn't we delete the category tags along with the category?

CC: @FernandoJoachin

2023-12-14 05:20 UTC, Cristianpan commented
> Hey @Cristianpan, we checked and everything looks good overall, just a few comments.
> 
> Also we have a question, shouldn't we delete the category tags along with the category?
> 
> CC: @FernandoJoachin

I've made the suggested changes, but about deleting category tags, it works correctly for me and I've not made it delete through the code because I'm delegating that action to the Db. I'd like that you to confirm if you are using a proper configuration for the Db (the eginee innodb). Likewise if anyone can confirm whether or not it is working correctly for them, that would be nice.

2023-12-14 16:27 UTC, FernandoJoachin approved these changes

2023-12-14 16:40 UTC, CarlosMay7 approved these changes
Nice work, thank you

2023-12-15 01:33 UTC, CarlosJCD approved these changes
Nice work!, remember to resolve comments before doing merge

2023-12-16 01:51 UTC, LUGAMAFE approved these changes

2023-12-16 02:37 UTC, merged