Edit measurement solution functionality
loopcrack-org/Kinub pull request #144
Opened 2023-12-01 14:33 UTC by CarlosJCD

## Summary

### Problem

Update / change the already registered data of a measurement solution.

### Solution

Implement the edit logic for registered measurement solutions

## Acceptance Criteria

### Requirements checklist

- [x] It must validate the inputs to not be empty

- [x] In case the inputs are correct, it must update the register of the measurement solution on the database

- [x] In case there are errors, it must return them to the view

- [x] It must return a response to the view indicating success or error on persisting the changes.

NOTES: The files functionality will be integrated on a later Issue

### Testing

- [x] On the edit measurement solution view, modify the name or  description on the form. Then click on the submit button and observe how it redirects to the measurement solutions page with a response indicating success and the new data updated on the table.

## Resources
## Demo

2023-12-01 17:07 UTC, CheloChidoone commented on app/Views/admin/typeSolutions/solutionsFormTemplate.php
> +<input type="hidden" name="msId" value="<?php old('msId') ?? $measurementSolution['msId'] ?? ''; ?>" >
This input shouldn't be necessary if all you want from it is the `msId` value because you should already be getting that from the route for the update

2023-12-01 17:08 UTC, CheloChidoone commented on app/Controllers/CtrlSolution.php
> +            $msData['msId']  = $msId;
Why are you overwriting the $msId that you receive as a parameter on this function, this shouldn't be necessary

2023-12-01 17:10 UTC, CheloChidoone requested changes
@CarlosJCD Good Job, it works well but we found some things that you added without it being necessary, check how update functions for other elements have been done for reference and check these comments.

CC: @Cristianpan

2023-12-04 00:59 UTC, Mauriciocr207 reviewed
I left you some comments
CC: @Oswaldo-Chan

2023-12-04 04:05 UTC, LUGAMAFE commented on app/Controllers/CtrlSolution.php
> +            $msData['msId']  = $msId;
```suggestion
```

there is no need for this
follow the pattern recommended by mau

`$msModel->updateData($msId, $msData);`

2023-12-12 02:19 UTC, LUGAMAFE approved these changes
Good Job @CarlosJCD

2023-12-12 03:08 UTC, Mauriciocr207 approved these changes

2023-12-12 03:08 UTC, Cristianpan approved these changes

2023-12-12 17:14 UTC, Oswaldo-Chan approved these changes

2023-12-12 17:14 UTC, CheloChidoone approved these changes
Good Job @CarlosJCD!

2023-12-12 23:24 UTC, merged