KIN-289 separate endpoints for confirm account and change password features
loopcrack-org/Kinub pull request #145
Opened 2023-12-11 09:56 UTC by FernandoJoachin

## Summary

### Problem

It is necessary to separate the confirm account functionality and reset account functionality in two new endpoints.

### Solution

Separate the confirm account functionality and reset password functionality in two different endpoints, so that each endpoint has its own routes and views 

## Acceptance Criteria

### Requirements checklist

- [ ] The confirm account view, implemented logic and it must be on its own endpoint.
- [ ] The change password view, implemented logic and it must be on its own endpoint.

### Testing

- [ ] Please go to http://kinub.cm/password_reset and try adding an account that hasn't been confirmed yet.
- [ ] Go to http://kinub.cm/password_reset and try adding a confirmed account. Then, go to Mailtrap and click on the 'reset password' button. Next, attempt to enter a token that doesn't exist in the URL or a token from someone who hasn't confirmed their account. This action should redirect you to http://kinub.cm/password_response with an error response.
- [ ] Create a new user. Then, go to Mailtrap and click on the 'set password' button. Afterward, try entering a token that doesn't exist in the URL or a token from someone who has already confirmed their account. This action should redirect you to http://kinub.cm/password_response with an error response.

2023-12-12 03:23 UTC, LUGAMAFE requested changes
@FernandoJoachin please talk with @CarlosJCD you have several code logic problems

2023-12-12 03:23 UTC, LUGAMAFE commented on app/Controllers/CtrlLogin.php
> +            $userModel->updatePassword($user['userId'], $data['password'], 1);
And now you need to remove the used token! you are not deleting used tokens

2023-12-12 03:23 UTC, LUGAMAFE commented on app/Controllers/CtrlLogin.php
> +
Same here you need to  remove the used token!

2023-12-12 03:30 UTC, Cristianpan commented on app/Utils/TokenUtils.php
> +        return $userTokenModel->join('users', 'users.userId = user_tokens.userId')->where('userToken', $token)->first();
I think that those methods should be in the UserTokenModel and not such as an util

2023-12-12 04:05 UTC, Mauriciocr207 requested changes

2023-12-12 04:05 UTC, Mauriciocr207 commented on app/Validation/ChangePasswordValidation.php
> +            }
I think you can separate this function on two, to be more descriptive for example:

```php
public function hasAccessToSetPassword($isConfirmed)
    {
        if ($isConfirmed !== USER_IS_NOT_CONFIRMED) {
            throw new Exception('Parece que no cuenta con el permiso para establecer su contraseña');
        }

        return true;
    }

public function hasAccessToResetPassword()
    {
        if ($isConfirmed !== USER_IS_CONFIRMED) {
            throw new Exception('Parece que no cuenta con el permiso para restablecer su contraseña');
        }

        return true;
    }
```

2023-12-12 04:05 UTC, Mauriciocr207 commented on app/Controllers/CtrlLogin.php
> +            $changePasswordValidation->accessValidation($user['confirmed'], '1');
And when you separate this functionality you can use the constants `USER_IS_NOT_CONFIRMED` like:
```php
$changePasswordValidation->hasAccessToSetPassword($user['confirmed'], USER_IS_NOT_CONFIRMED);
```

2023-12-12 04:05 UTC, Mauriciocr207 commented on app/Controllers/CtrlLogin.php
> +            $changePasswordValidation->accessValidation($user['confirmed'], '0');
And here:
```php
$changePasswordValidation->hasAccessToResetPassword($user['confirmed'], USER_IS_CONFIRMED);
```

2023-12-12 04:06 UTC, Cristianpan requested changes
Please considere the changes.

CC: @Mauriciocr207

2023-12-12 17:25 UTC, Oswaldo-Chan approved these changes

2023-12-12 17:36 UTC, Oswaldo-Chan approved these changes

2023-12-12 17:37 UTC, CheloChidoone approved these changes
Good Job @FernandoJoachin, thanks for adding the validations and changes requested, on our tests expired token validation and the tokens being deleted after being used work correctly, well done.

CC: @Oswaldo-Chan

2023-12-13 05:51 UTC, Mauriciocr207 approved these changes
Here there is some suggestions

2023-12-13 05:51 UTC, Mauriciocr207 commented on app/Validation/ChangePasswordValidation.php
> +            throw new Exception('Parece que no cuenta con el permiso para restablecer su contraseña');
I have a doubt, in the `hasAccessToSetPassword()`, you need that user is confirmed right? then you can make a positive sentence on if statement, and in the `hasAccessToResetPassword()` function occurs similar, then:
```suggestion
    public function hasAccessToSetPassword()
    {
        if ($this->userWithToken['confirmed'] === self::USER_IS_CONFIRMED) {
            throw new Exception('Parece que no cuenta con el permiso para establecer su contraseña');
        }

        return true;
    }

    public function hasAccessToResetPassword()
    {
        if ($this->userWithToken['confirmed'] === self::USER_IS_NOT_CONFIRMED) {
            throw new Exception('Parece que no cuenta con el permiso para restablecer su contraseña');
```

2023-12-13 05:51 UTC, Mauriciocr207 commented on app/Controllers/CtrlEmail.php
> +                throw new InvalidInputException($validateEmail->getErrors());
Here remember put the `$validateEmail` and the `$data` into the try-catch, you can not see it like a change, but if you check your code, those variables are out the try-catch

2023-12-13 06:42 UTC, CarlosMay7 commented on app/Models/UserModel.php
> +            $this->db->transComplete();
Here check the comments @Cristianpan made about using transCommit instead of transComplete

2023-12-13 06:55 UTC, CarlosMay7 approved these changes
Nice work, just check the comment I left you 

And also check the little conflict about the token generator with @Cristianpan

2023-12-13 16:54 UTC, Cristianpan commented on app/Controllers/CtrlLogin.php
> +
This is fine, but we have a file with all the constants we need for this project so I think it would be a good idea to add them to that file, especially since I see it used here and also in a validator. The file path is `/app/Config/Constants.php`.

2023-12-13 16:58 UTC, Cristianpan commented on app/Models/UserModel.php
> +            $this->db->transStart();
```suggestion
            $this->db->transException(true)->transStart();
```
Make this change please for the enable that the db throws the exceptions

2023-12-15 01:41 UTC, CarlosJCD requested changes
Nice work!, just check out the comments i left you.

2023-12-15 01:41 UTC, CarlosJCD commented on app/Config/Constants.php
> +define('USER_IS_CONFIRMED', '1');
I am not really sure if it is ok to define as a global constant a value that is currently only used in the ctrlLogin class. I believe that it would be better to manage this kind of constants as private attributes of the class so that it can have the right scope. Maybe its just my impression, what do you think about this? @Cristianpan , @Mauriciocr207 , @CheloChidoone , @LUGAMAFE

2023-12-16 01:53 UTC, LUGAMAFE commented on app/Config/Constants.php
> +define('USER_IS_CONFIRMED', '1');
yeah @CarlosJCD that is correct if is not being used i other parts should be a class constant

2023-12-16 21:32 UTC, Cristianpan commented on app/Config/Constants.php
> +define('USER_IS_CONFIRMED', '1');
Hmm ok but I had told Joachin to put it there since I saw that he was using it in a controller and a validator, also thinking that those constants could be reused. So I'd think that putting them in that file would be fine but I don't know what others think.

2023-12-17 05:16 UTC, FernandoJoachin commented on app/Config/Constants.php
> +define('USER_IS_CONFIRMED', '1');
So, how do I do it?"

> I am not really sure if it is ok to define as a global constant a value that is currently only used in the ctrlLogin class. I believe that it would be better to manage this kind of constants as private attributes of the class so that it can have the right scope. Maybe its just my impression, what do you think about this? @Cristianpan , @Mauriciocr207 , @CheloChidoone , @LUGAMAFE

So, how do I do it?"

2023-12-18 16:25 UTC, CarlosJCD commented on app/Views/login/PasswordResponse.php
> +    <?= $this->include('partials/vendor-scripts') ?>
@FernandoJoachin please check this out so that I can accept your PR

2023-12-18 16:26 UTC, CarlosJCD commented on app/Config/Constants.php
> +define('USER_IS_CONFIRMED', '1');
If you are using it in more than one class then leave it like that!, my observation was because I thinked that these constants where used only on the controller.

2023-12-19 03:19 UTC, LUGAMAFE approved these changes

2023-12-19 18:44 UTC, CarlosJCD approved these changes

2023-12-19 18:47 UTC, merged