KIN-290 Add resend email to confirm account functionality
loopcrack-org/Kinub pull request #147
Opened 2023-12-11 22:53 UTC by Cristianpan

## Summary

### Problem
It is needed to generate a feature on the admin panel that allows the admin to send again the confirm account email for unconfirmed accounts.

### Solution

Implement functionality that allows the admin user to resend an email to confirm the account.

## Acceptance Criteria

### Requirements checklist

- [ ] There must be a button for the users page and edit users views that must allow to resend the confirmation email to the unconfirmed account.
- [ ] It must be displayed a modal alert indicating success on resending the new confirm account or if there was an error in the process.
- [ ] When is triggered this button, the following must happen:
- [ ] The last created token for the account must be deleted.
- [ ] A new token wit a new expiration date (current date + 24 hours) must be generated and registered on the database token table.
- [ ] The confirm account must be sent again with this new token.

### Testing

Modify the "confirmed" attribute of a registered user and do the following and login to the admin panel with the superadmin account.
- [ ] Try to resend the account confirmation email from the administration panel and verify in mailtrap that you have received a new account confirmation email. Also check that the token has been updated in the database.
- [ ] Try to resend the account confirmation email from the user edit view and check the same as in the previous point.

## Resources

## Demo
![image](https://github.com/loopcrack-org/Kinub/assets/91033040/bc39ee3a-dd50-4093-bf4f-ade9962e1afe)
![image](https://github.com/loopcrack-org/Kinub/assets/91033040/e9efb631-01ed-4a4b-a8cd-c26cfa1ae5f3)

2023-12-12 17:48 UTC, CheloChidoone requested changes
Good job Cristian, it works well but when testing it from the button you added on the edit user page the confirmation modal does not show up, it just looks like it just recharged the page and nothing else appears even though it did work, just check that bug

CC: @Oswaldo-Chan

2023-12-13 06:38 UTC, FernandoJoachin commented on app/Controllers/CtrlUser.php
> +            return redirect()->back()->with('response', $response);
On lines 161 and 169, you have the same code. Take it out of the try-catch block to avoid code duplication. It should work
CC: @CarlosJCD

2023-12-13 06:40 UTC, FernandoJoachin commented on app/Models/UserTokenModel.php
> +            $this->db->transComplete();
The same comment. Use 'transCommit' instead of 'TransComplete'

2023-12-13 06:40 UTC, FernandoJoachin reviewed
Why did you remove TokenGenerator?

2023-12-14 05:26 UTC, Cristianpan commented
> Why did you remove TokenGenerator?

Because the utility could be replaced by the model events provided by CI in the models since that action is always performed before generating the token, then I considered that it would be better to delegate that action to the model event instead of creating a utility. 
You can read more about this in the CI models [here](https://www.codeigniter.com/user_guide/models/model.html#model-events)

2023-12-14 05:41 UTC, Cristianpan commented
> Why did you remove TokenGenerator?

Because replace the utility by the method in the model, where the token to be inserted is created directly there. I considered that it was better to have it as a utility.

2023-12-14 16:58 UTC, Oswaldo-Chan approved these changes

2023-12-15 01:53 UTC, CarlosJCD approved these changes
Excellent work!

2023-12-15 07:27 UTC, merged