functionality to create certificates with files
loopcrack-org/Kinub pull request #151
Opened 2023-12-14 12:00 UTC by FernandoJoachin

## Summary

### Problem

The logic of creating certificate was integrated without the file functionality.

### Solution

Integrate files functionality for the certificates files

## Acceptance Criteria

### Requirements checklist

- [ ] It must validate that on the certificate file input it is only uploaded pdf files
- [ ] It must validate that on the certificate preview input it is only uploaded png/jpg files
- [ ] If it passes all the validations, the files must be stored on the server and the file routes as must be stored in the database

### Testing

- [ ] Go to /admin/certificados/crear and create a certificate
- [ ] In the Preview Image field, upload a file that is not an image or that exceeds the specified weight or size
- [ ] In the Certificate File field, upload a file that is not a pdf or that exceeds the specified weight

2023-12-14 17:29 UTC, CheloChidoone requested changes
Good job @FernandoJoachin it works well but I found something that we should change that affects this PR, when we use an image that exceeds the dimensions you specified we get this message: 
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/c1e5f17a-c366-4a40-a6eb-8594ad9e1cfb)

I think this message makes it seem like the image should be exactly of those dimensions when in reality those are the max dimensions it could have so the message should say something like `no debe exceder estas dimensiones`.

@Cristianpan @Mauriciocr207 I don't know if these change should be made in this PR but it affects it and any other place where the image dimensions will be checked, please let us know your toughts about these change.

2023-12-15 07:29 UTC, Mauriciocr207 commented
> [Dec 14, 2023](#event-11247227267)
> [<img alt="CheloChidoone" width="40" height="40" src="https://avatars.githubusercontent.com/u/38699927?s=60&amp;v=4">](/CheloChidoone)
> ** [CheloChidoone](/CheloChidoone) ** requested changes [ Dec 14, 2023 ](#pullrequestreview-1782324773)
> [ View reviewed changes ](/loopcrack-org/Kinub/pull/151/files/7fd47978e6c1d7a09fc2c5a94b2a38b811a31918)

About this, I think that could be changed here due that is a little change

2023-12-16 02:41 UTC, LUGAMAFE requested changes
Nits @FernandoJoachin

2023-12-16 02:41 UTC, LUGAMAFE commented on app/Controllers/CtrlCertificate.php
> +        $fileConfigBuilder->builder('certificatePreviewId')->minFiles(1)->maxFiles(1)->maxSize(2, 'MB')->isImage()->maxDims(1000, 1500)->build();
Why `certificatePreviewId` should be only `certificatePreview`?
And i think the max dims are to much, look a real example
```suggestion
        $fileConfigBuilder->builder('certificatePreview')->minFiles(1)->maxFiles(1)->maxSize(2, 'MB')->isImage()->maxDims(700, 700)->build();
```

![image](https://github.com/loopcrack-org/Kinub/assets/24960025/9862444b-c252-4398-acc4-43f0fce34100)

2023-12-16 02:41 UTC, LUGAMAFE commented on app/Controllers/CtrlCertificate.php
> +        $fileConfigBuilder->builder('certificatefileId')->minFiles(1)->maxFiles(1)->maxSize(30, 'MB')->isPDF()->build();
Same why `certificatefileId` and not  just `certificatefile`

2023-12-16 02:41 UTC, LUGAMAFE commented on app/Views/admin/certificates/CertificateCreate.php
> +                <form id="form" autocomplete="off" class="needs-validation" novalidate method="POST">
Why you added novalidate?
```suggestion
                <form id="form" autocomplete="off" class="needs-validation" method="POST">
```

2023-12-16 02:41 UTC, LUGAMAFE commented on app/Views/admin/certificates/certificatesFormTemplate.php
> +                <?= view('admin/components/inputFilePond', ['config' => $filepondConfig['certificatePreviewId']]) ?>
```suggestion
                <?= view('admin/components/inputFilePond', ['config' => $filepondConfig['certificatePreview']]) ?>
```

2023-12-16 02:41 UTC, LUGAMAFE commented on app/Views/admin/certificates/certificatesFormTemplate.php
> +                 <?= view('admin/components/inputFilePond', ['config' => $filepondConfig['certificatefileId']]) ?>
```suggestion
                 <?= view('admin/components/inputFilePond', ['config' => $filepondConfig['certificatefile']]) ?>
```

2023-12-17 03:41 UTC, CarlosMay7 reviewed
I think it looks good but I have a little problem, I don't know if it's just me but the first time I try to create a certificate without a name it redirects me to a 404 page

[Demo](https://drive.google.com/file/d/1e49iYOOfLBROKowiak6cnv4rDU9CvCGx/view?usp=sharing)

2023-12-17 04:38 UTC, FernandoJoachin commented
> I think it looks good but I have a little problem, I don't know if it's just me but the first time I try to create a certificate without a name it redirects me to a 404 page
> 
> [Demo](https://drive.google.com/file/d/1e49iYOOfLBROKowiak6cnv4rDU9CvCGx/view?usp=sharing)

Has this happened to anyone else? Because I've checked and it works for me.

2023-12-18 02:02 UTC, Cristianpan approved these changes
Please considere that comment that I've left you and thanks to make the other changes.

2023-12-18 02:03 UTC, Cristianpan commented on app/Views/admin/certificates/certificatesFormTemplate.php
> +                    <input type="text"  class="form-control <?= isset($errors['certificatefileName']) ? 'is-invalid' : '' ?>" name="certificatefileName" id="certificatefileName" value="<?= old('certi
Please add required attribute in this input

2023-12-18 05:21 UTC, Mauriciocr207 commented
> I think it looks good but I have a little problem, I don't know if it's just me but the first time I try to create a certificate without a name it redirects me to a 404 page
> 
> [Demo](https://drive.google.com/file/d/1e49iYOOfLBROKowiak6cnv4rDU9CvCGx/view?usp=sharing)

I don´t know yet why this happened you, but it seems like the method patch with we load files fails. This still happen to you?

2023-12-18 05:29 UTC, Mauriciocr207 approved these changes
Good job, @FernandoJoachin!. Same comments as @Cristianpan . And if you made the previous corrections, please request changes again.

2023-12-19 03:30 UTC, LUGAMAFE commented
> I think it looks good but I have a little problem, I don't know if it's just me but the first time I try to create a certificate without a name it redirects me to a 404 page
> 
> [Demo](https://drive.google.com/file/d/1e49iYOOfLBROKowiak6cnv4rDU9CvCGx/view?usp=sharing)

Hey @CarlosMay7 can you check that your CI_ENVIRONMENT is in production mode.

![image](https://github.com/loopcrack-org/Kinub/assets/24960025/df2b6ab4-2e83-4351-b83f-1b87b40d8b71)

2023-12-19 03:38 UTC, LUGAMAFE requested changes
ignore this

2023-12-19 03:39 UTC, LUGAMAFE approved these changes
Nice @FernandoJoachin. Same comments as @Cristianpan please before merge

2023-12-19 23:34 UTC, CheloChidoone approved these changes

2023-12-21 02:16 UTC, CarlosMay7 approved these changes

2023-12-22 03:29 UTC, merged