KIN-93 API Searchbar - Product Filters API - BackEnd
loopcrack-org/Kinub pull request #152
Opened 2023-12-15 07:14 UTC by Mauriciocr207

## Summary

### Problem

It is needed to handle the frontend requests so that the filtered products can be retrieved from the server. Also it includes to modify models in order to filter products not only on api even on CtrlPubliPages

### Solution

Implement a product filter API and models needed by CtrlPubliPages.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [x] CategoryModel, CategoryTagModel and ProductTagModel have their methods to get tags, but not implemented yet on CtrlPublicPages
- [x] Provide an api filter to search by name between filtered products
- [x] Provide the necessary methods by models to filter and get products to use it on CtrlPubliPages
- [x] Provide a test filter on api to prove the CtrlPubliPages filter (not impmlemented yet on controller)
- [x] The filters must validate query params received from the client request
- [x] It must implement the endpoints for the product filters functionality
- [x] It must retrieve the products with the requested filters

### Testing or automated) executed to verify your changes

- [x] In order to test this pr remember do `php spark migrate:refresh` and `php spark db:seed MainTestSeeder` to add more registers to test correctly this pr.
- [x] Second, following the documentation on api search filter, you can access to the following [postman workspace](https://app.getpostman.com/join-team?invite_code=25f15db653260e6122b9b1760cf49ff5&target_code=426f7132b1ccfb8f9601a82bbda30cea) to get the test api.
- [x] And then, you can access via visual studio code to the extension of Postman to prove the api.

## Resources

- [Postman Extension](https://marketplace.visualstudio.com/items?itemName=Postman.postman-for-vscode)
- [documentation](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/69107714/Product+Search+Filter+Api)

## Demo

2023-12-17 00:35 UTC, CheloChidoone requested changes
Great Job @Mauriciocr207, it works awesome but please check these comments I left you and also update the api documentation because the names of the query params are different for a lot of them to what you actually did in the code so that gave us a lot of trouble testing until we found out the names of the params on the documentation are wrong.

CC: @Oswaldo-Chan

2023-12-17 00:35 UTC, CheloChidoone commented on app/Controllers/CtrlApiPublic.php
> +        $categoryIds      = $this->request->getGet('category');
Same, We should be consistent in the naming of the query params to make it easier, make it either `category` or `categories` for all endpoints

2023-12-17 00:35 UTC, CheloChidoone commented on app/Controllers/CtrlApiPublic.php
> +        $categoryId    = (string) $this->request->getGet('category');
Same, We should be consistent in the naming of the query params to make it easier, make it either `category` or `categories` for all endpoints

2023-12-17 00:35 UTC, CheloChidoone commented on app/Controllers/CtrlApiPublic.php
> +            $categories   = $request->getGet('categories');
We should be consistent in the naming of the query params to make it easier, make it either `category` or `categories` for all endpoints

2023-12-17 22:56 UTC, Mauriciocr207 commented on app/Controllers/CtrlApiPublic.php
> +        $categoryId    = (string) $this->request->getGet('category');
Here I name this with the query param `"category"` because we need only one category for get the image, but in the filter and search methods we need one o more categories

2023-12-18 02:09 UTC, CarlosMay7 reviewed
Looks good overall but I have an issue related to the sorting because it doesn't work in either way, in addition to another problem, what is the difference between order and direction?

2023-12-18 18:03 UTC, Mauriciocr207 commented
> Looks good overall but I have an issue related to the sorting because it doesn't work in either way, in addition to another problem, what is the difference between order and direction?

The order refers to the type of ordering by name or id. And direction can be ascendet or descendent.
Can you give more information about the problem?

2024-01-06 16:17 UTC, Cristianpan requested changes

2024-01-06 16:17 UTC, Cristianpan commented on app/Models/ProductModel.php
> +        $builder->where($whereQuery);
Instead of creating `where in` statements manually, you can make use of the whereIn method provided by the CI query builder, and the same case with the like statement.

```suggestion
             // added categories filter
        if (! empty($categories)) {
            $builder->whereIn('categories.categorySlug', $categories);
        }
        // added category_tags filter
        if (! empty($categoryTags)) {
            $builder->whereIn('category_tags.categoryTagSlug', $categoryTags);
        }
        // added products_tags filter
        if (! empty($productTags)) {
            $builder->whereIn('product_tags.ptSlug', $productTags);
        }
        // added search filter
        if (! empty($search)) {
            $builder->like('products.productName', $search)->orLike('products.productModel', $search);
        }

        $builder->groupBy('productId');

        return $this;
```

2024-01-06 16:17 UTC, Cristianpan commented on app/Models/ProductModel.php
> +    }
The name of this function could be confusing, I think a better name would be `orderByProductName`. And for the parameter, maybe a better descriptive name would be `orderType`.

2024-01-06 16:21 UTC, Cristianpan commented
Likewise, check that the documentation corresponds to the current implementation, as well as what you've provided to test the api.

2024-01-07 06:04 UTC, LUGAMAFE requested changes
Nice @Mauriciocr207 couple nitpicks.
And please can you update de documentation and insomnia API 🙏

2024-01-07 06:04 UTC, LUGAMAFE commented on app/Models/ProductModel.php
> +    public function filterProducts(array $categories, array $categoryTags, array $productTags, string $search = '')
```php
class ProductModel extends Model
{
    // ... [resto del código] ...

    public function filterProducts(array $categories, array $categoryTags, array $productTags, string $search = '')
    {
        $builder = $this->buildBaseQuery();

        $this->applyFilter($builder, 'categories.categorySlug', $categories);
        $this->applyFilter($builder, 'category_tags.categoryTagSlug', $categoryTags);
        $this->applyFilter($builder, 'product_tags.ptSlug', $productTags);
        $this->filterBySearch($builder, $search);

        $builder->groupBy('productId');

        return $this;
    }

    // Resto de métodos...

    private function applyFilter($builder, string $fieldName, array $values)
    {
        if (!empty($values)) {
            $builder->whereIn($fieldName, $values);
        }
    }

    private function filterBySearch($builder, string $search)
    {
        if (!empty($search)) {
            $builder->groupStart()
                    ->like('products.productName', $search)
                    ->orLike('products.productModel', $search)
                    ->groupEnd();
        }
    }

    // ... [resto del código] ...
}```

2024-01-09 17:21 UTC, Cristianpan commented
> All good @Mauriciocr207 just please check this small bug, and please update the insomnia contract with only the required query params. CC @Oswaldo-Chan ![image](https://private-user-images.githubusercontent.com/24960025/295280462-a5a0dcb3-9163-47be-a038-78ca18dfee63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjA2NTUsIm5iZiI6MTcwNDgyMDM1NSwicGF0aCI6Ii8yNDk2MDAyNS8yOTUyODA0NjItYTVhMGRjYjMtOTE2My00N2JlLWEwMzgtNzhjYTE4ZGZlZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE3MTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MDY1NzMzZDgyOTBjM2FlNjdkNDIzZDNjN2YxZWY1Mjg0YzUyZmM3Njc1NDg0YWMyYTAxZmIyM2MwNjFhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFdRMdVdzShf24ylg91lkHfblbv8T-C7Bgdn179zoUI)
> 
>  2024-01-09.10-51-45.mp4

About the bug, I think it doesn't return the name of some product because the new category tag you created hasn't been associated to some product. I've tried the same thing but associating it and it does return some results. 

![image](https://github.com/loopcrack-org/Kinub/assets/91033040/736b2476-8397-48c3-aece-8acbdce54c37)

And about Insomnia, it's "complicated" to update so I left you a video demo about how to update the API documentation in Insomnia.


https://github.com/loopcrack-org/Kinub/assets/91033040/43b1b060-973e-4789-a209-2f97aa6912dd

2024-01-09 17:44 UTC, LUGAMAFE approved these changes
Uff thanks for the info @Cristianpan yeap that worked for me! good job @Mauriciocr207 :)

2024-01-09 17:45 UTC, Mauriciocr207 commented
> All good @Mauriciocr207 just please check this small bug, and please update the insomnia contract with only the required query params. CC @Oswaldo-Chan ![image](https://private-user-images.githubusercontent.com/24960025/295280462-a5a0dcb3-9163-47be-a038-78ca18dfee63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjIxOTcsIm5iZiI6MTcwNDgyMTg5NywicGF0aCI6Ii8yNDk2MDAyNS8yOTUyODA0NjItYTVhMGRjYjMtOTE2My00N2JlLWEwMzgtNzhjYTE4ZGZlZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE3MzgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MjBkNTA3NDA0YzkxYWJlOTk0OGFiNTY3YjY2OTk2YmU4NGYwZWYyYjlmNDM1ZDNhM2YxYWQxNmM5MTNjNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r-3ty9L86Fyx-ty4UNnAZi_P9vZl_GLokPE2UpJbSpE)
> 
>  2024-01-09.10-51-45.mp4

I updated the pr description now, but yes. As Cristian mentioned, it is necessary to make pull on insomnia api
About the bug, I have the same question, is there any product with that category?

2024-01-09 17:50 UTC, Oswaldo-Chan approved these changes

2024-01-10 16:29 UTC, CheloChidoone approved these changes

2024-01-11 05:53 UTC, Cristianpan approved these changes

2024-01-11 06:35 UTC, Cristianpan approved these changes

2024-01-11 06:49 UTC, CarlosMay7 approved these changes

2024-01-11 06:50 UTC, merged