Improve caroussel and product details styles
loopcrack-org/Kinub pull request #153
Opened 2023-12-15 07:37 UTC by CarlosMay7

## Summary

### Problem

The carousel and details section on the product page needed some improvements related to the styling  

### Solution

Improving sizes and functionalities at the mentioned sections 

## Acceptance Criteria

### Requirements checklist

- [ ] The main image at the carousel must have a zoomed version on the side
- [ ] The carousel, data and heading sizes must be smaller than the current design
- [ ] It must fit on every display from a Galaxy fold to a 4k screen

### Testing

- [ ] Manually checked all the functionalities like zooming, dragging changing from one image to another and also videos

## Resources

## Demo

[Demo Improves](https://drive.google.com/file/d/1WKfa8qDb-IhlB4kh36VhIA-phVxHg-BB/view?usp=sharing)

2023-12-21 17:07 UTC, CheloChidoone reviewed
Good job @CarlosMay7, I think it looks a lot better, My only question about the new zoom that you added next to the carrousel, it looks fine but maybe as a possibility because the zoom doesn't cover up all of the details it could look better if you make the background a little faded when the zoom is active like how the background looks when we open the product form, let me know your toughts

2023-12-21 18:39 UTC, FernandoJoachin commented on src/public/sass/ITCSS/06_components/pages/product/carousel/_drift-zoom-pane.scss
> +@use '../../../../02_tools/breakpoints' as *;
Is it necessary to make these imports? Otherwise remove them
@CarlosJCD

2023-12-21 18:51 UTC, CarlosJCD reviewed
Nice work! @CarlosMay7 however we have some observations/doubts with the caroussel design:

- We believe that it could be great if it were a kind of border or frame around the cursor to indicate the image zone where its applied the zoom.
- We also detected that the zoom of the carousel is distorted and also some times even when the cursor is not on the image the zoom displays a zone of the image. We know that this maybe is caused because how the zoom plugin works, however we think that it could be great if you could restrict the zoom zone to the actual image instead of the plugin container.
- Also, it could be great if there where a kind of border around the thumbnail of the respective image that is displayed, this with the purpose of indicating the user more clarity in which image is selected.
- Finally, we saw that there is a play button above the thumbnails of the videos in the mobile view of the caroussel. However, we think that it could be great if this play button or other indicator is displayed for videos thumbnails, this with the purpose of making a distinction between videos and images on the caroussel.

Please consider our comments, and if in some of the observations we have already decided a way to do it or if some specifics details where requested like that please let us know so we can approve your pr.

CC: @FernandoJoachin

2023-12-21 18:51 UTC, CarlosJCD commented on src/public/sass/ITCSS/06_components/pages/product/carousel/_glide.scss
> +    // fill: color.adjust($color-white, $lightness: -15%);
is it necessary to keep this comment?

2023-12-21 18:51 UTC, CarlosJCD commented on src/public/sass/ITCSS/06_components/pages/product/carousel/_glide.scss
> +    // text-shadow: 0 0.25em 0.5em rgba($color-black, 0.1);
is it necessary to keep this comment?

2023-12-28 05:33 UTC, FernandoJoachin requested changes
We found an interaction in the carousel that creates a bad user experience. When there is a lot of information, if you zoom in on the image and then scroll down, the zoomed-in screen doesn’t follow but remains at the top. We've provided a video showing what happens.
CC: @Cristianpan

2023-12-28 05:46 UTC, FernandoJoachin reviewed
We have the following doubts: Is the carousel no longer infinite? Similarly, should the dots represent each image, or is that not necessary?
CC: @Cristianpan

2023-12-28 06:18 UTC, Cristianpan commented
> We found an interaction in the carousel that creates a bad user experience. When there is a lot of information, if you zoom in on the image and then scroll down, the zoomed-in screen doesn’t follow but remains at the top. We've provided a video showing what happens. CC: @Cristianpan

Here is the [video demo](https://youtu.be/gZhQayyltQY) of what joachín mentions.

2023-12-29 01:10 UTC, CarlosMay7 commented
> We have the following doubts: Is the carousel no longer infinite? Similarly, should the dots represent each image, or is that not necessary? CC: @Cristianpan

You are right, the carousel is no longer a loop and the desktop dots now represent the content regarding the division made between the number of images and the total number of elements displayed

2023-12-29 01:39 UTC, Mauriciocr207 approved these changes

2023-12-29 04:39 UTC, CarlosJCD approved these changes

2023-12-29 04:54 UTC, Cristianpan approved these changes
Nice job! Thanks for making the changes

2023-12-29 08:56 UTC, FernandoJoachin requested changes
I found the following interaction, it shouldn't happen, right? I mean, when I click on the 'x,' it should keep me on the same image instead of moving to the next one, correct?  [video demo](https://youtu.be/RRU_QZPaexY)

2023-12-29 16:41 UTC, CheloChidoone approved these changes
Good Job @CarlosMay7, we didn't get the same bug in the slider that Joachin mentioned but you should check it anyway just in case.

@LUGAMAFE I have a question, what did we decide to do for the preview images on the slider when it is a video, because now I think it is just the main image right?, is that how it will stay?

CC: @CarlosJCD

2023-12-29 17:37 UTC, LUGAMAFE commented
@CheloChidoone  Yes, I could not reproduce the error mentioned by @FernandoJoachin  either. 
About the preview image for the videos, we need to find a standard image for all the videos on the site. I'm thinking of a simple black image with a play icon.

2023-12-29 17:38 UTC, LUGAMAFE commented
@FernandoJoachin  could you please confirm the bug you present again, neither me nor marcelo could reproduce the bug you mention.

2023-12-29 21:24 UTC, CarlosMay7 commented
> Good Job @CarlosMay7, we didn't get the same bug in the slider that Joachin mentioned but you should check it anyway just in case.
> 
> @LUGAMAFE I have a question, what did we decide to do for the preview images on the slider when it is a video, because now I think it is just the main image right?, is that how it will stay?
> 
> CC: @CarlosJCD

I couldn't reproduce the bug that Joachin said either.

2023-12-29 22:49 UTC, FernandoJoachin approved these changes

2023-12-30 04:10 UTC, merged