KIN-390 Add the functionality to send product email and update the email table in the db
loopcrack-org/Kinub pull request #154
Opened 2023-12-15 08:11 UTC by Cristianpan

## Summary

### Problem

The modal form of the product page must be stored when submitted by the user, as well as it is needed to store the dates of the forms submitted by the users.

### Solution

Implement the logic to send and store the product email and update the database to add the field to store the sending dates of the mailing forms. 

## Acceptance Criteria

### Requirements checklist

- [ ] The product form must be stored as an email and sent.
- [ ] If the product e-mail form is submitted, a success message should be displayed, otherwise, an error message should be displayed.
- [ ] If the data is incomplete, it must display the errors on the form. 
- [ ] The emails table of the database must have a date column for date storage.
- [ ] The functionality for the technical support and contact form of the public view must have integrated the storage of the email date

### Testing
Note: Before testing this feature, is necessary that you make in the console `php spark migrate:refresh` and `php park db:seed MainTestSeeder` so you update your db.

- [ ] Go to the product page and send the product form with empty data and you should see a modal with a error message. 
- [ ] Go to the product page and send the  product form with all data and you sould see a modal with a success message. 
- [ ] Verify that your db have the field for the date. 
- [ ] Check that after sending the email, the date of sending is recorded in the database.

## Resources
## Demo

2023-12-17 04:03 UTC, CarlosMay7 reviewed
It works fine overall but I have a question. the date must be the same as the time it was sent, right? Because it didn't work for me

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/6e302faf-27ee-43b9-a754-8dd123b124b7)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/4b25494f-4b6a-40c1-9655-eb4c88716003)

2023-12-17 04:07 UTC, CarlosMay7 commented
Also, change the pull request name to KIN-340...

2023-12-18 01:11 UTC, Cristianpan commented
> It works fine overall but I have a question. the date must be the same as the time it was sent, right? Because it didn't work for me
> 
> ![image](https://private-user-images.githubusercontent.com/97546829/291026982-6e302faf-27ee-43b9-a754-8dd123b124b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjIxMDEsIm5iZiI6MTcwMjg2MTgwMSwicGF0aCI6Ii85NzU0NjgyOS8yOTEwMjY5ODItNmUzMDJmYWYtMjdlZS00M2I5LWE3NTQtOGRkMTIzYjEyNGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxMTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2Q2ZDc4NTcwZDc2Y2VkOGJiZThjYmZlOTE5YWEyN2Q0MGY5OGZhZmMyNGQ2ZDNmMmMxNWMxZDkxMjI2OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vi6erAPjiP-mTmQS3QQBmwVnWK0hPV_lHKDn07XEFaA) ![image](https://private-user-images.githubusercontent.com/97546829/291026985-4b25494f-4b6a-40c1-9655-eb4c88716003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjIxMDEsIm5iZiI6MTcwMjg2MTgwMSwicGF0aCI6Ii85NzU0NjgyOS8yOTEwMjY5ODUtNGIyNTQ5NGYtNGI2YS00MGMxLTk2NTUtZWI0Yzg4NzE2MDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxMTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNDhmN2VhOTExMmZmM2IwY2I0MDM3MzQzNzQ1MTZjNjZkOTAwZWUwOWVhYTYzMmI2ZmYxZTFiMjdmOTZjNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JC-FkKttuJ-Fv22izOHw0plBZayOq4oBJ1ViFRi5O8g)

I had not considered it but have already made the change.

2023-12-18 02:22 UTC, CarlosMay7 approved these changes
Nice work! Thank you

2023-12-18 03:45 UTC, FernandoJoachin approved these changes

2023-12-18 18:01 UTC, CarlosJCD approved these changes
Nice work, just check out the comment i left you

2023-12-20 00:59 UTC, Mauriciocr207 approved these changes

2023-12-20 02:07 UTC, CheloChidoone requested changes
I think there are many things to fix @Cristianpan

1. I think it should validate the form before sending it, not show the error message and then we have to reopen it to see the errors we had made when filling it
2. When I left the form empty and the error messages appears on the form it makes the modal bigger than my screen and the bottom part doesn't show and I can't scroll on it either 
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/18ec772c-1e8c-4ec3-afa4-336838794b16)
Also check my other comments about the response messages.

2023-12-20 02:07 UTC, CheloChidoone commented on app/Controllers/CtrlEmail.php
> +                'title'   => 'Ops! No se ha realizado el envio del email',
In this message, it should be `Oops` not `Ops`

2023-12-20 02:07 UTC, CheloChidoone commented on app/Controllers/CtrlEmail.php
> +                'message' => 'Se ha enviado correctamente',
This message is too generic, take for example the one Luis added for the `Soporte Tecnico` functionality and write a similar message here

2023-12-20 02:07 UTC, CheloChidoone commented on app/Controllers/CtrlEmail.php
> +                'message' => 'Se ha enviado correctamente',
Why did you change the messages for `soporte tecnico`?, you should return them to how they were

2023-12-20 02:07 UTC, CheloChidoone commented on app/Controllers/CtrlEmail.php
> +                'message' => 'No se pudo realizar el envío del email',
Same, Why did you change the messages for `soporte tecnico`?, you should return them to how they were

2023-12-21 22:27 UTC, Cristianpan commented on app/Controllers/CtrlEmail.php
> +                'message' => 'Se ha enviado correctamente',
It was my mistake, I've already corrected it.

2023-12-21 22:27 UTC, Cristianpan commented on app/Controllers/CtrlEmail.php
> +                'message' => 'No se pudo realizar el envío del email',
It was my mistake, I've already corrected it too.

2023-12-23 01:00 UTC, LUGAMAFE requested changes

2023-12-23 01:00 UTC, LUGAMAFE commented on app/Config/Constants.php
> +define('PRODUCT_EMAIL_ID', 3);
Hey @Cristianpan
```suggestion
```

Let move these constants to the file `app\Controllers\CtrlEmail.php`

```php
<?php
namespace App\Controllers;

class CtrlEmail extends BaseController
{
    /**
     * Email Types ID
     */
    const CONTACT_EMAIL_ID = 1;
    const SUPPORT_EMAIL_ID = 2;
    const PRODUCT_EMAIL_ID = 3;

    // Resto del código...
}
?>```

so we can use it like this: `CtrlEmail::CONTACT_EMAIL_ID;`

i don't see those variables being used in other places

2023-12-23 01:00 UTC, LUGAMAFE commented on src/public/js/product.js
> +      fn: function (field, container) {
Remove this line and remove unused variable
```suggestion
      fn: function (field) {
```

2023-12-23 01:00 UTC, LUGAMAFE commented on src/public/js/product.js
> +  },
```suggestion
  add: function (field, message, cls) {
    let errorElement = document.querySelector(`.${field.id}.${cls}`);
    
    if (!errorElement) {
      errorElement = document.createElement('p');
      errorElement.classList.add(field.id, cls);
      clonedForm.querySelector(`[for='${field.id}']`).after(errorElement);
    }

    errorElement.textContent = message;
  },
```

2023-12-23 01:02 UTC, LUGAMAFE requested changes
Good job @Cristianpan just please correct the nits and please make the mobile view look like this:

![image](https://github.com/loopcrack-org/Kinub/assets/24960025/3022fce7-8cb3-4df7-98a1-05e48ed0753f)

2023-12-27 17:46 UTC, CarlosJCD approved these changes
Nice Job!, just check out @CheloChidoone requested changes.

2023-12-27 17:46 UTC, CheloChidoone requested changes
Good Job @Cristianpan, thanks for making my requested changes, I have one more, make sure to deactivate the `enviar` button after the first click to prevent multiple emails

CC: @CarlosJCD

2023-12-29 16:45 UTC, CheloChidoone approved these changes
Good Job @Cristianpan

2024-01-02 01:32 UTC, LUGAMAFE requested changes
Please check and remove this padding on mobile views:
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/aa4c96b6-b4c3-4d69-9393-bc5c19fb15d9)

And merge with the latest main branch please

2024-01-03 03:04 UTC, LUGAMAFE approved these changes
Thanks @Cristianpan

2024-01-03 04:16 UTC, Mauriciocr207 approved these changes

2024-01-03 04:17 UTC, merged