KIN-335: Files Management Functionality on Measurement Solutions CRUD
loopcrack-org/Kinub pull request #156
Opened 2023-12-15 16:48 UTC by CarlosJCD

## Summary

### Problem

The CRUD operations for the measurement solutions entities does not handle files values.

### Solution

It is implemented the files management logic on the CRUD operations of the measurement solutions entities

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

#### On Create:
- [x] It must validate the file inputs
   -  The icon input must receive only 1 file, with a max size of 1MB and the file can only have a .svg extension
   -  The icon input must receive only 1 file, with a max size of 2MB and the file can only have a .jpg, .jpeg or .png extension.
- [x] It must store the measurement solutions files on the server and files routes on the database. Finally link them in measurement solution record.
#### On Update:
- [x] If the measurement solution image and/or icon are changed, the new files must be stored on the server and their routes stored in the database, as well as link this new file records to the measurement solution record. Finally the old files must be deleted from the server and the database.

#### On Delete:
- [x] It must delete the measurement solutions files on the server and from the database.

### Testing

- [x ] Create a new measurement solution record using the create view, you will see the new filepond inputs as well as its validation when you upload a file on the input. Also when the measurement solution is created you will see the stored files on the `/uploads` directory.
- [x ] Edit an existing measurement solution file in the edit view. Observe how when a new file is uploaded, the old one is deleted and the new one is registered on the database and stored on the uploads directory
- [ x] Delete an existing measurement solution and observe how the uploaded files are deleted.

## Demo

[video demo](https://drive.google.com/file/d/1P4vNMfw6zYSUM0Etrb3IsUcvcOSb3-I2/view?usp=drive_link)

2023-12-19 01:48 UTC, Cristianpan requested changes
When server error messages are displayed, the form layout is deformed. 
![image](https://github.com/loopcrack-org/Kinub/assets/91033040/182af264-b362-4e64-a211-b95102807c7a)

And in the solution edit view the validation errors are not displayed and the filepond status is not preserved either.
[Video Demo](https://youtu.be/g-ggGFEubk0)

2023-12-19 01:48 UTC, Cristianpan commented on app/Controllers/CtrlSolution.php
> +            return redirect()->to($this->MEASUREMENT_SOLUTIONS_BASE_ROUTE)->with('response', $response);
Update this constant 
```suggestion
            return redirect()->to(self::MEASUREMENT_SOLUTIONS_BASE_ROUTE)->with('response', $response);
```

2023-12-19 01:48 UTC, Cristianpan commented on app/Controllers/CtrlSolution.php
> +            return redirect()->to($this->MEASUREMENT_SOLUTIONS_BASE_ROUTE)->with('response', $response);
Update this constant 
```suggestion
            return redirect()->to(self::MEASUREMENT_SOLUTIONS_BASE_ROUTE)->with('response', $response);
```

2023-12-19 01:48 UTC, Cristianpan commented on app/Models/MeasurementSolutionModel.php
> +        }
Please add the rollback sentence 
```suggestion
        } catch (Throwable $th) {
           $this->db->transRollback();
            throw $th;
        }
```

2023-12-19 01:48 UTC, Cristianpan commented on app/Models/MeasurementSolutionModel.php
> +    }
I consider that this try catch is unnecessary since you do nothing more than catch the same error and throw it, which would be the same as if there were no try catch.

2023-12-19 19:37 UTC, FernandoJoachin commented on app/Controllers/CtrlSolution.php
> +        $fileConfigBuilder->builder('msImage')->isImage()->minFiles(1)->maxFiles(1)->maxSize(2, 'MB')->build();
Add the maxDimensions function to both.

2023-12-19 19:38 UTC, FernandoJoachin commented on app/Models/MeasurementSolutionModel.php
> +            $fileModel->delete($msData['msImageId']);
@Cristianpan Pan, I have the following question. Since TransException has been added, is it no longer necessary to validate if the delete query returned false to throw an exception?"

2023-12-20 01:24 UTC, Mauriciocr207 commented on app/Controllers/CtrlSolution.php
> +        $fileConfigBuilder->builder('msImage')->isImage()->minFiles(1)->maxFiles(1)->maxSize(2, 'MB')->build();
@FernandoJoachin in the case of svg, is not neccesary to set dimensions

2023-12-20 01:30 UTC, Cristianpan commented on app/Models/MeasurementSolutionModel.php
> +            $fileModel->delete($msData['msImageId']);
It's correct because before if there was an error, the delete returned a false but with the use of `$this->db->transException(true)->transStart()` now it throws an exception if there is an error.

2023-12-20 02:18 UTC, CheloChidoone approved these changes
Good Job @CarlosJCD, just finish checking the comments that Cristian and Joachin left you

2023-12-20 02:59 UTC, Oswaldo-Chan approved these changes

2023-12-20 03:04 UTC, Mauriciocr207 requested changes

2023-12-20 03:04 UTC, Mauriciocr207 commented on app/Models/MeasurementSolutionModel.php
> +            $fileModel->delete($msData['msImageId']);
I think this is incorrect. I think there is an incorrect relation on db, because you are deleting the entity measurement solution through the files. And I think that is an incorrect relation. Because of the way the db is already built, I think you need to delete the entity measurement solution first, and then delete the files. And I think you can change the db on fk actions, setting on delete set null and on update set null

2023-12-20 03:06 UTC, Mauriciocr207 requested changes

2023-12-20 03:06 UTC, Mauriciocr207 commented on app/Controllers/CtrlSolution.php
> +                throw new InvalidInputException($msDataValidator->getErrors());
Here you are not validating the files. This could be like following:
```suggestion
            $fileValidationRules = $this->fileConfig->getCollectionFileValidationRules();
            $msDataValidator->addRules($fileValidationRules['rules'], $fileValidationRules['messages']);
            if (! $msDataValidator->validateInputs($msData)) {
                throw new InvalidInputException($msDataValidator->getErrors());
            }
```

2023-12-20 03:06 UTC, Mauriciocr207 commented on app/Controllers/CtrlSolution.php
>              }
Validate files here, too

2023-12-21 02:17 UTC, Mauriciocr207 requested changes
I left you some comments
CC: @LUGAMAFE

2023-12-21 02:17 UTC, Mauriciocr207 commented on app/Controllers/CtrlSolution.php
> +    }
To improve and make more dinamic the routes you defined here, codeigniter provides global functions like [url_to](https://www.codeigniter.com/user_guide/helpers/url_helper.html?highlight=url_to#url_to) that allows you pass the class and any of its methods to return the route asociated to it. For example here you can change the controller to something like this:
```suggestion
    private static $MEASUREMENT_SOLUTIONS_BASE_ROUTE;
    private static $MEASUREMENT_SOLUTIONS_CREATE_ROUTE;

    protected FileValidationConfig $fileConfig;

    public function __construct()
    {
        self::$MEASUREMENT_SOLUTIONS_BASE_ROUTE = url_to(self::class . '::viewSolutions');
        self::$MEASUREMENT_SOLUTIONS_CREATE_ROUTE = url_to(self::class . '::viewSolutionCreate');
    
        $fileConfigBuilder = new FileValidationConfigBuilder(self::$MEASUREMENT_SOLUTIONS_BASE_ROUTE);

        $fileConfigBuilder->builder('msIcon')->isSVG()->minFiles(1)->maxFiles(1)->maxSize(1, 'MB')->build();
        $fileConfigBuilder->builder('msImage')->isImage()->minFiles(1)->maxFiles(1)->maxDims(500, 500)->maxSize(2, 'MB')->build();

        $this->fileConfig = $fileConfigBuilder->getConfig();
    }
```

2023-12-21 02:17 UTC, Mauriciocr207 commented on app/Controllers/CtrlSolution.php
> +            return redirect()->to(self::MEASUREMENT_SOLUTIONS_EDIT_ROUTE . $msId)->withInput()->with('errors', $th->getErrors());
Here, in order you use only once the `MEASUREMENT_SOLUTIONS_BASE_ROUTE` variable, then you can do here
```suggestion
            return redirect()->to(url_to(self::class . '::viewSolutionEdit', $msId))->withInput()->with('errors', $th->getErrors());
```

2023-12-21 02:18 UTC, LUGAMAFE approved these changes
Just one small nitpick and same comments as @Mauriciocr207 before doing merge

2023-12-21 02:18 UTC, LUGAMAFE commented on app/Controllers/CtrlSolution.php
> +        }
Revert the if always use the true path first
```suggestion
        if (session()->has('clientData')) {
            $dataFiles = session()->get('clientData');
        } else {
            $dataFiles['msIcon']  = [$msData['msIcon']];
            $dataFiles['msImage'] = [$msData['msImage']];
        }
```

2023-12-21 02:40 UTC, Cristianpan approved these changes

2023-12-21 02:41 UTC, CarlosMay7 approved these changes

2023-12-21 06:01 UTC, CarlosJCD commented on app/Controllers/CtrlSolution.php
> +            return redirect()->to(self::MEASUREMENT_SOLUTIONS_EDIT_ROUTE . $msId)->withInput()->with('errors', $th->getErrors());
why not using the static constant generated above?

2023-12-21 06:05 UTC, CarlosJCD commented on app/Controllers/CtrlSolution.php
> +    }
can I generate its value on the variable definitions instead of the constructor? or is it really necessary to generate it on the class constructor?

2023-12-21 17:17 UTC, Mauriciocr207 commented on app/Controllers/CtrlSolution.php
> +    }
The correct way to pass the method to the url_to is addin a string `"Controller::method"` , when we use `self::class`, that generates a string with the controller class name

2023-12-21 17:21 UTC, Mauriciocr207 commented on app/Controllers/CtrlSolution.php
> +            return redirect()->to(self::MEASUREMENT_SOLUTIONS_EDIT_ROUTE . $msId)->withInput()->with('errors', $th->getErrors());
When we use constants like the way you do before, we can´t use functions in constants expresions
Like: 
```php
private const MS_BASE = url_to(...)
```  
That is incorrect because is not a constant argument, but a function. That´s the reason we need to set an static variable and set it into the `__construct()` function

2023-12-21 20:37 UTC, Mauriciocr207 approved these changes

2023-12-22 02:19 UTC, merged