KIN-362_KIN-363_KIN-364_KIN-366 Improve all pages designs
loopcrack-org/Kinub pull request #157
Opened 2023-12-16 01:17 UTC by Tort9994

## Summary

### Problem

Some pages needed some style changes specially for desktop

### Solution

There is an improve on sizes and spaces for mostly all elements for those pages 

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] All views on destkop and other brakepints must look good 

### Testing
- [ ] Manually checked all brakepoints

## Resources

2023-12-16 02:43 UTC, LUGAMAFE commented
The title of the PR is wrong @Tort9994 should be 
KIN-362, KIN-363, KIN-364, KIN-366 Improve all pages designs

2023-12-16 03:08 UTC, LUGAMAFE requested changes
Really nice Job @Tort9994 just a couple of small changes i think

2023-12-16 06:06 UTC, CarlosMay7 commented on src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
> +      text-decoration: underline;
I don't know if this style fits the best with the current implementation of the nav bar, I think it looks kind of weird

Especially because it won't be always on the "selected" option
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/e3f2a52e-bdc1-497d-8b34-0ebf1f93f5b9)

2023-12-16 06:10 UTC, CarlosMay7 commented on src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
> +  margin: $spacing-xxl 0 0 auto;
```suggestion
  margin: $spacing-xxl auto 0 auto;
```
I think the margin should be this way so it is centered because in a 4k display it looks crooked

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/59332498-7082-4675-a557-8ca9c2c40750)

2023-12-16 06:14 UTC, CarlosMay7 approved these changes
Just check the comments Luis and I left you and it's ok

2023-12-16 07:13 UTC, Tort9994 commented on src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
> +      text-decoration: underline;
i didnt understand very well, is it about the underline right? the thing is that the user would not know that navbar is also clickable, i think  its kind of good, but i like to know if the is a better idea on styles if you are able to

2023-12-16 14:33 UTC, CarlosMay7 commented on src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
> +      text-decoration: underline;
Maybe you can make the background change when you hover over it

2023-12-17 04:17 UTC, FernandoJoachin approved these changes

2023-12-17 04:19 UTC, CarlosMay7 approved these changes

2023-12-18 19:51 UTC, merged