KIN-121 Create product view products page frontend
loopcrack-org/Kinub pull request #159
Opened 2023-12-17 06:44 UTC by Mauriciocr207

## Summary

### Problem

As the company i want a form through which I can register a new product, so that I can create new products on the system in a simpler way.

### Solution

Create the view for the product create form on admin panel

## Acceptance Criteria

### Requirements checklist

- [x] The form must gather the following data:
     - Product name.
     - Product model.
     - Product category.
     - Product category tags, provided by a searchbar.
     - Product tags.
     - Technical data of the product, input by key-value.
     - This key-value form must registered by dinamic key-value inputs.
     - Images and videos of the product.
     - Product Description (WYSIWYG Editor).
     - Product demo video.
     - Product representative image.
     - Brochure files.
     - Product certificates files.
     - Product Manual Files.
     - Product Datasheet Files.
- [x] It must have a submit button that on click the form data is submitted.
- [x] There must be a submit button that when it is clicked the form info is submitted.
- [x] When submitted the form, It must display an alert indicating success on creating the product or failure in the process

### Testing

- [x] To test this pr remember do `npm i`, `npm run dev:common` and then `npm run dev:admin`.  And go to route `/admin/productos/crear`
- [x] On the `CtrlProduct` there is a variable called `$passed`. Set it to `true` if you want a succes behavior or `false` if you want a failure behavior and how you are redirected to product create page with inputs seted.

## Resources
## Demo

2023-12-21 19:16 UTC, FernandoJoachin commented on app/Views/admin/products/productsFormTemplate.php
> +                        <option value="">Selecciona una categoría</option>
Change the text from 'Selecciona una categoría' to 'Selecciona un tag de categoría' or something similar.

2023-12-21 19:31 UTC, CarlosJCD commented on app/Models/CategoryTagModel.php
> +        $builder = $this->select(['categoryTagId', 'categoryTagName']);
Nitpick: Maybe change this to a more specific name like queryBuilder.
```suggestion
        $queryBuilder = $this->select(['categoryTagId', 'categoryTagName']);
```

CC: @FernandoJoachin

2023-12-21 19:31 UTC, CarlosJCD commented on src/admin/js/app.js
> +    // });
Is it necessary to keep this commented block of code? if not please delete it.

CC: @FernandoJoachin

2023-12-21 19:31 UTC, CarlosJCD commented on src/admin/js/pages/keyValueInput.js
> +  const keyValueKeyContainer = document.createElement('DIV');
NitPick: Maybe this JS code can be more readable by encapsulating some of this lines of codes on its own functions, so that for each created DOM node (`keyValueKeyContainer`,`keyValueKeyLabel`,`keyValueKey`, etc.) we have a respective function that denotes better its intention.

CC: @FernandoJoachin

2023-12-21 19:31 UTC, FernandoJoachin requested changes
Good job, just do those nitpick changes
CC: @CarlosJCD

2023-12-22 02:24 UTC, CarlosJCD approved these changes

2023-12-22 10:07 UTC, FernandoJoachin approved these changes

2023-12-22 22:03 UTC, Cristianpan requested changes
Nice Job! but I left you some comments

2023-12-23 02:26 UTC, CarlosMay7 commented on app/Views/admin/products/productsFormTemplate.php
> +                        <input type="text" class="form-control" name="name" id="name" placeholder="Ingresa el nobre del producto" value="<?= old('name') ?? ''?>" required>
```suggestion
                        <input type="text" class="form-control" name="name" id="name" placeholder="Ingresa el nombre del producto" value="<?= old('name') ?? ''?>" required>
```

2023-12-23 02:40 UTC, CarlosMay7 requested changes
We think it looks good but we found you missed the demo video input mentioned on the acceptance criteria, please add it.

CC: @Cristianpan

2023-12-27 18:09 UTC, CarlosJCD requested changes
We had an issue with the filepond inputs, for some reason when we try to upload an image or a file on any filepond input of the form it appears an error massage saying "error during upload". Please check it out.

<img width="1496" alt="Screenshot 2023-12-27 at 12 06 19" src="https://github.com/loopcrack-org/Kinub/assets/89323622/34888687-a57f-492b-bdeb-b2c5a661aa62">

Also we have an small suggestion on the wysiwyg inputs. We dont know if this is possible but we think that the tool bar that appears on top could be better if its background color is a little bit darker, however we dont know if its possible to make this change, so just check it out if its possible please.

CC: @CheloChidoone

2023-12-27 18:10 UTC, CheloChidoone requested changes
Good job @Mauriciocr207 but check the changes @CarlosJCD mentioned

2023-12-27 23:05 UTC, CarlosJCD requested changes
Thanks for fixing the bug, however now I noticed that on the `Imagenes`, `Videos` and all of the `Area de descarga` inputs does not allow me to upload more than one file. Please check it out and let me know if this is an error or this is something of my environment.

2023-12-27 23:10 UTC, CarlosJCD approved these changes
Nice job!

2023-12-28 06:10 UTC, Cristianpan requested changes
There is a bug with the dropdown to logout and maybe could be for the keyValueInput.js because we have seen that if we disable that js, the dropdown already works. Please check it and make the changes

CC: @FernandoJoachin

2023-12-28 21:18 UTC, Cristianpan approved these changes

2023-12-29 09:03 UTC, FernandoJoachin approved these changes

2023-12-29 16:59 UTC, CheloChidoone approved these changes
Good Job Mau, We have some questions about how the functionality will work later but we can address them tomorrow in the sprint review, but for the visual part of the product creation page this is very good

CC: @CarlosJCD

2023-12-29 22:21 UTC, CarlosMay7 approved these changes

2023-12-30 18:47 UTC, Cristianpan approved these changes
Thanks for adding the error message template

2023-12-30 20:54 UTC, merged