KIN-336 Add files managament in categories crud
loopcrack-org/Kinub pull request #160
Opened 2023-12-18 00:18 UTC by Cristianpan

## Summary

### Problem

Administrators must be able to add and update category files.

### Solution

Implement the files management logic in the categories crud. 

## Acceptance Criteria

### Requirements checklist

On create category:

- [x] It must store the category files on the server and files routes on the database. Finally link them in category record. 

On edit category:

- [x] If the edit category image and/or icon are changed, the new files must be stored on the server and their routes stored in the database, as well as link this new file records to the category record. Finally the old files must be deleted from the server and the database.
- [x] It is important to first register the new files and then delete the old ones because of the database design. 

On delete category:

- [x] It must delete the category files from the server and the database.

### Testing
_Note:_ Before to test this feature, run in console `php spark migrate:refresh` and as next step `php spark db:seed MainTestSeeder` to update the categories table. 

- [x] Create a new category and add its corresponding files. Verify that the files are saved on the server and in the db. 
- [x] Updates the files in an existing category and verifies that the new files are saved on the server and in the database, as well as deleting the old files from the server and db. 
- [x] Deletes a category and verifies that the files are removed from the server as well as from the db.

## Resources
## Demo

2023-12-21 17:22 UTC, Oswaldo-Chan approved these changes

2023-12-21 17:22 UTC, CheloChidoone approved these changes
Good Job @Cristianpan and thanks for adding the category subname field

2023-12-22 02:29 UTC, CarlosJCD approved these changes
Nice work!

2023-12-22 09:53 UTC, FernandoJoachin commented on app/Controllers/CtrlCategory.php
> +    private const CATEGORIES_BASE_ROUTE = '/admin/categorias/';
You should follow the new standard we are using to create class attributes over route constants. Check CtrlSolution

2023-12-22 09:53 UTC, FernandoJoachin commented on app/Controllers/CtrlCategory.php
> +        $fileConfigBuilder = new FileValidationConfigBuilder('/admin/categorias');
Don't forget to change this to class attributes

2023-12-22 09:55 UTC, FernandoJoachin requested changes
Great job!, just make those small changes.

2023-12-22 23:38 UTC, FernandoJoachin approved these changes

2023-12-23 00:37 UTC, merged