KIN-320: Improve logo and particles effect login page
loopcrack-org/Kinub pull request #161
Opened 2023-12-18 17:53 UTC by CarlosJCD

## Summary

### Problem

The login views does not have the same display style as well as the particles on the background needs to be improved

### Solution

Standarization of login views and improvement of the particles effects

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [x] The particles effect are change into a more complex one and interacts with the user clicks
- [x] The login views must be the same, with the kinub icon on top and outside of the form card and with its own white background

### Testing

- [x] Go to the login views and see the changes ( `/login,` `/password_reset`, `/password_reset/:token` )

## Demo

[demo video](https://drive.google.com/file/d/1N0YGZOc5btoNYczxfe2Bj8GpMq5bg94u/view?usp=sharing)

2023-12-19 03:10 UTC, CarlosMay7 reviewed
Maybe you can reconsider the final design, we think it looks a little weird. Maybe you can add a box shadow or a sort of filter and then remove the white background if you still want to keep the logo outside of the login box

CC: @Cristianpan

2023-12-21 03:04 UTC, Cristianpan commented on app/Views/login/PasswordEmail.php
>                                          <lord-icon src="https://cdn.lordicon.com/rhvddzym.json" trigger="loop" colors="primary:#0ab39c" class="avatar-xl">
Maybe would be good change this class `avatar-xl` for `avatar-lg`

2023-12-21 03:04 UTC, Cristianpan approved these changes

2023-12-21 03:04 UTC, CarlosMay7 approved these changes

2023-12-21 17:36 UTC, CheloChidoone requested changes
@CarlosJCD good job with the particles, that looks better, but for the logo did you change back what you did?, On login and password reset we see the logo still inside the box with the form, only on password reset with a token we see the logo outside but without the white background circle, let us know if we missed a step to get it to work or fix it if it is an actual mistake 
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/35765dd9-6662-418d-87a2-12320df9ef83)
CC: @Oswaldo-Chan

2023-12-22 04:52 UTC, CarlosJCD commented
> @CarlosJCD good job with the particles, that looks better, but for the logo did you change back what you did?, On login and password reset we see the logo still inside the box with the form, only on password reset with a token we see the logo outside but without the white background circle, let us know if we missed a step to get it to work or fix it if it is an actual mistake ![image](https://private-user-images.githubusercontent.com/38699927/292277300-35765dd9-6662-418d-87a2-12320df9ef83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjA5NTMsIm5iZiI6MTcwMzIyMDY1MywicGF0aCI6Ii8zODY5OTkyNy8yOTIyNzczMDAtMzU3NjVkZDktNjY2Mi00MThkLTg3YTItMTIzMjBkZjllZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA0NTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZjEwNGQzMTg2Mzc1YjBjOGM0MjIwNTRkMTE1OWM3ZWFhNDYzNWEzNTdjYzQ2MjAwODAxNDUxNzFmNjBjMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wu9g_HZsd5QrVdF8bhxSkbn5scB4WI9ITTI4GQL6GXg) CC: @Oswaldo-Chan

My mistake!, I totally forgot to update the response view. I will change it right away, thanks for noticing this!

2023-12-23 17:27 UTC, Mauriciocr207 approved these changes

2023-12-27 18:15 UTC, CheloChidoone approved these changes
Good Job @CarlosJCD, it looks a lot better

2023-12-27 18:16 UTC, merged