KIN-355 Side bar product filters layout
loopcrack-org/Kinub pull request #162
Opened 2023-12-19 04:49 UTC by Oswaldo-Chan

## Summary

### Problem

It's needed a component to apply the filters of the products on the products catalog page.

### Solution

A sidebar has been implemented, it contains the filter options for category, category tags and product tags.

## Acceptance Criteria

### Requirements checklist

- [x] A section to filter by category
- [x] A section to filter by category tags
- [x] A section to filter by product tags

### Testing

- [x] Test Responsive Design
- [x] Test multiple selection of checkboxes

## Resources

## Demo

[VIDEO DEMO](https://clipchamp.com/watch/aZ27qHmnTYB)

2023-12-21 05:19 UTC, Cristianpan requested changes
There is a "bug" with filters for devices smaller than 768 px. Please check it and make the correction.
[Video Demo](https://youtu.be/7l3ZuBv-zL0)

2023-12-22 04:50 UTC, CarlosJCD requested changes
Nice job!, i really love the design however i think there is an issue with this filters sidebar. On mobile views (viewport width less than 1024px) this filters sidebar can be removed but i cant see a way to display again this filter other than reloading the page. I believe that it would be optimal to give the users on this resolutions a way to display again the filters sidebar without having to reload the page. If this is made on purpose and there is something that I am missing out please let me know so that i can accept this changes. 😄

2023-12-29 04:40 UTC, CarlosJCD approved these changes

2024-01-07 06:24 UTC, LUGAMAFE requested changes
The sidebar looks very different from Saturday's demo, we need to add or make it look like today's demo, plus the corrections, margins, paddings, and font sizes that we discussed.

2024-01-13 00:17 UTC, merged