KIN-304 edit certificate functionality with files
loopcrack-org/Kinub pull request #166
Opened 2023-12-22 07:43 UTC by FernandoJoachin

## Summary

### Problem

As an administrator of the admin panel, I want to edit an registered certificate so that they can be up to date on the public view

### Solution

Add the functionality to edit certificate with files

## Acceptance Criteria

### Requirements checklist

- [ ] It must validate the form inputs to not be empty.
- [ ] If it passes all the validations: If the certificate name is changed, it must update the certificate record on the database.
- [ ] It must return a response to the view indicating success on updating the certificate or failure in the process.
- [ ] It must validate that on the certificate file input it is only uploaded pdf files.
- [ ] It must validate that on the certificate preview input it is only uploaded png/jpg files.
- [ ] If the certificate preview image is changed, the previous certificate preview image must be deleted, the new certificate preview image stored  and the records on the database for the file must be updated.
- [ ] If the certificate file is changed, the previous certificate file must be deleted, the new certificate file stored and the records on the database for the file must be updated. 

### Testing

- [ ] Create a certificate, and then edit its information.
- [ ] Delete a file and upload a new one. The change must be reflected on the server and in the database

2023-12-23 03:02 UTC, CarlosMay7 approved these changes

2023-12-23 03:02 UTC, Cristianpan approved these changes

2023-12-27 18:29 UTC, CarlosJCD requested changes
Nice Job!, just an observation that when we try to delete a file from the input and the pop-up message appears, this must appear with the same color theme as the page one, however this always appear in light theme, this happens because you need to add its respective styles to the form, please fix it.

<img width="1496" alt="Screenshot 2023-12-27 at 12 28 43" src="https://github.com/loopcrack-org/Kinub/assets/89323622/edd88cfe-eb74-4f94-96d3-482465554e25">

CC: @CheloChidoone

2023-12-29 03:40 UTC, Mauriciocr207 approved these changes

2023-12-29 04:40 UTC, CarlosJCD approved these changes

2023-12-29 17:03 UTC, CheloChidoone approved these changes
Good Job @FernandoJoachin, thanks for making the corrections

2023-12-29 22:49 UTC, merged