KIN-343 integrate about us section with the admin panel
loopcrack-org/Kinub pull request #167
Opened 2023-12-22 08:40 UTC by FernandoJoachin

## Summary

### Problem

It is needed to integrate the admin panel generated values with the public view

### Solution

Integrate the about us record generated on the admin panel in the about us section of the public view

## Acceptance Criteria

### Requirements checklist

- [ ] The about us text generated on the admin panel must be displayed on the public view
- [ ] The about us image stored through the admin panel must be displayed on its public view section.
- [ ] The about us video stored through the admin panel must be displayed on its public view section.
- [ ] The about us styles section layout should not break with the integration of the file values.

### Testing

- [ ] Go to the next route /admin/nosotros and upload the corresponding files.
- [ ] Go to the home page and check that the previously uploaded files are reflected on the site

2023-12-23 03:16 UTC, CarlosMay7 approved these changes
Nice job!

2023-12-23 03:16 UTC, Cristianpan approved these changes

2023-12-29 05:15 UTC, CarlosJCD requested changes
I think that it is important to limit the amount of text that the user can insert for the about  us text section on the admin panel. This is important because if it is not restricted then the user can place a lot of info and the layout of the about us section get broken. Please check it out and set a limit at your discretion

2023-12-29 17:16 UTC, CarlosJCD requested changes
There is an issue with the current way of the restriction of characters on the text field of the about us page. Because there is a limit of characters stablished on the html tag of the text area, the user gets restricted but there is no kind of feedback or warning telling the user that it was reached the limit of characters, even where it is a validation there is also no kind of tool or tip to the user indicating if the text has reached its limit or not. Maybe velzon has some kind of input that could help you with this.

CC: @CheloChidoone

2023-12-29 17:17 UTC, CheloChidoone requested changes
Good Job in general @FernandoJoachin but check @CarlosJCD comment about the issues with the text area character limit

2024-01-02 03:18 UTC, LUGAMAFE approved these changes
Hey @FernandoJoachin nice job can you set max dims for the image please. Im thinking about W1200px x H1000px

2024-01-02 23:26 UTC, CarlosJCD approved these changes
Nice work!. Just a nitpick

2024-01-02 23:26 UTC, CarlosJCD commented on src/admin/js/pages/textareaCounter.js
> +  characterCount.textContent = `${textLength}/${450}`;
I think it is only needed the `${}` syntax on string templates for operations or variables

```suggestion
  characterCount.textContent = `${textLength}/450`;
```

2024-01-02 23:40 UTC, CheloChidoone approved these changes

2024-01-03 03:20 UTC, LUGAMAFE commented on src/admin/js/pages/textareaCounter.js
hey @FernandoJoachin do we really need this file? if we already have in the textarea a maxlength="450"

2024-01-03 03:24 UTC, LUGAMAFE requested changes

2024-01-03 03:24 UTC, LUGAMAFE commented on src/admin/js/pages/textareaCounter.js
> +  }
I dont think we need this code
```suggestion
```

2024-01-03 03:24 UTC, LUGAMAFE commented on src/admin/js/pages/textareaCounter.js
> +const errorAboutUsText = document.querySelector('.invalid-feedback');
Where we have this element 
```suggestion
```

2024-01-03 03:24 UTC, LUGAMAFE commented on src/admin/js/pages/textareaCounter.js
> +    errorAboutUsText.classList.remove('d-none');
remove 
```suggestion
```

2024-01-03 03:24 UTC, LUGAMAFE commented on src/admin/js/pages/textareaCounter.js
> +    errorAboutUsText.classList.remove('d-block');
remove

2024-01-03 18:21 UTC, Mauriciocr207 approved these changes
Good job!

2024-01-07 06:40 UTC, LUGAMAFE requested changes
Hey @FernandoJoachin check these padding problems please
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/09c1e9a5-ad55-4a95-baf3-c170353b50b6)

And can you help meGPT adding the capability to edit the "About Us" text.
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/c3e774e3-ab98-4307-925d-fe6b3f2af0bc)

2024-01-08 06:57 UTC, FernandoJoachin commented
> Hey @FernandoJoachin check these padding problems please ![image](https://private-user-images.githubusercontent.com/24960025/294742037-09c1e9a5-ad55-4a95-baf3-c170353b50b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTcyMjIsIm5iZiI6MTcwNDY5NjkyMiwicGF0aCI6Ii8yNDk2MDAyNS8yOTQ3NDIwMzctMDljMWU5YTUtYWQ1NS00YTk1LWJhZjMtYzE3MDM1M2I1MGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA2NTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MDA2MWNiZmYwMzZkODhmMzI2NGQ4ODYyZmFlZDgwNmVjYWQxYjgxZjk2N2Q1OWI5NTY3OTZhMjY5YmUzZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5lvGUSsqcBiqQBgoaUtcrtYYP9_Me_DQaAEpgjPTQk)
> 
> And can you help meGPT adding the capability to edit the "About Us" text. ![image](https://private-user-images.githubusercontent.com/24960025/294742088-c3e774e3-ab98-4307-925d-fe6b3f2af0bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTcyMjIsIm5iZiI6MTcwNDY5NjkyMiwicGF0aCI6Ii8yNDk2MDAyNS8yOTQ3NDIwODgtYzNlNzc0ZTMtYWI5OC00MzA3LTkyNWQtZmU2YjNmMmFmMGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA2NTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZDdlMDU5YTRmZWMxNTVhZjc0MGFlODVkZjk3MTk2ZTU3MDc2NGNkOTVkOWQzMDU0NzgwOGE2NDNhZTY5YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QR1SFCdtgqid-nm62cDSJLyShHRLLdXG-ONkkvwf2Qs)

The padding problem was fixed in the KIN-128

2024-01-09 17:05 UTC, Oswaldo-Chan approved these changes

2024-01-09 17:05 UTC, LUGAMAFE approved these changes
All good @FernandoJoachin thank you! i just have a small nit

2024-01-09 17:05 UTC, LUGAMAFE commented on app/Validation/AboutUsValidation.php
> +            'required'   => 'El titulo es obligatoria.',
Nit
```suggestion
            'required'   => 'El titulo es obligatorio.',
```

2024-01-09 17:39 UTC, Oswaldo-Chan approved these changes

2024-01-09 17:49 UTC, merged