KIN-178 Database Table and Seeder
loopcrack-org/Kinub pull request #17
Opened 2023-08-28 07:21 UTC by CarlosJCD

### Problem

the need to store the records of users accessing the database.

### Solution

Implement a Table on the database that stores specific information of the users.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] The table must match with the class diagram

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Check the table correctness with the seeder that was created via spark.

## Resources

- [Database Design Document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/1277953/Database+Design)
- [Class Diagram Document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/1605633/Class+Diagram)

2023-08-28 16:45 UTC, Cristianpan requested changes
You've changed the name of the columns in the email table, so this is throwing an error in EmailSeeder, please check and make the changes.

2023-08-28 17:45 UTC, Cristianpan approved these changes

2023-08-28 22:17 UTC, Mauriciocr207 approved these changes

2023-08-28 23:52 UTC, Oswaldo-Chan approved these changes

2023-08-29 02:56 UTC, CheloChidoone approved these changes

2023-08-29 03:15 UTC, merged