KIN-347 integrate measurement solutions section with the admin panel home page
loopcrack-org/Kinub pull request #170
Opened 2023-12-28 16:00 UTC by FernandoJoachin

## Summary

### Problem

It is needed to integrate the admin panel generated values with the public view.

### Solution

Integrate the measurement solutions values generated on the admin panel in the about us section of the public view

## Acceptance Criteria

### Requirements checklist

- [ ] For each measurement solution registered via the admin panel must be displayed on the measurement solutions section.
- [ ] The measurement solution name registered via the admin panel must be displayed in its respective section on the home page.
- [ ] The measurement solution description registered via the admin panel must be displayed on hover on its own section in the measurement solutions section of the home page.
- [ ] The measurement solution styles should not break with the integration of the text values
- [ ] The measurement solution logo stored via the admin panel must be displayed on its respective section on the measurement solutions section of the home page.
- [ ] The measurement solution image stored via the admin panel must be displayed on the background of its respective section on the measurement solutions section of the home page.
- [ ] The measurement solutions section layout should not break with the files values integration

### Testing

- [ ] Go to /admin/solutions and edit a measurement solution. Changes should be reflected on the home page

2023-12-30 18:00 UTC, CarlosMay7 approved these changes
It looks good, just check the comment @Cristianpan left you

2024-01-02 04:16 UTC, LUGAMAFE requested changes

2024-01-02 04:16 UTC, LUGAMAFE commented on app/Views/public/index.php
> +                            <img src="<?= $measurementSolution['msIconRoute']?>" alt="<?= $measurementSolution['msIconName']?>" class="measurement-solution__icon-img">
Instead of using a `<img/>` tag we should use a `<svg/>` tag to avoid the gray animation. Instead of using 
the` filter: brightness(0) invert(1);` we should be using this
```
    * {
      /* stylelint-disable-next-line itcss/no-at-important */
      fill: $color-white !important; //The reason for this is that the svgs imported already have a fill property
    }
```

instead of using the src attribute. We need to get the file content of this route : `$measurementSolution['msIconRoute']`

2024-01-02 23:57 UTC, CheloChidoone approved these changes
Good Job @FernandoJoachin but finish checking and solving what Cristian and Luis told you

2024-01-07 06:54 UTC, LUGAMAFE requested changes
Where is the carousel? yo need to merge with main i think, and we need different colors for each bottom bar
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/ddab37c1-f5bf-49cd-af2b-38e18f01876c)

2024-01-08 06:53 UTC, FernandoJoachin commented
> Where is the carousel? yo need to merge with main i think, and we need different colors for each bottom bar ![image](https://private-user-images.githubusercontent.com/24960025/294742553-ddab37c1-f5bf-49cd-af2b-38e18f01876c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTY5NTcsIm5iZiI6MTcwNDY5NjY1NywicGF0aCI6Ii8yNDk2MDAyNS8yOTQ3NDI1NTMtZGRhYjM3YzEtZjViZi00OWNkLWFmMmItMzhlMThmMDE4NzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA2NTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMGFmNTE3YWIxNDhiOTNhYmQ2NGEwYzQ2ZWJlZmFhMGQyZDk2YmVlOTk5MzBmOWExMjkxYjAxOGRiYWRiOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0eSpESz_WKxsFUXhwQrSe0-MLQn9OX_ur6nMqBYJqk)

The carousel does not appear because currently there are only 4 measurement solutions in the database. If a fifth element is added, the carousel appears

2024-01-08 16:22 UTC, Mauriciocr207 approved these changes

2024-01-09 02:49 UTC, Cristianpan approved these changes

2024-01-09 17:24 UTC, LUGAMAFE requested changes
All good but there is a bug:

https://github.com/loopcrack-org/Kinub/assets/24960025/6ebd9d55-61dd-4e35-9bcf-dea665504c1d

2024-01-09 17:24 UTC, LUGAMAFE commented on src/public/js/home.js
> +});
I think you could move this code to the php file @FernandoJoachin , but good job with this logic

2024-01-09 17:24 UTC, LUGAMAFE commented on src/public/sass/ITCSS/06_components/pages/home/measurement-solutions/_measurement-solution.scss
> +
Don't add new lines please
```suggestion
```

2024-01-09 17:24 UTC, LUGAMAFE commented on app/Controllers/CtrlPublicPages.php
> +        }
```suggestion
    foreach ($measurementSolutions as $key => $value) {
        $msNameParts = explode(' ', $value['msName']);
        $measurementSolutions[$key]['msNameStrong'] = $msNameParts[0];
        $measurementSolutions[$key]['msNameNotStrong'] = implode(' ', array_slice($msNameParts, 1));
    }
```

2024-01-09 18:42 UTC, CarlosJCD commented
> All good but there is a bug:
> 
>  2024-01-09.11-23-04.mp4

@LUGAMAFE  I am mostly sure that it is a problem with the seeders and the database configuration, when i made the seeders and the migration of the database i configured it that when a record of a file is deleted, the record of the entity is also deleted and because in the seeders the majority of the entities have a reference to one single file record, when this record is deleted it deletes also many other entities records. However I was sure that i fixed this when doing the measurement solutions CRUD, please make sure that your database is up to date with the migrations and if the error persists let me know so I can generate a bug ticket.

2024-01-09 18:48 UTC, LUGAMAFE commented
> > All good but there is a bug:
> > 
> >  2024-01-09.11-23-04.mp4
> 
> @LUGAMAFE  I am mostly sure that it is a problem with the seeders and the database configuration, when i made the seeders and the migration of the database i configured it that when a record of a file is deleted, the record of the entity is also deleted and because in the seeders the majority of the entities have a reference to one single file record, when this record is deleted it deletes also many other entities records. However I was sure that i fixed this when doing the measurement solutions CRUD, please make sure that your database is up to date with the migrations and if the error persists let me know so I can generate a bug ticket. 

@CarlosJCD i refreshed the migration and seeds, so yes, it is a problem with seeders that needs to be fixed.

2024-01-09 23:55 UTC, CarlosJCD commented
> > > All good but there is a bug:
> > > 2024-01-09.11-23-04.mp4
> > 
> > 
> > @LUGAMAFE  I am mostly sure that it is a problem with the seeders and the database configuration, when i made the seeders and the migration of the database i configured it that when a record of a file is deleted, the record of the entity is also deleted and because in the seeders the majority of the entities have a reference to one single file record, when this record is deleted it deletes also many other entities records. However I was sure that i fixed this when doing the measurement solutions CRUD, please make sure that your database is up to date with the migrations and if the error persists let me know so I can generate a bug ticket.
> 
> @CarlosJCD i refreshed the migration and seeds, so yes, it is a problem with seeders that needs to be fixed.

Ok I will make sure to generate a bug ticket to change that seeder

2024-01-10 00:01 UTC, CarlosJCD approved these changes

2024-01-10 02:04 UTC, LUGAMAFE approved these changes
Since the seeders will be fixed on other PR i will accept for now. :)

2024-01-11 15:53 UTC, LUGAMAFE approved these changes

2024-01-11 16:10 UTC, merged