KIN-305 delete certificate functionality certificates page
loopcrack-org/Kinub pull request #175
Opened 2024-01-03 08:05 UTC by FernandoJoachin

## Summary

### Problem

As a company I would like to delete certificates from the system so that I can remove any certificate that I no longer have.

### Solution

Add remove certificate functionality in CtrlCertificate

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] It must remove the certificate record from the database
- [ ] It must return a response with a message indicating success on the deleting the certificate or failure in the process
- [ ] It must delete the certificates files from the server
- [ ] It must remove the certificate preview image and the certificate file record from the database

### Testing

- [ ] Go to the next route /admin/certificados/crear and create a certificate. After creating the certificate, delete it with the corresponding button
- [ ] Check that the files were deleted on both the server and the database

2024-01-03 16:47 UTC, Mauriciocr207 approved these changes

2024-01-03 16:47 UTC, CarlosMay7 approved these changes

2024-01-04 17:11 UTC, CheloChidoone requested changes
@FernandoJoachin I left a small comment for you to check and also make sure to check the other observation made by Cristian

2024-01-04 17:11 UTC, CheloChidoone commented on app/Controllers/CtrlCertificate.php
> +            FileManager::deleteMultipleFoldersWithContent([$certificate['certificateUuid']]);
I think it is better if you just call this function once and pass both uuids in the array you give it, calling it twice should not be necessary

2024-01-04 17:19 UTC, Cristianpan requested changes
I left you some comments, please check it and make the changes

2024-01-04 17:19 UTC, Cristianpan commented on app/Models/CertificateModel.php
> +            }
It's unnecessary to verify that the element was deleted and then throw an exception because if it isn't deleted, the statement already throws an exception.

2024-01-04 17:19 UTC, Cristianpan commented on app/Models/CertificateModel.php
> +            $isDeleted  = $fileModel->where($queryWhere)->delete();
Instead of creating an or manually, you can make use of the whereIn statement
```suggestion
            $isDeleted  = $fileModel->whereIn('uuid', [$certificate['previewUuid'], $$certificate['certificateUuid']])->delete();
```

2024-01-07 06:56 UTC, LUGAMAFE approved these changes

2024-01-08 16:24 UTC, CheloChidoone approved these changes
Good Job @FernandoJoachin

2024-01-09 02:50 UTC, Cristianpan approved these changes

2024-01-09 15:25 UTC, merged