KIN-128 Add create product functionality
loopcrack-org/Kinub pull request #176
Opened 2024-01-03 10:45 UTC by Cristianpan

## Summary

### Problem

The administrator needs to create a new product with valid data. If the data is invalid or incomplete, the system shouldn't register the product data and should display error messages.

### Solution

Implement the logict to create and validate the product data to save the register and its files in the server. 

## Acceptance Criteria

### Requirements checklist

- [x] The product name, model, product tags, category, tecnical data, images, description, and files must not be empty (exception on product files).

- [x] It must validate the files inputs when submitted the info:
   - For the product files (certificates, manuals, brochures and datasheets) it must be pdf files only
   - For the product sample video, it must be a mp4 file.
   - For the product representative image
   - For the product images it must be a .png/jjpg images.

If it passes all the validations, the info must be stored:

- [x] The product info must be stored on the database.
   - A new record of the product must be generated on the products table in the database.
   - The associated category tags must be displayed on the “products-category_tags” table in the database.
   - The associated product tags must be stored on the “product_tags“ table in the database. 
   - The images, videos and product files must be stored in the server.
      - The files routes must be stored in the database as well.
      - The files records must be associated with its product on the product-product_files table in the database.

- [x] It must return a response indicating success on creating the new product or indicating that an error occurred in the process.

### Testing
Before this feature, you should make `php spark migrate:refresh` and next `php spark db:seed MainTestSeedert` to update your database. 
- [x] Go to the route `admin/productos/crear` and enter the necessary data to create a new product and you should look for a message with a successful or error message.
- [x] Check that the product data has been saved correctly in the database. 
- [x] Check that the product files have been saved correctly on the server. 
- [x] To verify that the server validations are working correctly, you can do `form.submit()` from the console and you should see all the validation errors

## Resources

- [Technical Design Document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/$END_POINT)

## Demo

If applicable, include screenshots and/or screen recordings associated with your solution

2024-01-03 17:13 UTC, CarlosMay7 requested changes
We think that the image and video inputs must be required fields 
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/e3591f94-6173-42b3-8424-896b25ce26dd)

When you send empty the `Detalles del producto` input it fills the `Clave` input with numbers 
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/dd633fe2-5c12-4752-909b-ea7bc0ab495c)

Furthermore we think that it could be a good idea to show alerts when you send some empty fields

2024-01-03 22:16 UTC, LUGAMAFE commented
@CarlosMay7 @Mauriciocr207 @Cristianpan images and videos are not required fields. Only the main image

2024-01-03 22:18 UTC, Cristianpan commented
> @CarlosMay7 @Mauriciocr207 @Cristianpan images and videos are not required fields. Only the main image

So the video demo is not required too?

2024-01-03 22:27 UTC, Mauriciocr207 commented
> @CarlosMay7 @Mauriciocr207 @Cristianpan images and videos are not required fields. Only the main image

What about the download area, brochure and others are not required too, right?

2024-01-03 22:34 UTC, LUGAMAFE commented
> What about the download area, brochure and others are not required too, right?
> @LUGAMAFE 

We already discussed that topic in the paat, they are optional @Mauriciocr207

2024-01-07 06:58 UTC, LUGAMAFE requested changes
We need the "Recommended" input option that we discussed on saturday demo

2024-01-08 09:46 UTC, FernandoJoachin approved these changes

2024-01-08 16:53 UTC, CheloChidoone requested changes
Good Job @Cristianpan, just check this slight correction on the relevance validation

2024-01-08 16:53 UTC, CheloChidoone commented on app/Validation/ProductValidation.php
> +            'required'    => 'La relevancia del producto obligatoria',
@Cristianpan slight correction, the message should be 'La relevancia del producto **es** obligatoria'

2024-01-08 17:00 UTC, Mauriciocr207 approved these changes
Nice job, just please made the corrections Marcelo m left you

2024-01-08 17:01 UTC, Mauriciocr207 commented on app/Validation/ProductValidation.php
> +            'required'    => 'La relevancia del producto obligatoria',
Also @Cristianpan on line 17 check
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/5225d829-8b04-4987-ac3c-6f2d1c2700da)

Can you correct the name input placeholder to it can say "Ingresa el nombre..."

2024-01-09 16:25 UTC, CarlosMay7 approved these changes

2024-01-09 17:31 UTC, LUGAMAFE requested changes
Good Job @Cristianpan but please the main video should not be required only the main image.
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/beb03f3f-ada4-43f8-905f-ca04ba8d9392)

2024-01-10 00:51 UTC, CarlosJCD approved these changes

2024-01-10 02:07 UTC, LUGAMAFE approved these changes
Nice Job @Cristianpan!

2024-01-10 16:35 UTC, CheloChidoone approved these changes

2024-01-11 04:27 UTC, merged