KIN-342 Add cache busting
loopcrack-org/Kinub pull request #177
Opened 2024-01-03 18:13 UTC by CheloChidoone

## Summary

### Problem

The project has issues with cache preventing the reload of certain files when they change

### Solution

Add cache busting to the project

## Acceptance Criteria

### Requirements checklist

- [ ] When building the project in production mode a manifest generates along with the css and js files to identify them with newly generated names so when they are next requested they'll have to reload and not get stuck in cache
- [ ] When building the project in development mode the project should build the css and js files the same way as before
- [ ] The css and js should all still be working and behaving in the same way in both development and production modes

### Testing

- [ ] Test building the project and using it in development mode and you should see the files in assets stay like we've been using them, test that the css and js look and work correctly in all public and private pages
- [ ] Test building the project and using it in production mode and you should see the files in assets have different names and a manifest file generated inside each assets folder (public, common, and private) and it lists the original names of the files and their new name, test that the css and js looks and works correctly in all public and private pages

## Resources

- [What is cache busting?](https://cloudinary.com/glossary/cache-busting#:~:text=Cache%20busting%20is%20a%20technique,instead%20of%20using%20outdated%20ones.)

## Demo

- If this gets complicated to test and you think it would be necessary we can schedule some time to do a demo

2024-01-09 05:58 UTC, LUGAMAFE requested changes

2024-01-09 17:32 UTC, LUGAMAFE approved these changes
Nice @CheloChidoone thanks for the refactor!!

2024-01-09 17:35 UTC, Oswaldo-Chan approved these changes

2024-01-09 21:42 UTC, CarlosJCD approved these changes

2024-01-10 14:51 UTC, Cristianpan approved these changes

2024-01-11 06:58 UTC, CarlosMay7 approved these changes

2024-01-12 04:19 UTC, FernandoJoachin approved these changes

2024-01-15 20:38 UTC, CheloChidoone commented
@LUGAMAFE I made a commit fixing conflicts with main, can you approve the PR again so it can be merged, thanks

2024-01-16 04:21 UTC, LUGAMAFE approved these changes

2024-01-16 21:55 UTC, LUGAMAFE approved these changes

2024-01-16 21:55 UTC, merged