KIN-345 integration with admin panel equipments page
loopcrack-org/Kinub pull request #178
Opened 2024-01-04 10:05 UTC by FernandoJoachin

## Summary

### Problem

 It is needed to integrate the admin panel generated values with the public view.

### Solution

 Integrate the categories generated in the admin panel on the equipments page

## Acceptance Criteria

### Requirements checklist

- [ ] The categories name must be displayed on the equipments card.
- [ ] For each registered category an equipment card must be displayed.
- [ ] When a card is clicked, the user gets redirected to the product catalog page with its category id as query param.
- [ ] The category logo must be displayed on its respective equipment card on the equipments page of the public view
- [ ] When clicked on its equipment card and redirected to the product catalog page, the product catalog must have as banner the categorie image stored via the admin panel
- [ ] The equipment page certificates layout should not break with the admin integration.

### Testing
- [ ] Go to /admin/category/create and create a category. Changes should be reflected on the equipments page.
- [ ] Clicking on a category, you should be redirected to the product catalog page with the category name in the banner

2024-01-07 07:16 UTC, LUGAMAFE requested changes

2024-01-07 07:16 UTC, LUGAMAFE commented on app/Views/admin/categories/categoriesFormTemplate.php
> +                        <input type="text" class="form-control <?= isset($errors['categorySubname']) ? 'is-invalid' : '' ?>" name="categorySubname" id="categorySubname" value="<?= old('categorySubnam
this input is not required @FernandoJoachin

2024-01-07 07:16 UTC, LUGAMAFE commented on app/Config/Routes.php
> +$routes->get('/categoria/(:num)', [CtrlPublicPages::class, 'viewCategory']);
This URL is not correct; talk to @Mauriciocr207  so he can tell you what the correct URL should be.

2024-01-09 16:55 UTC, CarlosMay7 approved these changes

2024-01-09 17:35 UTC, LUGAMAFE requested changes

2024-01-09 17:35 UTC, LUGAMAFE commented on app/Views/admin/categories/categoriesFormTemplate.php
> +                        <input type="text" class="form-control <?= isset($errors['categoryName']) ? 'is-invalid' : '' ?>" name="categoryName" id="categoryName" value="<?= old('categoryName') ?? $cate
You updated the wrong input  @FernandoJoachin.
This input is required
```suggestion
                        <input type="text" class="form-control <?= isset($errors['categoryName']) ? 'is-invalid' : '' ?>" name="categoryName" id="categoryName" value="<?= old('categoryName') ?? $category['categoryName'] ?? ''; ?>" placeholder="Ingrese el título" maxlength="20">
```

2024-01-09 17:35 UTC, LUGAMAFE commented on app/Views/admin/categories/categoriesFormTemplate.php
> +                        <input type="text" class="form-control <?= isset($errors['categorySubname']) ? 'is-invalid' : '' ?>" name="categorySubname" id="categorySubname" value="<?= old('categorySubnam
this input is the one that is not required

2024-01-09 17:36 UTC, Oswaldo-Chan approved these changes

2024-01-10 16:59 UTC, Mauriciocr207 requested changes
Nice job, i left you some comments
CC: @CheloChidoone

2024-01-10 16:59 UTC, Mauriciocr207 commented on app/Views/public/equipment.php
> +                <a href="/categoria?categoria=<?= $category['categoryName']; ?>" class="equipment">
Here instead of `$category['categoryName']` must be `$category['categorySlug']`

2024-01-10 16:59 UTC, Mauriciocr207 commented on app/Controllers/CtrlPublicPages.php
> +        $categories    = $categoryModel->join('files', 'files.fileId = categories.categoryIconId')->findAll();
This could be as a function on CategoryModel, instead of make the join here on controller

2024-01-10 16:59 UTC, Mauriciocr207 commented on app/Views/public/equipment.php
> +                    <img src="<?= $category['fileRoute']; ?>" alt="equipment" class="equipment__icon">
Here it is necessary to use all image versions in order to improvement image load on page

2024-01-10 16:59 UTC, Mauriciocr207 commented on app/Views/public/category.php
> +                <img src="/assets/images/imagen-catalogo.png" alt="" class="product__image">
Here the same

2024-01-10 16:59 UTC, Mauriciocr207 commented on app/Controllers/CtrlPublicPages.php
> +        $category      = $categoryModel->join('files', 'files.fileId = categories.categoryImageId')->where('categoryName', $categoryName)->first();
Also, this could be inside the model but it is not necessary because this will be modified on the filter products functionality

2024-01-10 16:59 UTC, CheloChidoone requested changes
Check my comments about the subname validation @FernandoJoachin because you left it required in the validations, also check Mau's comments too

2024-01-10 16:59 UTC, CheloChidoone commented on app/Validation/CategoryValidation.php
> +            'required'   => 'El subnombre de la categoría es obligatorio.',
Subname is not required, you forgot to remove the validation message from here

2024-01-10 16:59 UTC, CheloChidoone commented on app/Validation/CategoryValidation.php
> +        'categorySubname' => 'required|max_length[20]',
Subname is not required, you forgot to remove the validation here

2024-01-10 17:05 UTC, Cristianpan requested changes
Please check the suggestions and make the changes.

CC: @CarlosJCD

2024-01-10 17:09 UTC, CarlosJCD approved these changes
Nice work, check out @Cristianpan 

CC: @Cristianpan

2024-01-12 02:38 UTC, LUGAMAFE approved these changes
Nice Job @FernandoJoachin

2024-01-12 03:42 UTC, CheloChidoone approved these changes

2024-01-12 03:42 UTC, Mauriciocr207 approved these changes

2024-01-12 05:06 UTC, Cristianpan approved these changes

2024-01-12 05:07 UTC, merged