Task/kin 384 improvements on admin panel
loopcrack-org/Kinub pull request #179
Opened 2024-01-08 04:33 UTC by CarlosJCD

## Summary

### Problem

It is needed to do certain improves on the admin panel.

### Solution

Implements the requested improves on table records and validation on resend confirmation email endpoint.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [x] Add sweetalert2 styles on missing pages so that the pop ups messages match with the selected theme of the page

- [x] On files inputs, add size validations according to current design on the public page.

- [x] Add respective titles on the actions buttons of the records tables 

- [x] On the records tables of the private view set the sizes smaller for icons and images
- [ ] 

### Testing

- [x] Check that the filepond delete alerts match with the current color theme of the page.
- [x] Check that the images and icons are now smaller on their respective tables. 
- [x] Check that when an action button is hovered its respective title appears.

2024-01-09 04:38 UTC, LUGAMAFE requested changes

2024-01-09 04:38 UTC, LUGAMAFE commented on app/Controllers/CtrlCategory.php
> +        $fileConfigBuilder->builder('icon')->isSVG()->maxFiles(1)->minFiles(1)->maxSize(5, 'KB')->build();
why only 5 kb? that is too low use 20kb just in case
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/d9c537af-121a-4545-be33-53f193bf600c)

2024-01-09 04:38 UTC, LUGAMAFE commented on app/Views/admin/certificates/Certificates.php
> +                                                <img class="w-50 object-fit-contain" src="<?= $certificate['fileRoute']; ?>" alt="Imagen del certificado " . <?= $certificate['certificateId']; ?> heig
```suggestion
                                                <img class="w-50 object-fit-contain" src="<?= $certificate['fileRoute']; ?>" alt="Imagen del certificado " . <?= $certificate['certificateId']; ?> height="110">
```

2024-01-09 04:38 UTC, LUGAMAFE commented on app/Views/admin/certificates/Certificates.php
> +                                                <a href="#" class="btn btn-danger btn-icon waves-effect waves-light w-100" data-bs-toggle="modal" data-bs-target="#deleteCertificatesModal" data-id=<?=
can we use the same layout that categories table is using for these buttons please
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/bf8125d5-4103-4ee4-9d1d-51a5b3e783ee)

2024-01-09 04:38 UTC, LUGAMAFE commented on app/Views/admin/emails/Emails.php
> +                                                <a href="#" class="btn btn-danger btn-icon waves-effect waves-light w-100" data-bs-toggle="modal" data-bs-target="#deleteEmailsModal" data-id=<?= $emai
same here:
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/e0a8d95a-c7ab-4912-9543-09d9bf70fa38)

2024-01-09 04:38 UTC, LUGAMAFE commented on app/Views/admin/products/Products.php
> +                                                <img class="w-50 object-fit-contain" src="<?= $product['fileRoute']; ?>" alt="<?= 'Imagen del certificado' . $product['productId']; ?>" height="90">
```suggestion
                                                <img class="w-50 object-fit-contain" src="<?= $product['fileRoute']; ?>" alt="<?= 'Imagen del certificado' . $product['productId']; ?>" height="80">
```

2024-01-09 04:38 UTC, LUGAMAFE commented on app/Views/admin/products/Products.php
> +                                                <a href="#" class="btn btn-danger btn-icon waves-effect waves-light w-100" data-bs-toggle="modal" data-bs-target="#deleteProductsModal" data-id=<?= $pr
same here:
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/f5a8136f-25c7-4c1a-97d7-685731f2d9ae)

2024-01-09 04:38 UTC, LUGAMAFE commented on app/Views/admin/users/Users.php
> +                                            <a href="/admin/usuarios/editar/<?= $user['userId']?>" class="btn btn-primary btn-icon waves-effect waves-light flex-grow-1"><i class="ri-edit-2-fill ri-lg
title attr not working

2024-01-09 04:38 UTC, LUGAMAFE commented on app/Views/admin/users/Users.php
> +                                            <button class="btn btn-danger btn-icon waves-effect waves-light flex-grow-1" data-bs-toggle="modal" data-bs-target="#deleteUsersModal" data-id=<?= $user['u
```suggestion
                                            <button class="btn btn-danger btn-icon waves-effect waves-light flex-grow-1" data-bs-toggle="modal" data-bs-target="#deleteUsersModal" data-id="<?= $user['userId']?>" title="Eliminar Usuario"><i class="ri-delete-bin-5-line ri-lg"></i></button>
```

2024-01-10 17:13 UTC, CarlosJCD commented on app/Views/admin/users/Users.php
> +                                            <button class="btn btn-danger btn-icon waves-effect waves-light flex-grow-1" data-bs-toggle="modal" data-bs-target="#deleteUsersModal" data-id=<?= $user['u
Thanks i havent noticed it!, I will add it ASAP

2024-01-10 17:14 UTC, CheloChidoone requested changes
Good Job @CarlosJCD but finish checking the changes Luis requested, you are still missing some of the button layouts he mentioned and also the last change where I left you a comment that it also is still missing

2024-01-10 17:28 UTC, Cristianpan requested changes

2024-01-10 17:28 UTC, Cristianpan commented on app/Controllers/CtrlUser.php
> +            }
We have a constant that represents when a user is not confirmed, replace that magic number for the constant please. 
```suggestion
            if ($userData['confirmed'] !== USER_IS_NOT_CONFIRMED) {
                throw new UserAlreadyConfirmedException('No es posible enviar el correo de confirmación ya que la cuenta ya ha sido confirmada');
            }
```

2024-01-10 17:28 UTC, Cristianpan commented on app/Controllers/CtrlUser.php
> +                'message' => $th->getMessage(),
I think this is not a good idea because the user should not see errors like from the database, for example.

2024-01-12 02:51 UTC, LUGAMAFE requested changes
buttons look wrong @CarlosJCD they need spacing
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/495ed1cc-d632-401a-b794-107d321bd8bb)
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/fd418eb8-752b-4bf2-a8ef-411936f39c0f)

2024-01-12 04:46 UTC, FernandoJoachin reviewed
To solve the space of the buttons you can look at how Pan did it on the users page. All you have to do is add a column-gap to the div that contains the buttons and a flex-growp-1 to the buttons.

2024-01-15 17:07 UTC, CheloChidoone approved these changes
Great Job @CarlosJCD

2024-01-16 00:16 UTC, FernandoJoachin commented on app/Views/admin/certificates/Certificates.php
> +                                                <a href="/admin/certificados/editar/<?= $certificate['certificateId']; ?>" class="btn btn-primary btn-icon waves-effect waves-light mb-2 flex-grow-1"
delete mb-2

2024-01-16 00:16 UTC, FernandoJoachin approved these changes

2024-01-16 02:12 UTC, CarlosMay7 approved these changes

2024-01-16 04:29 UTC, LUGAMAFE approved these changes

2024-01-16 04:32 UTC, LUGAMAFE commented on app/Views/admin/certificates/Certificates.php
> +                                                <a href="/admin/certificados/editar/<?= $certificate['certificateId']; ?>" class="btn btn-primary btn-icon waves-effect waves-light mb-2 flex-grow-1"
use gap-2 in parent element instead of mb-2

2024-01-16 04:33 UTC, LUGAMAFE approved these changes
replace margins with gaps

2024-01-16 04:33 UTC, LUGAMAFE commented on app/Views/admin/emails/Emails.php
> +                                                <a href="/admin/emails/ver/<?= $email['emailId']; ?>" class="btn btn-warning btn-icon waves-effect waves-light mb-2 flex-grow-1" ><i class="mdi mdi-ema
use gap-2 in parent component remove mb-2

2024-01-16 04:33 UTC, LUGAMAFE commented on app/Views/admin/products/Products.php
> +                                                <a href="/admin/productos/editar/<?= $product['productId']; ?>" class="btn btn-primary btn-icon waves-effect waves-light mb-2 flex-grow-1" title="Edita
use gap-2 in parent component remove mb-2

2024-01-16 05:41 UTC, Cristianpan requested changes
Good job! And thanks for making the changes but I consider that this change is also important. Please check that in all the views where the tables are, that in the text elements have a "text-wrap" class, as this helps to prevent that if for example the product name is large, it overflows on small devices like <=320.
![image](https://github.com/loopcrack-org/Kinub/assets/91033040/3784202c-b958-4a89-b3ef-bfc5d1425eb3)

I have seen that this "defect" is in soluciones de medición y en categorías but it would be good that you verify in the other tables.

2024-01-16 07:57 UTC, Cristianpan approved these changes

2024-01-16 17:39 UTC, merged