KIN-188 Gulpfile fix
loopcrack-org/Kinub pull request #19
Opened 2023-08-29 00:49 UTC by Mauriciocr207

## Summary

### Problem

Error when runnning gulp task images related to manage image minification 

### Solution

Change names routes on gulpfile.js to correctly run the correspond gulp task

## Acceptance Criteria

### Requirements checklist

- [ ] Gulp may manage all images and transform to the established formats.

### Testing

- [ ] Choose any image to be managed. Put it into src/img folder and then run on terminar the command "gulp images". You should see that image transformed in all corresponding formats on public/assets/img folder

## Resources
## Demo

2023-08-29 02:06 UTC, CarlosJCD submitted a review, later dismissed

2023-08-29 04:24 UTC, FernandoJoachin submitted a review, later dismissed

2023-08-29 04:38 UTC, Cristianpan approved these changes

2023-08-29 04:45 UTC, FernandoJoachin approved these changes

2023-08-29 04:52 UTC, Oswaldo-Chan approved these changes

2023-08-29 15:48 UTC, CarlosJCD approved these changes

2023-08-29 17:50 UTC, LUGAMAFE requested changes

2023-08-29 17:50 UTC, LUGAMAFE commented on gulpfile.js
> +function pagesJavascript() {
@Mauriciocr207 could you explain in more detail the addition of this in your PR description, this is not part of the images work, right?

2023-08-29 21:38 UTC, Mauriciocr207 commented on gulpfile.js
> +function pagesJavascript() {
During this task, it was noted that there were problems with the javascript file structure that the gulp generated.
However, this was not declared on the description of this pull request.

2023-08-29 23:38 UTC, LUGAMAFE commented on gulpfile.js
> +function pagesJavascript() {
yeap we need to update de description of the PR at least @Mauriciocr207

2023-08-30 03:55 UTC, LUGAMAFE approved these changes

2023-08-30 05:07 UTC, merged