KIN-296 integration with the admin panel product page frontend
loopcrack-org/Kinub pull request #191
Opened 2024-01-17 03:37 UTC by Cristianpan

## Summary

### Problem

The user must be able to see the specific product information with all its data.

### Solution

Integrate the product page with the db to show the product data. 

## Acceptance Criteria

### Requirements checklist
The Product info of the database must be shown on the product page:
   - [x] The detailed info
   - [x] The product images and videos which routes were stored
   - [x] The Product tags, category tags, name and model number
   - [x] The product description
   - [x] The product technical info description
   - [x] The product demo video which route was stored
- [x] The links of the download section must download the files which routes were stored
- [x] If the product doesn't have files to download, the download area should be hidden.
- [x] The tags when clicked must redirect to the product catalog page with their respective filter activated

### Testing
To test the product page, you should access the route with the product id and the product name, for example: `http://localhost:8080/producto/21/Producto%201`
- [x] Verify that product data is displayed correctly
- [x] Enter the path with a non-existent name or id and you should see a 404 error page.
- [x] Verify that if the product doesn't have files to download, the download area is hidden.

## Resources
## Demo

2024-01-17 17:15 UTC, CarlosJCD requested changes
Nice work, just check out the couple of comments that I left you

CC: @CheloChidoone

2024-01-17 17:16 UTC, CheloChidoone requested changes
Good Job @Cristianpan but change those two details that Carlos explained

2024-01-17 21:52 UTC, CarlosJCD approved these changes
Thanks for the changes!

2024-01-18 01:06 UTC, CheloChidoone approved these changes

2024-01-18 01:27 UTC, FernandoJoachin approved these changes

2024-01-18 04:05 UTC, CarlosMay7 approved these changes

2024-01-18 04:11 UTC, merged