KIN-396 incorrect error message on login
loopcrack-org/Kinub pull request #194
Opened 2024-01-17 09:47 UTC by FernandoJoachin

## Summary

### Problem

When a non-existent email is entered, the unconfirmed account alert is displayed

### Solution

Modify validations so they display properly.

## Acceptance Criteria

### Requirements checklist

- [ ] Do not show the unconfirmed account alert when a non-existent account is entered.
- [ ] Show an appropriate alert for when a non-existent account is entered.

### Testing

- [ ] Enter a non-existent email and verify that the correct alert is displayed
- [ ] Enter an email that exists but is not confirmed and verify that the correct alert is displayed.
- [ ] Enter an email that exists, that is confirmed but your password is incorrect and verify that the correct alert is displayed

2024-01-17 22:03 UTC, CarlosJCD requested changes

2024-01-17 22:41 UTC, CheloChidoone commented on app/Validation/LoginValidation.php
> +    protected $invalid_account_message     = 'Correo electrónico no válido. Por favor, verifica el email proporcionado.';
You are right @CarlosJCD it should be the same message just saying that either the password or email was invalid and not specifying, make this change please @FernandoJoachin

2024-01-18 04:29 UTC, LUGAMAFE reviewed
Same comment that @CarlosJCD

2024-01-18 04:29 UTC, LUGAMAFE commented on app/Validation/LoginValidation.php
> +    protected $invalid_account_message     = 'Correo electrónico no válido. Por favor, verifica el email proporcionado.';
Yes, that's right, we shouldn't give the user hints about what is wrong.

2024-01-18 20:13 UTC, CarlosJCD approved these changes
Thanks for the changes!

2024-01-19 04:59 UTC, Mauriciocr207 approved these changes

2024-01-19 10:41 UTC, merged