KIN-400 Resize Category and Product image to work for metatags
loopcrack-org/Kinub pull request #198
Opened 2024-01-19 17:49 UTC by CheloChidoone

## Summary

### Problem

The Images of the products and categories that are used dynamically as meta image for the meta tags need to be resized to fit into the expected size of open graph for the metatags

### Solution

Added an image generator function for use for categories and products which generates and saves the metaimage if it does not exist yet

## Acceptance Criteria

### Requirements checklist

- [ ] Meta image generates correctly for any category and gets saved in the same folder where the current category image is
- [ ] Meta image generates correctly for any product and gets saved in the same folder where the current product main image is

### Testing

When loading a catalog page or a product page this function should execute and you can check that a new image of size around 1200x630 is generated and added to the folder where the main image for the category or product is

## Resources

- None

## Demo

This is how sharing looks now with these changes:

![image](https://github.com/loopcrack-org/Kinub/assets/38699927/b9f823b7-68b5-4860-874f-9c07a73c8a47)

This is just the category example, I didn't save the product example but it also works, I already tested on server

2024-01-19 19:43 UTC, CarlosJCD approved these changes

2024-01-20 05:33 UTC, LUGAMAFE requested changes
Porfavor checa los comments hay que refactorizar el codigo chelo. Aun lo he probado

2024-01-20 05:33 UTC, LUGAMAFE commented on app/Utils/UrlGenerator.php
> +            if ($originalWidth < $ogImageWidth && $originalHeight < $ogImageHeight) {
No deberia ser un or esto?
```suggestion
            if ($originalWidth < $ogImageWidth || $originalHeight < $ogImageHeight) {
```

2024-01-20 05:33 UTC, LUGAMAFE commented on app/Utils/UrlGenerator.php
> +
Mueve esto a su propia clase porfas y refactoriza el codigo
```suggestion
class OGImageGenerator
{
    const OG_IMAGE_WIDTH = 1200;
    const OG_IMAGE_HEIGHT = 630;

    public static function generateOgImage($originalImageRoute)
    {
        $originalImagePath = base_url() . ltrim($originalImageRoute, '/');
        $pathInfo = pathinfo($originalImageRoute);
        $newFilePath = $pathInfo['dirname'] . '/' . $pathInfo['filename'] . '-metaimage.png';

        if (file_exists($newFilePath)) {
            return base_url() . $newFilePath;
        }

        $originalImage = self::createImageFromPath($originalImagePath);
        if (!$originalImage) {
            return null;
        }

        list($newWidth, $newHeight, $isSmaller) = self::calculateNewDimensions(
            imagesx($originalImage),
            imagesy($originalImage)
        );

        $newImage = self::createNewImage($originalImage, $newWidth, $newHeight, $isSmaller);
        imagepng($newImage, $newFilePath);

        imagedestroy($originalImage);
        imagedestroy($newImage);

        return base_url() . $newFilePath;
    }

    private static function createImageFromPath($path)
    {
        if (str_ends_with($path, '.png')) {
            return imagecreatefrompng($path);
        } elseif (str_ends_with($path, '.jpeg') || str_ends_with($path, '.jpg')) {
            return imagecreatefromjpeg($path);
        }
        return null;
    }

    private static function calculateNewDimensions($originalWidth, $originalHeight)
    {
        if ($originalWidth < self::OG_IMAGE_WIDTH && $originalHeight < self::OG_IMAGE_HEIGHT) {
            return [$originalWidth, $originalHeight, true];
        } else {
            $aspectRatio = $originalWidth / $originalHeight;
            if (self::OG_IMAGE_WIDTH / self::OG_IMAGE_HEIGHT > $aspectRatio) {
                return [self::OG_IMAGE_HEIGHT * $aspectRatio, self::OG_IMAGE_HEIGHT, false];
            } else {
                return [self::OG_IMAGE_WIDTH, self::OG_IMAGE_WIDTH / $aspectRatio, false];
            }
        }
    }

    private static function createNewImage($originalImage, $newWidth, $newHeight, $isSmaller)
    {
        $newImage = imagecreatetruecolor(self::OG_IMAGE_WIDTH, self::OG_IMAGE_HEIGHT);
        $transparency = imagecolorallocatealpha($newImage, 0, 0, 0, 127);
        imagefill($newImage, 0, 0, $transparency);
        imagesavealpha($newImage, true);

        if ($isSmaller) {
            $paddingX = (self::OG_IMAGE_WIDTH - $newWidth) / 2;
            $paddingY = (self::OG_IMAGE_HEIGHT - $newHeight) / 2;
            imagecopy($newImage, $originalImage, $paddingX, $paddingY, 0, 0, $newWidth, $newHeight);
        } else {
            imagecopyresampled($newImage, $originalImage, (self::OG_IMAGE_WIDTH - $newWidth) / 2, (self::OG_IMAGE_HEIGHT - $newHeight) / 2, 0, 0, $newWidth, $newHeight, imagesx($originalImage), imagesy($originalImage));
        }

        return $newImage;
    }
}

```

2024-01-20 05:35 UTC, CheloChidoone commented on app/Utils/UrlGenerator.php
> +            if ($originalWidth < $ogImageWidth && $originalHeight < $ogImageHeight) {
No because if it is bigger on width or height it needs to adapt differently than if the image is smaller in both width and height

2024-01-20 06:33 UTC, CheloChidoone commented on app/Utils/UrlGenerator.php
> +
@LUGAMAFE Done

2024-01-20 13:56 UTC, LUGAMAFE approved these changes

2024-01-20 13:57 UTC, merged