KIN-399 Change product image carousel
loopcrack-org/Kinub pull request #200
Opened 2024-01-19 19:43 UTC by Cristianpan

## Summary

### Problem

What problem does this pull request aim to solve? Include relevant motivation and context.

### Solution

How does this pull request solve that problem? List any dependencies that are required for this change.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] Requirement A
- [ ] Requirement B

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Test A
- [ ] Test B

## Resources

- [Technical Design Document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/$END_POINT)

## Demo

If applicable, include screenshots and/or screen recordings associated with your solution

2024-01-19 19:57 UTC, CarlosJCD approved these changes
Nice job

2024-01-20 00:11 UTC, CheloChidoone requested changes
@Cristianpan It looks good visually but it has a lot of bugs at least when I tested, 

- I created a product with 5 images (1 main image and 4 images) and instead of showing me just those 5 it showed me 6 images (I confirmed in my DB my product should have only 5 images)
- If the product has a video when hovering to it the video shakes like it's trying to resizes or appear and disappear or something
- When opening the gallery it is showing double the images there should be, meaning it's duplicating all of them

2024-01-20 00:14 UTC, CheloChidoone commented on app/Views/public/product.php
> +}
@Cristianpan Is this foreach duplicated?, this might be causing the images to duplicate

2024-01-20 00:14 UTC, CheloChidoone commented on app/Views/public/product.php
>  }
This seems like the same foreach but a second time

2024-01-20 02:04 UTC, CarlosJCD commented
> @Cristianpan It looks good visually but it has a lot of bugs at least when I tested,
> 
> * I created a product with 5 images (1 main image and 4 images) and instead of showing me just those 5 it showed me 6 images (I confirmed in my DB my product should have only 5 images)
> * If the product has a video when hovering to it the video shakes like it's trying to resizes or appear and disappear or something
> * When opening the gallery it is showing double the images there should be, meaning it's duplicating all of them

@Cristianpan Heres a video of the second point


https://github.com/loopcrack-org/Kinub/assets/89323622/c6fb1bfc-4dc3-45dc-bd9e-59b07379e262

2024-01-20 04:54 UTC, CheloChidoone commented
Good Job @Cristianpan images aren't repeated anymore, and the video is much better but still when first clicking on the video for it to play the resizing thing happens again, do you think it can be fixed?

2024-01-20 07:44 UTC, CheloChidoone approved these changes

2024-01-20 08:00 UTC, LUGAMAFE approved these changes

2024-01-20 08:00 UTC, merged