KIN-400 Fix Meta Image Generator
loopcrack-org/Kinub pull request #204
Opened 2024-01-22 23:28 UTC by CheloChidoone

## Summary

### Problem

The Meta Image Generator does not work properly for categories and may raise a warning for some images like the new category jumbotron image

### Solution

Fix the Meta Image Generator integration for the catalog pages and prevent warnings during the process

## Acceptance Criteria

### Requirements checklist

- [ ] Meta Image generates correctly when a main category is selected in the catalog
- [ ] Meta Image generator does not show warnings when generating

### Testing

To test you need to have a category with properly uploaded images for it
- [ ] Select the category for your test from the `equipos` page, check that on the same folder where the jumbotron image for the category was created the new meta image was generated successfully

## Resources

None

## Demo

None

2024-01-24 05:19 UTC, CarlosJCD requested changes
For some reason the jumbotron when there is no filter selected does not load. I am not sure if this is an error of my local environment so please let me know if it is.

<img width="1496" alt="Screenshot 2024-01-23 at 23 19 22" src="https://github.com/loopcrack-org/Kinub/assets/89323622/84c4173d-b2a5-4105-8996-c649824a8759">

2024-01-24 05:19 UTC, CarlosJCD commented on app/Utils/OgImageGenerator.php
> +use Exception;
please remove this unused import
```suggestion
```

2024-01-24 05:29 UTC, CheloChidoone commented on app/Utils/OgImageGenerator.php
> +use Exception;
I removed the import @CarlosJCD thanks for the observation

2024-01-24 05:31 UTC, CheloChidoone commented on app/Utils/OgImageGenerator.php
> +use Exception;
About the jumbotron issue I hadn't seen it because it worked fine on the server but now I noticed that when there is no category filter selected the jumbotron tries to load the image from this path and we don't have this image on this path on our locals so we see the issue, `/uploads/4972868bb3df514edd5939b872e1d7a5/Bannersproductos-Recuperado.psdMesa-de-trabajo-1.png`, why did you choose to do it this way @Mauriciocr207 ??

2024-01-24 05:32 UTC, Cristianpan commented on app/Utils/OgImageGenerator.php
> +use Exception;
I think the error is because the image wasn't uploaded correctly in uploads when the filter ticket was uploaded. Please confirm if this is the case or not @Mauriciocr207, @CarlosMay7 , @Oswaldo-Chan

2024-01-24 05:49 UTC, Mauriciocr207 commented on app/Utils/OgImageGenerator.php
> +use Exception;
@LUGAMAFE told me that I get that image to show the jumbotron image in case there is not filter applied. In order the image is loaded now on server, I just choose the path on production, because tha image was ready loaded there.

2024-01-24 06:03 UTC, Mauriciocr207 commented on app/Utils/OgImageGenerator.php
> +use Exception;
I think that image could be into the image folder instead of uploads folder.

2024-01-24 06:14 UTC, Mauriciocr207 approved these changes

2024-01-24 06:31 UTC, CarlosMay7 approved these changes

2024-01-24 16:29 UTC, FernandoJoachin commented on app/Utils/OgImageGenerator.php
> +use Exception;
And was what Carlos Calderón mentioned solved? Because what he mentioned keeps happening to me

2024-01-24 16:36 UTC, CheloChidoone commented on app/Utils/OgImageGenerator.php
> +use Exception;
@FernandoJoachin we don't have that image in our locals because they took the path from the uploads on the production server, I'll add it to the image folder like Mau said instead of uploads and that should fix it

2024-01-24 17:09 UTC, Oswaldo-Chan approved these changes

2024-01-26 02:49 UTC, CarlosJCD approved these changes

2024-01-26 04:11 UTC, LUGAMAFE approved these changes
Nice

2024-01-26 04:11 UTC, LUGAMAFE commented on app/Controllers/CtrlPublicPages.php
> +            $metaDescription = 'Explora los mejores productos de '.$principalCategory['categoryName'];
```suggestion
            $metaDescription = "Explora los mejores productos de {$principalCategory['categoryName']}";
```

2024-01-26 13:15 UTC, merged