KIN-405 add date column on emails table of the admin panel
loopcrack-org/Kinub pull request #205
Opened 2024-01-23 09:15 UTC by FernandoJoachin

## Summary

### Problem

Data for emails sent from the contact form, support form, and product form should be displayed with their sent date.

### Solution

Display the sent date of the emails 

## Acceptance Criteria

### Requirements checklist

- [ ] The sent date must be displayed on the emails table.

### Testing

- [ ] Complete a form and then navigate to admin/emails. There, the system should display the sent email along with its sending date.

2024-01-24 05:22 UTC, CarlosJCD approved these changes

2024-01-24 06:13 UTC, Cristianpan requested changes

2024-01-24 06:13 UTC, Cristianpan commented on app/Views/admin/emails/Emails.php
> +                                                <p class="text-wrap"><?= $email['createdAt']; ?></p>
I think you should format the date better as "day/month/year"
```suggestion
  <p class="text-wrap"><?= date('j/m/Y', strtotime($email['createdAt']))?></p>
```

2024-01-24 06:13 UTC, Cristianpan commented on app/Views/admin/emails/Emails.php
> +                                            <div class="text-<?= ($email['emailTypeId'] === '1') ? 'warning-emphasis' : (($email['emailTypeId'] === '2') ? 'info-emphasis' : 'success-emphasis'); ?> te
I see that you are using type identifiers and I think you should replace those magic numbers with constant values to improve the readability of the code. I remember that in the controller where we send the emails, we have those constants but they are of the class. Since they would now be used in more than one place, maybe it would be good to move them to App/Config/Constant.php. But I don't know what @LUGAMAFE , @CheloChidoone @Mauriciocr207, @CarlosJCD think

2024-01-24 06:31 UTC, Mauriciocr207 commented on app/Views/admin/emails/Emails.php
> +                                                <p class="text-wrap"><?= $email['createdAt']; ?></p>
Maybe for this, as you have the hour, you can set the date on that format and the hour like this:
```suggestion
<p class="text-wrap"><?= date('j/m/Y, g:i a', strtotime($email['createdAt']))?></p>
```

In case you want more date format recomendations, you have thie reference @FernandoJoachin: [date on php](https://www.php.net/manual/es/function.date.php)

2024-01-24 06:53 UTC, CarlosJCD commented on app/Views/admin/emails/Emails.php
> +                                            <div class="text-<?= ($email['emailTypeId'] === '1') ? 'warning-emphasis' : (($email['emailTypeId'] === '2') ? 'info-emphasis' : 'success-emphasis'); ?> te
I missed that out.! I agree, it is important to avoid magic numbers/strings.

2024-01-24 06:57 UTC, Mauriciocr207 commented on app/Views/admin/emails/Emails.php
> +                                            <div class="text-<?= ($email['emailTypeId'] === '1') ? 'warning-emphasis' : (($email['emailTypeId'] === '2') ? 'info-emphasis' : 'success-emphasis'); ?> te
I agree, but also think we could remove the if-else operation with the ternary operator and change by
```php
<?php foreach ($emails as $email) { ?>
<?php
switch ($email['emailTypeId']) {
    case CONTACT_EMAIL_ID:
        $emailTypeEmphasis = 'text-warning-emphasis';
        $emailTypeText     = 'Contacto';
        break;

    case SUPPORT_EMAIL_ID:
        $emailTypeEmphasis = 'text-info-emphasis';
        $emailTypeText     = 'Soporte técnico';
        break;

    case PRODUCT_EMAIL_ID:
        $emailTypeEmphasis = 'text-success-emphasis';
        $emailTypeText     = 'Información de producto';

        break;
}
?>
<tr>
    <!-- Rest of code -->
    ...
    <td>
        <div class="<?= $emailTypeEmphasis?> text-wrap">
            <?= $emailTypeText?>
        </div>
    </td>
```
Or something similar. Also in this way you don´t need to evaluate the emailTypeId twice, just once.

2024-01-24 15:04 UTC, Cristianpan commented on app/Views/admin/emails/Emails.php
> +                                            <div class="text-<?= ($email['emailTypeId'] === '1') ? 'warning-emphasis' : (($email['emailTypeId'] === '2') ? 'info-emphasis' : 'success-emphasis'); ?> te
Hmmm maybe would be better to create an associative array instead of a switch but I think that the text of the email type should be taken directly from the database that is already being stored there.

2024-01-24 16:23 UTC, CheloChidoone commented on app/Views/admin/emails/Emails.php
> +                                            <div class="text-<?= ($email['emailTypeId'] === '1') ? 'warning-emphasis' : (($email['emailTypeId'] === '2') ? 'info-emphasis' : 'success-emphasis'); ?> te
@Mauriciocr207 @Cristianpan I think the if-else operation is fine like we have it but you do need to avoid the magic numbers @FernandoJoachin, if we used the email type id numbers as constants in multiple places then we can move those constants to `App/Config/Constant.php` like Cristian said and used them from there, make those changes and this should be good.

2024-01-24 16:33 UTC, CheloChidoone approved these changes
Good Job @FernandoJoachin, just finish the change Cristian requested regarding the magic numbers

2024-01-25 15:35 UTC, Mauriciocr207 approved these changes
Good job! Just make the requested changes

2024-01-26 03:22 UTC, Cristianpan commented
Thanks for changing the magic numbers to constants, but I think you should also add those constants in `app/Controllers/CtrlEmail` and remove the class constants. I know it doesn't pertain to the ticket but I think it would be nice if you did that since it's a small change.

2024-01-26 04:19 UTC, LUGAMAFE approved these changes
Good Job @FernandoJoachin

2024-01-26 04:19 UTC, LUGAMAFE commented on app/Views/admin/emails/Emails.php
>                                              </div>
```suggestion
                                            <?php
                                                switch ($email['emailTypeId']) {
                                                    case EMAIL_CONTACT_FORM:
                                                        $class = 'warning-emphasis';
                                                        $text = 'Contacto';
                                                        break;
                                                    case EMAIL_TECHNICAL_SUPPORT_FORM:
                                                        $class = 'info-emphasis';
                                                        $text = 'Soporte técnico';
                                                        break;
                                                    default:
                                                        $class = 'success-emphasis';
                                                        $text = 'Información producto';
                                                        break;
                                                }
                                            ?>

                                            <div class="text-<?= $class; ?> text-wrap">
                                                <?= $text; ?>
                                            </div>
```

2024-01-26 04:20 UTC, CarlosMay7 approved these changes

2024-01-27 23:04 UTC, LUGAMAFE commented
@Cristianpan can you check this PR please

2024-01-27 23:12 UTC, Cristianpan approved these changes

2024-01-29 00:22 UTC, merged