KIN-410 add empty messages on public pages
loopcrack-org/Kinub pull request #212
Opened 2024-01-24 09:13 UTC by FernandoJoachin

## Summary

### Problem

There can be cases where there are no records of certain kind of entity

### Solution

Implement empty messages when there are no records on equipments page or certificates page.

## Acceptance Criteria

### Requirements checklist

- [ ] There must be a message indicating that there are no type of equipment registered on the equipments page when there are no categories records.
- [ ] There must be a message indicating that there are no certificates registered on the certificates page when there are no certificates records.

### Testing

- [ ] Check that a message is displayed when there are no items on the certificates or equipment page.

2024-01-24 16:29 UTC, CarlosJCD approved these changes

2024-01-26 04:56 UTC, LUGAMAFE requested changes
@FernandoJoachin please always add a demo!

2024-01-26 04:57 UTC, LUGAMAFE requested changes

2024-01-26 04:57 UTC, LUGAMAFE commented on app/Views/public/equipment.php
> +                <!--Add more video formats-->
```suggestion
```

2024-01-26 04:57 UTC, LUGAMAFE commented on app/Views/public/equipment.php
> +                    </a> <!--equipment-->
```suggestion
                    </a>
```

2024-01-26 04:58 UTC, CarlosMay7 approved these changes

2024-01-30 04:29 UTC, LUGAMAFE approved these changes

2024-01-30 14:46 UTC, merged