KIN-86 Sending the email of the technical support form
loopcrack-org/Kinub pull request #27
Opened 2023-08-31 04:51 UTC by FernandoJoachin

The implementation of sending the mail was made in the sendSupportEmail method

## Summary

### Problem

The project needs the information collected through the support form to be sent to the company email address so that you can be notified as soon as possible.

### Solution

The functionality of sending emails for the technical support form was implemented. In this way the company will be notified of the problems presented by customers.

## Acceptance Criteria

### Requirements checklist

- [ ] You must send an email to the company's email address with the information collected from the form.

### Testing

- [ ] Make a post in postman at the url: http://kinub.cm/email/soporte
[![imagen-2023-08-30-222926899.png](https://i.postimg.cc/VNKt8dx6/imagen-2023-08-30-222926899.png)](https://postimg.cc/xkb8GTTD)

## Demo

[![imagen-2023-08-30-223012259.png](https://i.postimg.cc/SQ2TNMmH/imagen-2023-08-30-223012259.png)](https://postimg.cc/nMxY3Mj1)

[![imagen-2023-08-30-223037561.png](https://i.postimg.cc/Pq5KGL63/imagen-2023-08-30-223037561.png)](https://postimg.cc/VJ2XnNPn)

2023-08-31 15:14 UTC, LUGAMAFE requested changes

2023-08-31 15:14 UTC, LUGAMAFE commented on app/Controllers/CtrlEmail.php
> +        $subject = "Mensaje del formulario de soporte técnico";
@FernandoJoachin La responsabilidad del controlador `app\Controllers\CtrlEmail.php` empieza a ser muy variada, si ya tienes el controlador base para los emails con el metodo `sendEmail(...)` tal vez ahora podrias crear otro controlador para solo los emails de Support que tenga sus propios metodos como este de `sendSupportEmail()` u otra manera seria que `CtrlEmail.php` podria ser una clase estatica. Lo que si es que este controlador no tiene una responsabilidad unica y hay que refactorizar este codigo.

2023-09-01 23:13 UTC, CheloChidoone reviewed
@FernandoJoachin Parecen estar bien tus cambios pero me quedo la duda de si se resolvio lo de la refactorizacion que te pidio Luis?, Lo pregunto porque en tus cambios no veo que hayas creado otro controlador o clase estática como dijo Luis, eso sigue en progreso aun?

2023-09-02 01:56 UTC, FernandoJoachin commented
> @FernandoJoachin Parecen estar bien tus cambios pero me quedo la duda de si se resolvio lo de la refactorizacion que te pidio Luis?, Lo pregunto porque en tus cambios no veo que hayas creado otro controlador o clase estática como dijo Luis, eso sigue en progreso aun?

2023-09-02 02:10 UTC, CheloChidoone approved these changes
Ya vi que se hizo la refactorizacion en otro PR, gracias.

2023-09-02 14:15 UTC, Mauriciocr207 approved these changes

2023-09-02 15:52 UTC, Cristianpan approved these changes

2023-09-02 16:23 UTC, Mauriciocr207 approved these changes

2023-09-02 17:49 UTC, LUGAMAFE approved these changes

2023-09-02 18:08 UTC, Oswaldo-Chan approved these changes

2023-09-02 19:05 UTC, merged