KIN-179 added company video section
loopcrack-org/Kinub pull request #31
Opened 2023-09-01 10:53 UTC by Oswaldo-Chan

## Summary

### Problem

The homepage should feature a representative company video to provide more information about it.

### Solution

A section has been implemented to add the company video.

## Acceptance Criteria

### Requirements checklist

- [x] It must be responsive
- [x] Must be able to reproduce
- [x] The recommendations of other videos should not appear in the iframe

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [x] Use browser development tools to simulate different screen sizes and test the responsive design.
- [x] Test playback in various web browsers.
- [x] Verify video controls functionality.

## Resources

## Demo
![demo-1](https://github.com/loopcrack-org/Kinub/assets/92545103/5be85808-e643-4dc7-a51f-382c7136357b)
![demo-2](https://github.com/loopcrack-org/Kinub/assets/92545103/473d6ffb-5434-43e7-bb2d-57c8c5562771)

2023-09-01 15:29 UTC, CarlosJCD reviewed
Hey, I have a couple of issues with the video:
- It does not cover all the designated space.
- The video player does not allow me to fast forward or rewind the video.
Video of the above: [https://drive.google.com/file/d/1vX5jtOJ6-AYOL7w05sQJ-RD_M6XHFGSH/view?usp=sharing](https://drive.google.com/file/d/1vX5jtOJ6-AYOL7w05sQJ-RD_M6XHFGSH/view?usp=sharing)  


The reason I put this as a comment its because I don't know if it's a problem in how I run the project, a problem with my browser, or if I'm overlooking something. I would like to know if anyone else has this problem.

I run the project with php spark
My google chrome version: 116.0.5845.96

2023-09-01 15:58 UTC, Oswaldo-Chan commented
I made the changes requested by @LUGAMAFE and installed a new dependency, so we need to run 'npm install' again

2023-09-02 18:09 UTC, LUGAMAFE requested changes

2023-09-02 18:19 UTC, Oswaldo-Chan commented on app/Views/public/index.php
>  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
Hola, de hecho aún no he modificado el pr ya que parece haber un error con el htaccess y no detecta el script y los estilos de plyr en la en la que lo puse, ayer logré usar plyr con imports pero con ayuda de webpack, está bien usarlo de esa forma? o mejor solo subo los archivos que me serviran en la carpeta de libs

2023-09-05 11:01 UTC, closed without merging