KIN-111 Reset password form logic
loopcrack-org/Kinub pull request #33
Opened 2023-09-01 17:32 UTC by Cristianpan

## Summary

### Problem
A user must be able to request a password reset through their registration email.

### Solution
The request was handled through the email controller, where business validations are used to send the email with the password reset information to an existing user.

## Acceptance Criteria

### Requirements checklist

- [x] It must validate the form that the email input is not empty
- [x] It must validate that the email obtained from the for its indeed registered on the database
- [x] In case its passes all the validations, it must send an email to the account given with a url to change the password.
- [x] In case that it does not passes all the validations, it must return the errors generated to the view of the form.
- [x] In case the email belongs to the super admin, it should not send the email and should return a message to the view

### Testing
To test this feature, run UserSeeder in the terminal using: `php spark db:seed UserSeeder`.

- [ ] Enter a random email and you should see the error message "No existe algun usuario con el email ingresado"
- [ ] Enter the email "admin@admin" and you should see an error message like "No cuenta con permisos para restablecer su contraseña, por favor contacte con los desarrolladores"
- [ ] Enter the email "nkutch@gmail.com" and you should see a message like "Verifique su bandeja de entrada para poder restablecer su contraseña" and check if you received the email

## Resources

## Demo
[KIN-113 Reset password form logic](https://youtu.be/5G-LiRxJzeQ)

2023-09-01 23:24 UTC, CheloChidoone requested changes
@Cristianpan creo que aquí aplica el mismo comment que Luis hizo en el PR del ticket KIN-86, La responsabilidad del controlador `app\Controllers\CtrlEmail.php` empieza a ser muy variada, hay que intentar refactorizarla, quiza sea mejor tener un controlador para cada tipo de email como los de support, contacto y los relacionados con registro y login como este de reset password.

2023-09-02 02:11 UTC, CheloChidoone approved these changes
Ya vi que si se hizo la refactorizacion en otro PR anterior, gracias.

2023-09-02 04:31 UTC, FernandoJoachin approved these changes

2023-09-02 14:13 UTC, Mauriciocr207 approved these changes

2023-09-02 18:09 UTC, Oswaldo-Chan approved these changes

2023-09-02 18:10 UTC, LUGAMAFE approved these changes

2023-09-02 18:14 UTC, merged