KIN-187 Change Password Logic
loopcrack-org/Kinub pull request #35
Opened 2023-09-01 22:59 UTC by Mauriciocr207

## Summary

### Problem

Users need a form where they can change their password if they need it.

### Solution

Add a form with fields that allow users create a new password.

## Acceptance Criteria

### Requirements checklist

- [x] It must be responsive
- [x] The form must validate that the fields aren't empty
- [x] The form must validate that the new password and confirmation of the password match
- [x] The form must validate that the new password has a minimum length of 8 character
- [x] The new password must be hashed before stored on the database, not the plain password.

### Testing
Method 1:
- [x] Before using the logic added, you need to create some users with UserSeeder
`php spark db:seed UserSeeder`
- [x] Go to route `/login/password/reset/FAS12AQajqa`, the string "FAS12AQajqa" indicates a fake token provided when the user request a password change. By default when you create a user with UserSeeder, this is the token created.

Method 2:
- [x] Also, if you have created some users, you can generate some tokens using the reset password page from `/login/password/reset`, where you can enter some email stored on your local database and request a change password.
- [x] Then, you can enter a new password to verify the functionality of this feature.

2023-09-01 23:31 UTC, CheloChidoone requested changes
@Mauriciocr207 entiendo que esto depende de lo que hizo Cristian en su PR tambien porque veo que tienes parte de los mismos cambios en CtrlEmail.php, entonces te dejo el mismo comentario que le deje, creo que aquí aplica el mismo comment que Luis hizo en el PR del ticket KIN-86, La responsabilidad del controlador `app\Controllers\CtrlEmail.php` empieza a ser muy variada, hay que intentar refactorizarla, quiza sea mejor tener un controlador para cada tipo de email como los de support, contacto y los relacionados con registro y login como este de reset password.

2023-09-02 02:16 UTC, CheloChidoone commented on app/Validation/LoginValidation.php
> +        // var_dump($password);
Trata de no dejar comments innecesarios @Mauriciocr207 o se empezara a ensuciar el código si de repente hay muchos comments así.

2023-09-02 13:59 UTC, Mauriciocr207 commented on app/Validation/LoginValidation.php
> +        // var_dump($password);
He quitado los comments @CheloChidoone

2023-09-02 15:13 UTC, Cristianpan requested changes

2023-09-02 15:13 UTC, Cristianpan commented on app/Controllers/CtrlLogin.php
> +        return redirect()->back()->with("response", $response);
Please, change the redirect to `login/password/reset` because this redirect may cause logical errors because, in case of success, the token is removed from the registers, so it shouldn't redirect to a path that would no longer be valid.

2023-09-02 17:22 UTC, CheloChidoone approved these changes
Gracias por hacer las correcciones.

2023-09-02 18:07 UTC, Cristianpan approved these changes

2023-09-02 18:10 UTC, Oswaldo-Chan submitted a review, later dismissed

2023-09-02 18:27 UTC, LUGAMAFE commented
@Mauriciocr207 me gustaria hacer una llamada en la tarde ya que tengo algunas preguntas

2023-09-02 19:32 UTC, Cristianpan approved these changes

2023-09-04 21:56 UTC, CarlosJCD approved these changes

2023-09-04 23:23 UTC, CheloChidoone approved these changes

2023-09-05 04:49 UTC, FernandoJoachin approved these changes

2023-09-05 15:02 UTC, merged