Feature/kin 75/navigation bar public view front end
loopcrack-org/Kinub pull request #36
Opened 2023-09-02 05:56 UTC by CarlosMay7

## Summary

### Problem

The project needs a way to reach the different pages of the site

### Solution

Create a navigation bar that contains the names of the different pages of the site and redirects the user to each one.

## Acceptance Criteria

### Requirements checklist

- [ ]  It must be displayed on each public page of the website.

- [ ] It must include the company logo, which when clicked on it redirects to the main page of the site.

- [ ]  The navigation bar should include labeled links to access the following public pages: Equipment, Technical Support, Certificates, and Contact.

- [ ]  The "Contact" link should redirect the user to the home page and be automatically positioned in the contact form.

- [ ]  The appearance of the navigation bar must be responsive.

### Testing

- [ ] Tested the redirection of the logo and the contact link

## Resources

## Demo

If applicable, include screenshots and/or screen recordings associated with your solution

https://github.com/loopcrack-org/Kinub/assets/97546829/d6a773d4-2122-4d3f-885d-23a664c5586b

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/36114822-e800-4326-be0b-8dddc4ead9c6)

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/a22a2d3b-6150-4160-a09a-b350f04b8a50)

2023-09-02 05:59 UTC, CarlosMay7 commented
The logo is unchecked because the question arose if we have to make the logo according to the mockups or they will send us an image of it

2023-09-02 16:59 UTC, Mauriciocr207 approved these changes

2023-09-02 18:11 UTC, Oswaldo-Chan approved these changes

2023-09-02 18:36 UTC, LUGAMAFE requested changes
@CarlosMay7 can we reduce the height of the header to only 60px instead of 80px, other thing that is missing is that the header should be fixed and follow you all along the page, also for the moment it is ok to omit the logo, or put any other logo as an example ;)

2023-09-08 07:48 UTC, FernandoJoachin reviewed
Encontré una interacción rara con el botón de la navegación. Lo que sucede es que si tengo la navegación en formato de celular, luego le pico al botón para desplegar la navegación, después redimensiono la ventana a un formato de tablet o laptop, y regreso al formato de celular, el botón hace la acción contraria, es decir, la X despliega la navegación y las 3 rayitas quitan la navegación.

2023-09-08 16:46 UTC, Cristianpan approved these changes

2023-09-08 17:52 UTC, CarlosJCD approved these changes

2023-09-08 19:25 UTC, LUGAMAFE requested changes
@CarlosMay7 @Oswaldo-Chan the instruction was that on desktop still have a height of 80px and on mobile and tablet 60px. likewise in galaxy fold resposive design is incorrect. If I'm honest the white shadow that comes out of the mobile view seems ugly and unnecessary. I think we can lower the intensity of the navbar shadow in the desktop view. Other than that good job.

2023-09-08 19:25 UTC, LUGAMAFE commented on src/sass/public/UI/header/_sidebar.scss
> +        z-index: 2;
Could you add please:
```suggestion
        z-index: 2;
        backdrop-filter: blur(3px);
```

2023-09-08 19:25 UTC, LUGAMAFE commented on src/sass/public/UI/header/_header-mobile.scss
> +    box-shadow: 0px 10px 15px 0px v.$gray;
```suggestion
```
remove this line

2023-09-08 19:25 UTC, LUGAMAFE commented on src/sass/public/UI/header/_sidebar.scss
> +        background-color: rgb(0 0 0 / 0.90);
```suggestion
        padding: 2rem; // Dont use excesive padding
        opacity: 1;
        height: 100%;
        width: 100%;
        position: fixed;
        top: 60px; // create a sass or css variable to save the header height
```
dont use excesive padding use the header size instead. Create a sass or css variable to save the header height for mobile and desktop

2023-09-08 19:25 UTC, LUGAMAFE commented on src/sass/public/UI/header/_header.scss
> +    box-shadow: 0px 10px 15px 0px v.$gray;
```suggestion
    box-shadow: 0px 6px 15px 0px v.$gray-500;   
```
reduce the box shadow

2023-09-11 17:00 UTC, LUGAMAFE approved these changes
@CarlosMay7 Listo muchas gracias por los cambios nadamas corrigue el nombre del PR antes de mergear porfavor

2023-09-11 17:59 UTC, CheloChidoone approved these changes

2023-09-12 05:19 UTC, merged