Added the whatsapp button to the site
loopcrack-org/Kinub pull request #40
Opened 2023-09-05 04:33 UTC by CarlosMay7

## Summary

### Problem

The clients need a fast way to contact the company in order to get more information about some products

### Solution

Create a whatsapp button that redirects the client to their whatsaap aplication and open the company chat with a default message

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] The button must be the WhatsApp logo

- [ ] The button will always be fixed in one position

- [ ] The button will redirect opening a new tab, not replacing the current one.

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Manually tested the button

## Resources

## Demo

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/ed81a225-f6cb-44bc-a6a1-49b89ab1a1f5)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/15b16468-a97c-4af9-b2ad-815a10fb4d26)

2023-09-05 04:49 UTC, LUGAMAFE commented on app/Views/public/templates/whatsapp.php
> +<button class="btn-whatsapp" id="btn-whatsapp">
@CarlosMay7 creo que seria mas facil si esto fuera un anchor con un href a la direccion que pusiste en el javascript no?

algo asi 

```suggestion
<a target="_blank" href="https://api.whatsapp.com/send?phone=.....">
```

2023-09-05 16:51 UTC, LUGAMAFE approved these changes

2023-09-05 19:20 UTC, CarlosJCD reviewed
Is it okay that the codeIgniter logo appears?.

Just asking because I genuinely don't know xd.

2023-09-05 23:31 UTC, CheloChidoone commented
> Is it okay that the codeIgniter logo appears?.
> 
> Just asking because I genuinely don't know xd.

@CarlosJCD ese logo de codeigniter que aparece es el debug toolbar, si das click en el veras que sale una barra con unas funcionalidades para debug, no hay problema de que aparezca, ese toolbar aparece porque tenemos el `CI_ENVIRONMENT` como `development` en el `.env`, si lo cambiamos a `production` ya no aparece, asi que no hay problema con eso.

2023-09-05 23:31 UTC, CheloChidoone approved these changes

2023-09-06 01:06 UTC, Oswaldo-Chan approved these changes

2023-09-06 06:00 UTC, Mauriciocr207 requested changes

2023-09-06 06:00 UTC, Mauriciocr207 commented on app/Views/public/templates/whatsapp.php
> +<a target="_blank" href="https://api.whatsapp.com/send/?phone=529993102600&text=*_WHATSAPP KINUB_*%0A*Hola, solicito información sobre dispositivos*">
It´s not a good practice use button elements inside anchor elements in html.
It´s better use
`<a class="btn-whatsapp"><svg>...</svg></a>`
[reference](https://www.freecodecamp.org/espanol/news/ejemplos-de-codigo-de-enlaces-de-botones-html-como-crear-hipervinculos-html-usando-el-atributo-href-en-las-etiquetas/#:~:text=Los%20botones%20se%20suponen%20que,de%20una%20etiqueta%20de%20anclaje.)

2023-09-06 06:03 UTC, Mauriciocr207 commented on src/sass/public/UI/whatsapp/_whatsapp.scss
> +    position: fixed;
sad

2023-09-06 16:18 UTC, FernandoJoachin approved these changes

2023-09-06 17:08 UTC, CarlosJCD approved these changes

2023-09-06 17:09 UTC, Mauriciocr207 approved these changes

2023-09-06 17:09 UTC, merged