KIN-129 Category table view
loopcrack-org/Kinub pull request #46
Opened 2023-09-08 16:48 UTC by FernandoJoachin

The category table was created along with its pagination

## Summary

### Problem

The project requires a way to display existing categories on the categories page of the admin panel to allow users to view and interact with them.

### Solution

Create a view with a table to show the categories, as well as having buttons to create, edit or delete them.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] A table with the existing categories must be displayed.
- [ ] It must have a button for creating a new category.
- [ ] Each register in the table must have the following: Name of the category, Categor, icon, Button to edit and Button to delete.
- [ ] It must implement the private view pagination.

### Testing

- [ ] Add more static categories in views/admin/categories/categories.php file to test performance.

## Demo

[![imagen-2023-09-08-104215001.png](https://i.postimg.cc/vmD9zmg3/imagen-2023-09-08-104215001.png)](https://postimg.cc/v1Fc8bvV)
[![imagen-2023-09-08-104254869.png](https://i.postimg.cc/g2tLnPSR/imagen-2023-09-08-104254869.png)](https://postimg.cc/VJMkV2cL)

2023-09-08 18:02 UTC, CarlosJCD reviewed
Are we going to use the same parameters for responsive web design on the private view?

I am asking this because it seems that for devices that have 475px or less the layout starts to break, but I don't know how important is for the private view to have a responsive design.


Update 12/09/2023: The design its now responsive, excellent work!

2023-09-08 21:19 UTC, LUGAMAFE requested changes
@FernandoJoachin te deje un monton de comentarios, pero no por que tu trabajo este mal, al contrario esta muy bien, pero creo que hay muchas cosas que podemos mejorar. 

Creo que me gustaria que platicaraas todos estos cambioes que te pedi con @Cristianpan y @Mauriciocr207

2023-09-08 21:19 UTC, LUGAMAFE commented on app/Views/admin/categories/Categories.php
> +                                    </table>
Puedes añadir un tfoot porfavor @FernandoJoachin 

```suggestion
                                            </tr>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                               <th>ID</th>
                                               <th>Nombre</th>
                                               <th>Icono</th>
                                               <th>Imagen</th>
                                               <th>Acciones</th>
                                              </tr>
                                          </tfoot>
                                    </table>
```

2023-09-11 17:22 UTC, LUGAMAFE requested changes

2023-09-11 17:22 UTC, LUGAMAFE commented on app/Views/admin/categories/Categories.php
> +                        <table id="category" class="table nowrap dt-responsive align-middle table-hover table-bordered" style="width:100%">
```suggestion
                        <table id="categories-table" class="table nowrap dt-responsive align-middle table-hover table-bordered" style="width:100%">
```
change the name of the id

2023-09-11 17:22 UTC, LUGAMAFE commented on app/Views/templates/admin/dashboardTable.php
> +    <style>
Esta etiqueta style para que es?

2023-09-11 17:22 UTC, LUGAMAFE commented on public/assets/js/pages/category.js
> +    });
```suggestion
    $('#category').DataTable({
        "language": {
            "info": "Mostrando _START_ a _END_ de _TOTAL_ categorías",
            "infoEmpty": "Mostrando 0 a 0 de 0 categorías",
            "infoFiltered": "(filtrado de _MAX_ categorías totales)",
            "lengthMenu": "Mostrar _MENU_ categorías",
        },
         columnDefs: [
            { orderable: false, responsivePriority: 1, targets: -1}
         ]   
    });
```
Añade esto porfavor @FernandoJoachin para mejorar la tabla

2023-09-12 04:48 UTC, FernandoJoachin commented on app/Views/templates/admin/dashboardTable.php
> +    <style>
No me di cuenta que deje eso

2023-09-12 05:07 UTC, LUGAMAFE approved these changes
muchas gracias @FernandoJoachin

2023-09-12 15:58 UTC, CarlosJCD approved these changes

2023-09-12 15:59 UTC, CheloChidoone approved these changes

2023-09-12 18:09 UTC, merged