KIN-84 added client information fieldset to support page
loopcrack-org/Kinub pull request #47
Opened 2023-09-09 06:15 UTC by Oswaldo-Chan

## Summary

### Problem

The customer needs to have a way to get in touch with the company and provide their information so that the company can contact them and assist with the issue they want to resolve.

### Solution

A fieldset was implemented to collect client (customer) information and send it to the company.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [x] Real time validation
- [x] It must be part of a multi-step form
- [x] Collect customer name
- [x] Collect customer e-mail
- [x] Collect customer phone number

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [x] Test real-time validation when trying to move to the next fieldset

## Resources

## Demo

![Technical Support Form](https://clipchamp.com/watch/XIAmJhmYz9g)
![image](https://github.com/loopcrack-org/Kinub/assets/92545103/f0094fc5-e7bc-4025-8632-2e455dd1a92c)
![image](https://github.com/loopcrack-org/Kinub/assets/92545103/6880bbb3-feca-43c6-b496-71f35955fe12)

2023-09-11 16:32 UTC, CarlosJCD commented on src/js/public/support.js
> +function validateFields(fields) {
it might be better to rename this function to "validateEmptyFields" as this is what it actually does and it can be misunderstood its purpose by calling it "validateFields".

2023-09-11 16:32 UTC, CarlosJCD commented on src/js/public/support.js
> +    let isValid = true;
Also here, it could be great if you could change the name to isEmpty, or since you are initiating it on true, you could call it isNotEmpty. Just a suggestion tho ;)

2023-09-11 16:35 UTC, CarlosJCD commented on src/js/public/support.js
> +function validateFields(fields) {
it could also be `checkEmptyFields` or something like that, the point is that it can reveal its action/purpose by only the name. :)

2023-09-11 17:43 UTC, LUGAMAFE commented
@Oswaldo-Chan i think is better to upload a video in the Demo section for this type of Pull Requests too

2023-09-12 04:00 UTC, Oswaldo-Chan commented
@LUGAMAFE I was checking the library you showed me, but I can't use it because I have to buy it first. As for the video demo of how the form works, I uploaded it in the PR

2023-09-12 04:22 UTC, LUGAMAFE commented
> @LUGAMAFE I was checking the library you showed me, but I can't use it because I have to buy it first. As for the video demo of how the form works, I uploaded it in the PR

Oh sorry i found this other one:
https://welisonmenezes.github.io/vanilla-validator/documentation/index.html

2023-09-16 19:06 UTC, FernandoJoachin commented on app/Views/public/support.php
> +                style="display: none;"></div>
Wouldn't it be correct to put display:none in your sass file?

2023-09-18 01:54 UTC, LUGAMAFE requested changes
Excelente trabajo @Oswaldo-Chan te deje varias observaciones para mejorar el codigo y la logica

2023-09-18 01:54 UTC, LUGAMAFE commented on src/js/public/support.js
>      }
```suggestion
// Función para establecer la visibilidad y el mensaje del contenedor de errores
function setContainerVisibility(container, isVisible, cls, message) {
  if (isVisible) {
    container.classList.add("support-form__error--active", cls);
    container.innerHTML = message;
  } else {
    container.classList.remove("support-form__error--active", cls);
    container.innerHTML = "";
  }
}

function updateErrorContainer(field, message, cls) {
  // Obtener el ID del contenedor de errores
  const containerErrorsID = field.getAttribute("data-errors-id");
  
  if (!containerErrorsID) return; // Salir si no hay ID de contenedor de errores

  // Obtener el contenedor de errores
  const containerErrors = document.getElementById(containerErrorsID);

  if (!containerErrors) return; // Salir si el contenedor no existe

  // Determinar si debemos mostrar o ocultar el contenedor de errores
  const shouldDisplayError = Boolean(message);

  // Actualizar la visibilidad y el mensaje del contenedor de errores
  setContainerVisibility(containerErrors, shouldDisplayError, cls, message);
}
```

2023-09-18 01:54 UTC, LUGAMAFE commented on src/js/public/support.js
> +    const validatorForm = new VanillaValidator(configForm);
I think we could do something like this to refactor the code a bit:

```javascript
// Constantes para mensajes y clases
const MESSAGES = {
  required: "campo obligatorio",
  email: "correo inválido",
  phone: "teléfono inválido",
};

const SELECTORS = {
  error: "is-invalid",
  messageError: "invalid-feedback",
};

// Función para el manejo del progreso visual
function handleProgress(step) {
  progressName[step - 1].classList.add("support-progress__name--active");
  progressBullet[step - 1].classList.add("support-progress__bullet--active");
}

// Configuración común para customViewErrors
const commonCustomViewErrors = {
  add: function (field, message, cls) {
    updateErrorContainer(field, message, cls);
  },
  remove: function (field, cls) {
    updateErrorContainer(field, "", cls);
  },
};

const configSteps = {
  container: ".support-form__step",
  button: ".next-step",
  validationBy: "onclick",
  selectors: SELECTORS,
  messages: MESSAGES,
  customViewErrors: commonCustomViewErrors,
  onContainerSuccess: function (container) {
    currentStep++;
    supportForm.style.transform = `translateX(-${(currentStep - 1) * 100}%)`;
    handleProgress(currentStep - 1);
  },
};

const configForm = {
  container: "#support-form",
  button: "#btn-submit",
  validationBy: "onclick",
  messages: {
    required: MESSAGES.required,
  },
  customViewErrors: commonCustomViewErrors,
  onFormSubmit: function (container) {
    handleProgress(currentStep);
    document.querySelector("#support-form").submit();
  },
};

// Inicializar los validadores
const validatorSteps = new VanillaValidator(configSteps);
const validatorForm = new VanillaValidator(configForm);
```

2023-09-18 01:54 UTC, LUGAMAFE commented on app/Views/public/support.php
> +                <fieldset class="support-form__fieldset support-form__step" data-step="1">
```suggestion
                <fieldset class="support-form__fieldset active support-form__step" data-step="1">
```

2023-09-18 02:10 UTC, LUGAMAFE requested changes

2023-09-18 02:10 UTC, LUGAMAFE commented on src/js/public/support.js
> +    initializeFieldsets();
Remove this function. Instead  you need to play with the css visibility property for each fieldset.

```suggestion
```
```javascript
  //Seleccionamos todos los fieldsets del form
   const fieldsetsElements = document.querySelectorAll(
    ".support-form__fieldset"
  );
  
  //Dentro de onContainerSuccess( ... )y prevButtons.forEach((button) => { ....   añadimos esto

  // Borramos la clase active de todos los fieldsets. Notece que no añado un modificador si no una clase .active
  fieldsetsElements.forEach((fieldset) => {
     fieldset.classList.remove("active");
   });
  //Añadiemos la clase active al fieldset actual 
   fieldsetsElements[currentStep - 1].classList.add("active");
```

y dentro de tu archivo `_support.scss`

añade esto: 
```scss

//...codigo previo
.support-form {
  display: grid;
  grid-template-columns: repeat(3, 100%);
  margin-bottom: 3rem;
  transition: transform 300ms ease-in-out;

  &__fieldset {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    border: none;
   //Añadimos la propiedad visibility y no  la de display none. Para ocultar el elemento y que no se pueda 
   // interactuar con los inputs por medio de los tabs, pero al mismo tiempo el fieldset sigue ocupando su 
   // mismo tamaño para no interferir con la transform de translateX()
    visibility: hidden;
    &.active {
     //Se muestra el elemento
      visibility: visible;
    }
  }
//......
```

2023-09-18 02:10 UTC, LUGAMAFE commented on app/Views/public/support.php
> +                <fieldset class="support-form__fieldset support-form__step" data-step="1">
```suggestion
                <fieldset class="support-form__fieldset active support-form__step" data-step="1">
```
we add the .active class to de first fieldset by default

2023-09-18 02:10 UTC, LUGAMAFE commented on src/js/public/support.js
> +    function initializeFieldsets() {
delete all the function

2023-09-18 02:10 UTC, LUGAMAFE commented on src/js/public/support.js
> +    function handleFieldKeydown(e) {
delete this function too

2023-09-20 23:33 UTC, CheloChidoone approved these changes
Good Job Oswaldo!

2023-09-21 00:19 UTC, CarlosMay7 approved these changes
Nice job!

2023-09-21 05:19 UTC, LUGAMAFE requested changes
Te deje unos pequeños cambios que hay que hacer para refinar el codigo @Oswaldo-Chan pero todo lo demas se ve super.

Porfavor encontre este error en la validacion con el BE asegurate de que @CarlosJCD añada un bug ticket y permitir numeros con ladas. Ya que si imaginemos un extranjero quisiera dejar su numero, no podria.
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/c8ee9162-7c9c-49eb-9231-b9ea123a5c5c)

2023-09-21 05:19 UTC, LUGAMAFE commented on src/js/public/support.js
> +    fieldsetsElements[currentStep - 1].classList.add("support-form__fieldset--active");
```suggestion
```
No tiene caso ejecutar este codigo cuando se ejecuta el JS por primera vez. Ya que ya verifique que en tu html ya le pusiste la clase `support-form__fieldset--active` al primer fieldset.

De hecho en mi comentario original puedes ver donde te pedi que lo pusieras:
https://github.com/loopcrack-org/Kinub/pull/47#discussion_r1328197418

este codigo deberia estar dnetro de 
`onContainerSuccess( ... )y prevButtons.forEach((button) => { .... `

te dejare comentarios mas abajo de donde deberia estar.

2023-09-21 05:19 UTC, LUGAMAFE commented on src/js/public/support.js
> +            fieldsetsElements[currentStep - 1].classList.add("support-form__fieldset--active");
```suggestion
            fieldsetsElements.forEach((fieldset) => {
               fieldset.classList.remove("support-form__fieldset--active");
            });
            fieldsetsElements[currentStep - 1].classList.add("support-form__fieldset--active");
```
Es importante remover el modificador --active de los fieldsets que ya no se estan mostrando

2023-09-21 05:19 UTC, LUGAMAFE commented on src/js/public/support.js
> +                progressName[currentStep - 1].classList.remove('support-progress__name--active');
```suggestion
                supportForm.style.transform = `translateX(-${(currentStep - 1) * 100}%)`;
                fieldsetsElements.forEach((fieldset) => {
                  fieldset.classList.remove("support-form__fieldset--active");
                });
                fieldsetsElements[currentStep - 1].classList.add("support-form__fieldset--active");
                progressName[currentStep - 1].classList.remove('support-progress__name--active');
```
mismo comentario que arriba

de hecho ya que este codigo es el mismo:

```javascript
fieldsetsElements.forEach((fieldset) => {
  fieldset.classList.remove("support-form__fieldset--active");
});
fieldsetsElements[currentStep - 1].classList.add("support-form__fieldset--active");
```

puedes crear una funcion para esto y nadamas mandarla a llamar

2023-09-22 15:43 UTC, LUGAMAFE approved these changes

2023-09-23 20:59 UTC, Mauriciocr207 approved these changes

2023-09-24 03:01 UTC, CarlosJCD approved these changes

2023-09-24 03:09 UTC, merged