KIN-220Renaming of the emails, email_types and users tables
loopcrack-org/Kinub pull request #48
Opened 2023-09-11 17:38 UTC by CarlosJCD

### Problem

Standarize the database to a single naming convention
### Solution

Renaming the existing table to match the naming convention
## Acceptance Criteria

## Resources

- [Naming conventions document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/14188560)

2023-09-11 17:49 UTC, LUGAMAFE requested changes

2023-09-11 17:49 UTC, LUGAMAFE commented on backup/Database.sql
>  CREATE TABLE `Email` (
```suggestion
CREATE TABLE `emails` (
```
Shouldn't it also say emails here?

2023-09-11 17:49 UTC, LUGAMAFE commented on backup/Database.sql
> +  CONSTRAINT `Correos_FK` FOREIGN KEY (`idTypeEmail`) REFERENCES `email_types` (`id`)
what about 
```suggestion
  CONSTRAINT `emails_fk` FOREIGN KEY (`idTypeEmail`) REFERENCES `email_types` (`id`)
```

2023-09-11 18:04 UTC, CheloChidoone reviewed
Also remember to add the Labels for your PR.

2023-09-12 15:39 UTC, LUGAMAFE approved these changes

2023-09-12 15:59 UTC, CheloChidoone approved these changes

2023-09-13 05:05 UTC, Cristianpan requested changes
I haven't been able to test the backup because it gives me an error when importing. Please check if everything is correct and make the necessary changes.

[![error](https://i.postimg.cc/NF60qNCH/imagen-2023-09-12-230521531.png)](https://postimg.cc/FkKv0x4r)

2023-09-13 20:59 UTC, CheloChidoone approved these changes
It looks good and the importing works now, good job.

2023-09-14 04:23 UTC, Cristianpan approved these changes

2023-09-15 02:10 UTC, FernandoJoachin approved these changes

2023-09-15 02:14 UTC, merged