KIN-130 Create category view
loopcrack-org/Kinub pull request #49
Opened 2023-09-13 07:22 UTC by FernandoJoachin

The form was created to create the categories

## Summary

### Problem

The project requires having a view that allows registering a new category in the system.

### Solution

Create a form for creating categories.

## Acceptance Criteria

### Requirements checklist

- [ ] It must load the create category template form with its fields empty.
- [ ] It must have a submit button
- [ ] It must have a return page button

### Testing

- [ ] Upload an image in drag and drop
- [ ] Write a tag

## Demo

[![imagen-2023-09-13-011224355.png](https://i.postimg.cc/QxJ09kNH/imagen-2023-09-13-011224355.png)](https://postimg.cc/MvXygBQS)

2023-09-13 21:28 UTC, CheloChidoone requested changes
Looks good for being the layout of the create category page but when I write tags I can't see the first letters and it made me think I wasn't writing correctly until I saw the little message below and realized the letters I wrote were hiding for some reason, we should fix that. 
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/d84d11c7-11cc-49d6-a5fa-233d6ce352c0)

2023-09-14 01:01 UTC, FernandoJoachin commented
> Looks good for being the layout of the create category page but when I write tags I can't see the first letters and it made me think I wasn't writing correctly until I saw the little message below and realized the letters I wrote were hiding for some reason, we should fix that. ![image](https://user-images.githubusercontent.com/38699927/267793817-d84d11c7-11cc-49d6-a5fa-233d6ce352c0.png)

It seems to be a compatibility problem with the browser since it works fine on Firebox. [![imagen-2023-09-13-185951088.png](https://i.postimg.cc/4xq1gwLQ/imagen-2023-09-13-185951088.png)](https://postimg.cc/QFg7ggrF)

2023-09-15 04:17 UTC, CarlosJCD approved these changes
Great work!

2023-09-15 04:54 UTC, Cristianpan approved these changes

2023-09-15 05:00 UTC, Mauriciocr207 approved these changes

2023-09-15 05:05 UTC, merged