KIN-81 added measurement solutions section to homepage
loopcrack-org/Kinub pull request #51
Opened 2023-09-13 20:03 UTC by Oswaldo-Chan

## Summary

### Problem

The customer needs to learn about the different solutions that the company offers.

### Solution

A section was implemented on the homepage that displays all the types of measurement solutions offered by the company.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

Each section of a solution must contain the following:

- [x] Section name
- [x] Icon
- [x] Representative background image
- [x] Information text
- [x] Hovering design matching the mockup

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [x] Test responsive design
- [x] Hovering test 

## Resources

[Mock-up](https://drive.google.com/file/d/1WMpOfR5sZbRXIYwBAdbW3wpfuCnmyLmy/view?usp=drive_link)

## Demo

![image](https://github.com/loopcrack-org/Kinub/assets/92545103/cff6fcc0-ea5b-4206-96b3-1cd1e6003a17)
![image](https://github.com/loopcrack-org/Kinub/assets/92545103/8e01d0a6-e23e-45ca-af30-c829379ed320)
![image](https://github.com/loopcrack-org/Kinub/assets/92545103/e311e043-7f23-48e8-896f-248ece72d6fe)

2023-09-14 00:14 UTC, CheloChidoone requested changes
I found some issues you need to check, the colors on the little bars below each measurement solution are not all the same in the original design, try to make the colors match there, the other issue is your changes are affecting other things, in this case, the footer, your changes made some of the icons on the footer disappear, check that too and be careful that you are not affecting your previous work with the new things that you are adding.  

![image](https://github.com/loopcrack-org/Kinub/assets/38699927/fa8ec06f-110c-49c4-bd27-741f31f32e15)

![image](https://github.com/loopcrack-org/Kinub/assets/38699927/6834b592-6fa5-4130-ae00-8e23ee54aa42)

2023-09-14 17:50 UTC, CarlosJCD reviewed
if I am not mistaken, I remember that @LUGAMAFE  had told us that hovering over it produced an animation in which the icon and the category name became smaller and displayed upwards, while the text became larger, but I am not entirely sure. Can you confirm me if this is true?

2023-09-15 01:57 UTC, FernandoJoachin commented
> if I am not mistaken, I remember that @LUGAMAFE had told us that hovering over it produced an animation in which the icon and the category name became smaller and displayed upwards, while the text became larger, but I am not entirely sure. Can you confirm me if this is true?

I think you're right, it sounds to me like that's what I should do.

2023-09-15 15:56 UTC, LUGAMAFE requested changes
I think you hit the nail on the head with the color animation in the hover @Oswaldo-Chan  but as the colleagues tell you the animation is missing to make the icon smaller and move it up, the reason for this is that we need to show more text when the user hover, also the color of the bottom bar when you hover should be a different color. 

Also the cards should occupy 100% of the screen width, I was looking at the designs and the cards occupy the entire width of the screen. Keep in mind that the images of the designs are in a size of 1920px wide.

Also as marcelo says it looks like you broke some .svg images in the footer.

![image](https://github.com/loopcrack-org/Kinub/assets/24960025/7a6ce780-74a0-4df8-a790-d337d41ec195)

2023-09-22 15:48 UTC, LUGAMAFE requested changes
Hi @Oswaldo-Chan is already much better but the transitions should be smoother and slower. The animations as they are now are very aggressive.

2023-09-29 16:16 UTC, CarlosMay7 requested changes
I really liked the design! I left a comment to improve it a little more

2023-09-29 16:16 UTC, CarlosMay7 commented on src/public/sass/UI/measurement-solutions/_measurement-solutions.scss
> +            @include m.grid(3, 1fr);
```suggestion
            @include m.flex-columns(3, 0rem, 0rem);
```
Creo que quedaría mejor dejar los elementos "extra" de la fila de 3 elementos en el medio la sección utilizando este mixin

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/c4e0daa1-7607-4dbc-ba7b-06d43b691831)

2023-09-30 01:12 UTC, CarlosMay7 approved these changes

2023-09-30 05:30 UTC, LUGAMAFE approved these changes
@Oswaldo-Chan Super mejor la animacion todavia no me gusta mucho el responsive pero es un tema que podemos ver luego! muchas gracias @Cristianpan por la ayuda con los svgs!!

Deje unos pequeños nit que siendo honesto luego podemos ver en le futuro pero me gustaria que anotartan

2023-09-30 05:30 UTC, LUGAMAFE commented on app/Views/public/index.php
> +                </svg>
Note that all this will need to be copied and pasted for each image we use.
and just change the href of 

`<image href="assets/images/drop.svg" width="100%" height="100%" />`

we can reuse linearGradient def if move the def to the top of the html

2023-09-30 05:30 UTC, LUGAMAFE commented on app/Views/public/index.php
> +                </svg>
Missing <mask> <defs> even if this works now without the mask defs, in the future you will have to have a mask for each image. 
```suggestion
                <svg
                    class="measurement-solution__svg"
                    xmlns="http://www.w3.org/2000/svg"
                    width="200"
                    height="200"
                    viewBox="0 0 200 200"
                >
                <rect
                    x="0"
                    y="0"
                    width="100%"
                    height="100%"
                    fill="url(#mask-degraded)"
                    mask="url(#icon-mask)"
                />
                <defs>
                    <mask id="icon-mask" x="0" y="0" width="200" height="200">
                        <image href="assets/images/drop.svg" width="100%" height="100%" />
                    </mask>
                </defs>
                </svg>

                <svg
                    class="measurement-solution__svg--mask"
                    xmlns="http://www.w3.org/2000/svg"
                    width="200"
                    height="200"
                    viewBox="0 0 200 200"
                >
                <rect
                    x="0"
                    y="0"
                    width="100%"
                    height="100%"
                    fill="#ffffff"
                    mask="url(#icon-mask)"
                />
                </svg>
```

2023-09-30 05:30 UTC, LUGAMAFE commented on app/Views/public/index.php
> +                    </linearGradient>
We can move this linearGradient def within an individual svg to the beginning of the body so we can re use mask-degraded id def in other svgs

```html
<body>
    
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="200"
        height="200"
        viewBox="0 0 200 200"
    >
                    
        <defs>
            <linearGradient
                id="mask-degraded"
                x1="0%"
                y1="0%"
                x2="100%"
                y2="0%"
            >
                <stop offset="20%" style="stop-color: #0D65A7" />
                <stop offset="40%" style="stop-color: #54B4DB" />
                <stop offset="60%" style="stop-color: #7FBCD6" />
                <stop offset="80%" style="stop-color: #2892BC" />
            </linearGradient>
          <defs>
    </svg>
    
    Body ........
    
    
```

2023-09-30 06:07 UTC, Cristianpan approved these changes

2023-09-30 13:36 UTC, Mauriciocr207 approved these changes

2023-10-06 01:25 UTC, CheloChidoone approved these changes

2023-10-09 02:02 UTC, LUGAMAFE commented
@Oswaldo-Chan esta historia ya lleva mucho tiempo sin mergearse porfa cuando puedas

2023-10-09 16:00 UTC, CarlosMay7 approved these changes

2023-10-09 16:24 UTC, merged