KIN-228 Webpack-gulp integration
loopcrack-org/Kinub pull request #52
Opened 2023-09-14 05:55 UTC by Mauriciocr207

## Summary

### Problem

Developers need an space where build all project resources. This to accelerate the development and generate assets to production.

### Solution

Reestructuring of gulp and tasks to compile SASS and use JS on project. Was created an integration made with webpack and gulp to minify, compile and get an standart CSS and JS files. 

## Acceptance Criteria

### Requirements checklist

- [x] Compile SASS to minified and standart CSS for multiple files.
- [x] Bundle JS modules into one minified JS file for multiple files.
- [x] It is supported importing JS modules and SASS from node_modules.
- [x] Provide npm scripts to generate all JS and CSS to production.
- [x] Provide npm scripts to development mode in three areas: Admin, Public and Common.

### Testing

- [x] Run  the scripts provided on `package.json`. The scripts are described below.

- `npm run build:images`. Build all images in .webp, .avif, and jpg formats.
- `npm run build:public`. Build public assets
- `npm run build:admin`. Build admin assets
- `npm run build:common`. Build common assets
- `npm run build`. Build all assets to production
- `npm run dev:public` Run a development mode to build assets on public area
- `npm run dev:admin` Run a development mode to build assets on admin area
- `npm run dev:common` Run a development mode to build assets on common area

2023-09-14 16:56 UTC, CarlosJCD approved these changes
looks good

2023-09-14 22:11 UTC, CheloChidoone approved these changes
The assets seem to be generated correctly, so it looks good for the objective of this PR.

2023-09-15 23:46 UTC, LUGAMAFE requested changes

2023-09-16 00:02 UTC, Mauriciocr207 commented on package.json
> +    "gulp-sourcemaps": "^3.0.0"
Yes, I was thinking about how dependencies could be devDependencies and I saw only one, the gulp-sourcemaps. Which other dependencies could be devDependencies?

2023-09-21 03:19 UTC, LUGAMAFE approved these changes
I only left a small nitpick. And please update the description of the tickets with the new commands

2023-09-21 14:59 UTC, CarlosMay7 approved these changes

2023-09-21 16:20 UTC, Oswaldo-Chan approved these changes

2023-09-21 23:37 UTC, merged