KIN-88 Equipment Layout Public View Front End
loopcrack-org/Kinub pull request #53
Opened 2023-09-14 07:37 UTC by CarlosMay7

## Summary

### Problem

The site needs a place where the users can find all the types of equipment they have

### Solution

Creating a page where all the different categories are listed is a way to give the users the information they need

## Acceptance Criteria

### Requirements checklist

- [ ] It must have a heading associated to the page

- [ ] It must have a background video associated with the page.

- [ ] Each category must be represented as a cell of a grid. Each cell must contain the following:

    - An icon related to the category
    - The category’s name.

- [ ] It must be responsive

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Checked the responsiveness
- [ ] Check the animations
- [ ] Check the video is playing

## Resources

## Demo

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/62a6e823-5959-4cb0-9f98-a5e76242222a)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/b28cdf78-86d1-4f6c-9515-9ebfbd348dda)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/dca7ed4a-d485-4f4d-af89-d1c1d9fcd115)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/1e9c4b55-15c5-4534-97c8-605208f20f1e)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/a29cb9b4-c75b-46a3-a8e8-23402bf05c81)

2023-09-14 07:39 UTC, CarlosMay7 commented
I created a placeholder route "equipment" in order to make and try this design. When this feature is accepted I will delete that route

2023-09-14 07:42 UTC, CarlosMay7 commented
I also think the spacing is kind of weird but while it is getting closer to the max (9 categories I think) it gets better

2023-09-14 17:41 UTC, CarlosJCD approved these changes
Great job. Be sure to replace the placeholder route with the one specified on [the documentation](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/3178510/Routes).

2023-09-14 17:41 UTC, CarlosJCD commented on app/Config/Routes.php
> +$routes->get('/equipment', 'CtrlPublicPages::viewEquipment');
I am curious, why using a placeholder instead of the route specified on the documentation?

2023-09-14 21:02 UTC, CheloChidoone reviewed
It looks fine but I also wonder why you used a placeholder route instead of the actual route specified?

2023-09-15 01:18 UTC, CarlosMay7 commented on app/Config/Routes.php
> +$routes->get('/equipment', 'CtrlPublicPages::viewEquipment');
Sorry, I wasn't sure if I could create one more function in the controller and put a new route on the router so I put it that way but I'll change it, thanks

2023-09-15 02:57 UTC, CarlosJCD commented on app/Config/Routes.php
> +$routes->get('/equipment', 'CtrlPublicPages::viewEquipment');
Don't worry, just asking by mere curiosity. Just change the route to the one on the doc and that would be it. ;)

2023-09-15 05:48 UTC, Mauriciocr207 reviewed
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/3911bb7e-4d4e-4329-9cb7-29fe846f5d37)
I see that the grid is taken width 100%, it could be better if the `class="equipment_grid" have a max-width. And for the video, it could be better if it extends to all width.

2023-09-15 05:48 UTC, Mauriciocr207 commented on app/Views/public/equipment.php
> +
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/3911bb7e-4d4e-4329-9cb7-29fe846f5d37)
I see that the grid is taken width 100%, it could be better if the `class="equipment_grid"` have a max-width. And for the video, it could be better if it extends to all width.
Also, I see you use gap: 2rem and row-gap:2rem, you can pass row and column gap to gap property, like: `gap: 2rem 4rem` with you have `row-gap:2rem` and `column-gap:4rem`

2023-09-15 21:13 UTC, CheloChidoone approved these changes
It looks better, good job!

2023-09-16 00:33 UTC, LUGAMAFE requested changes
Very good design @CarlosMay7 I would take a little more care of the margins that are not equal to the design but it is only a nitpick not a blocker.

I left you some comments

2023-09-16 00:33 UTC, LUGAMAFE commented on src/sass/public/UI/equipments/_equipments.scss
> +        backdrop-filter: blur(50px);
```suggestion
        backdrop-filter: blur(50px) hue-rotate(15deg) saturate(1.8);
```

add this to match the hover effect in the designs

2023-09-16 00:33 UTC, LUGAMAFE commented on src/js/public/equipments.js
@CarlosMay7 hahahaha bro you went too far, delete this file.
The same thing you did here with JS can and should be done with css and mediaqueries, you literally started to mimic the behavior of media queries, do you realize?

2023-09-16 00:33 UTC, LUGAMAFE commented on src/sass/public/base/_global.scss
> +    margin: 0 auto;
this is not the correct file to add this css

2023-09-16 01:04 UTC, CarlosMay7 commented on src/js/public/equipments.js
I did it that way thinking that there will be times when there is one left over in the rows so that thing will have to be placed in the middle, but there will also be occasions when there are 2 left over or they are full, so it doesn't apply and I didn't find a way to put those conditions in css so I opted for js, should I continue looking for options to put those conditions in css?

2023-09-17 23:06 UTC, LUGAMAFE requested changes
I created a new mixin that will help you to remove the js file @CarlosMay7  and I also added some changes to improve the sass and match the design better.

2023-09-17 23:06 UTC, LUGAMAFE commented on src/sass/public/UI/equipments/_equipments.scss
> +            @include m.grid(3, 4rem 2rem);
```suggestion
           @include m.flex-columns(3, 2rem, 4rem);
```

include this new mixin I created. 

don't forget to add this mixin in the corresponding _mixins.scss file

``` scss
@mixin flex-columns(
  $columns,
  $column-gap,
  $row-gap,
  $items-max-height: none,
  $justify: center,
  $align-content: flex-start
) {
  display: flex;
  flex-wrap: wrap;
  justify-content: $justify;
  align-content: flex-start;
  row-gap: $row-gap;
  column-gap: $column-gap;
  > * {
    flex-basis: calc((100% - $column-gap * ($columns - 1)) / $columns);
    max-height: $items-max-height;
  }
}
```

`flex-columns` Mixin

1. **$columns**: Specifies the number of columns.
2. **$column-gap**: Gap between columns.
3. **$row-gap**: Gap between rows.
4. **$items-max-height**: Maximum height for items. It defaults to none.
5. **$justify**: Sets the justify-content property. Defaults to center.
6. **$align-content**: Sets the align-content property. Defaults to flex-start.

It uses Flexbox to create a layout, utilizing the flex-wrap, justify-content, align-content, row-gap, and column-gap properties. It then calculates the flex-basis for child elements to properly place them into columns.

`grid` Mixin

1. **$columns**: Specifies the number of columns.
2. **$gap**: Gap between grid items.

It uses CSS Grid to create a layout using grid-template-columns and gap properties. It's much more straightforward and relies on the built-in Grid layout capabilities to place items into columns.

**Differences**
**Flexibility**: The `flex-columns` mixin provides more control over how items should be laid out. You can control justification, content alignment, and even the maximum height of items.

**Code Complexity**: _grid_ is simpler and has less code, making it easier to understand. However, it's also less flexible.

**Cross-Browser Support**: Flexbox has better support in older browsers compared to CSS Grid. Although as of my last update in September 2021, this is becoming less of a concern.

**Responsibility**: In `flex-columns`, you have to calculate the width of the columns yourself (using `flex-basis`). In `grid`, the grid layout takes care of that for you.

**Which is better?**
"Better" can be subjective, depending on what you need:

For simplicity and modern layouts: Use the grid mixin. It's cleaner and leverages newer CSS standards.

For more control and possibly better browser support: Use the flex-columns mixin.

2023-09-17 23:06 UTC, LUGAMAFE commented on src/js/public/equipments.js
now you can delete this file and use `flex-columns` mixin instead

2023-09-17 23:06 UTC, LUGAMAFE commented on app/Views/public/equipment.php
> +<?php $this->endSection(); ?>
```suggestion

```

delete if no needed for the moment

2023-09-20 18:20 UTC, FernandoJoachin approved these changes
Good job!!

2023-09-21 05:25 UTC, LUGAMAFE approved these changes
Nice Job @CarlosMay7

2023-09-21 10:24 UTC, Oswaldo-Chan approved these changes

2023-09-21 15:41 UTC, merged