KIN-201 Template category form
loopcrack-org/Kinub pull request #56
Opened 2023-09-15 14:37 UTC by FernandoJoachin

The template category form was created

## Summary

### Problem

As developers, we want to not repeat the code and be able to reuse the same form both to create and edit categories.

### Solution

Create a template for the create and edit category form.

## Acceptance Criteria

### Requirements checklist

The form must get the next information:

- [ ] Category name
- [ ] Related category icon
- [ ] Category image, which will be useful for the header of the product catalog page. The input must be a drag a drop
- [ ] Category tags

### Testing

- [ ] The create category form must be correct.
- [ ] In the viewCategoryCreate method of CtrlCategory send an array with the information that you want the inputs to display and this must be able to be displayed in the view. For example: [ "category" => ["title" => "Telemetry", "tags" => "tag1,tag2"] ]

2023-09-15 21:27 UTC, CheloChidoone approved these changes
Looks good, well done!

2023-09-16 02:51 UTC, Cristianpan requested changes
Everything looks good, but I think it would be better to move the form template to the folder where are the views corresponding to the category to have a better order and please make the other changes

2023-09-16 02:51 UTC, Cristianpan commented on app/Views/templates/admin/categoriesFormTemplate.php
> +                    <input type="text" class="form-control" name="category_title" id="category-title-input" value="<?= $category["name"] ?? "";?>" placeholder="Ingrese el título" required>
Please change the values of the "name" attributes of the inputs to correspond to the name of the table columns in the database.

2023-09-16 04:02 UTC, Cristianpan approved these changes

2023-09-16 18:01 UTC, CarlosJCD approved these changes

2023-09-16 18:50 UTC, Oswaldo-Chan approved these changes

2023-09-18 02:39 UTC, LUGAMAFE approved these changes
Se ve muy bien @FernandoJoachin solo hay que asegurarnos de no recibir tambien videos. Actualmente se pueden subir

2023-09-19 16:12 UTC, merged