KIN-205 Creation of the measurement solution table
loopcrack-org/Kinub pull request #59
Opened 2023-09-20 05:47 UTC by FernandoJoachin

The measurement solution table was created

## Summary

### Problem

The project requires displaying existing measurement solutions on the "measurement solutions" page of the admin panel to allow users to view and interact with them.

### Solution

Create a table to show the different types of measurement solution

## Acceptance Criteria

### Requirements checklist

- [ ] A table with the existing measurement solutions must be displayed.
- [ ] It must have a button for creating a new measurement solution.
- [ ] Each register in the table must have the following: Name of the measurement solution, Measurement solution icon, Button to edit, Button to delete.
- [ ] It must implement the private view pagination.

### Testing

- [ ] Log in and go to the route: http://kinub.cm/admin/soluciones

## Demo
[![imagen-2023-09-19-234610211.png](https://i.postimg.cc/tJNjWm4Z/imagen-2023-09-19-234610211.png)](https://postimg.cc/tnJwHkPp)

2023-09-20 23:44 UTC, CheloChidoone requested changes

2023-09-20 23:44 UTC, CheloChidoone commented on app/Views/admin/typeSolutions/Solutions.php
> +                            <a href="/admin/categorias/create" class="btn btn-success btn-label waves-effect waves-light rounded-pill">
This button redirects to `/admin/categorias/create` instead of `/admin/soluciones/create`, I know the layout for the `create` for soluciones isn't complete yet but this href shouldn't go to the categorias `create`, also the url shouldn't be `create`, I hadn't noticed that but it should be `crear` in spanish and not `create`

2023-09-21 05:46 UTC, LUGAMAFE approved these changes

2023-09-21 16:31 UTC, CheloChidoone approved these changes

2023-09-21 18:02 UTC, CarlosJCD approved these changes

2023-09-22 03:50 UTC, Cristianpan approved these changes

2023-09-22 04:14 UTC, merged