KIN-207 Create measurement solution view
loopcrack-org/Kinub pull request #61
Opened 2023-09-21 06:37 UTC by FernandoJoachin

## Summary

### Problem

The project requires having a form to be able to record a new measurement and display it on the home page.

### Solution

Make a form to create the measurement solution

## Acceptance Criteria

### Requirements checklist

- [ ] The button should redirect to a page with a form to create a new measurement solution.
- [ ] It must get the following info: Measurement solution name, Related icon, Background image and Informative text

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Go to the path admin/solutions/create
- [ ] Upload an image in drag and drop

## Demo

[![imagen-2023-09-21-003148003.png](https://i.postimg.cc/d37cbw5T/imagen-2023-09-21-003148003.png)](https://postimg.cc/7JyR788x)

2023-09-21 22:22 UTC, CheloChidoone requested changes
Buen trabajo Joachin, pero es necesario tener otro archivo .js de file upload diferente aunque es igual al .js de file upload de categorias?, No podemos tener uno reutilizable para todos los lugares donde hagamos uso de este plugin para subir archivos?

2023-09-21 23:21 UTC, FernandoJoachin commented
> Buen trabajo Joachin, pero es necesario tener otro archivo .js de file upload diferente aunque es igual al .js de file upload de categorias?, No podemos tener uno reutilizable para todos los lugares donde hagamos uso de este plugin para subir archivos?

2023-09-22 18:12 UTC, CheloChidoone approved these changes
Great Job Joachin, it will be easier now with this reusable .js in cases where image file uploads are needed.

2023-09-23 08:47 UTC, Cristianpan approved these changes

2023-09-23 17:46 UTC, LUGAMAFE requested changes
@FernandoJoachin there are several things that do not convince me that I put in the review. Like a mistake that I realized with the sass of the filepond.
I believe that mau forced a blue style for when there are errors in the filepond. 
Try to drag an invalid file to an input and you will see that even though it tells you that the file is invalid it will show the file in blue color when it should be red.

You have to remove the `!important` from the following image to correct this:
`src\sass\admin\plugins\_filepond.scss`
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/b36f0987-46f4-4816-94a0-e819b34fe6e1)

2023-09-23 17:46 UTC, LUGAMAFE commented on app/Views/admin/typeSolutions/SolutionCreate.php
> +                                    <input type="file" class="filepond filepond-input-multiple" name="icon" data-allow-reorder="true" data-max-file-size="3MB" data-max-files="3">
```suggestion
                                    <input type="file" class="filepond" name="icon">
```
All these filepond attributes I don't think it's good to put them in the html directly, if you already have a filepond configuration object in the JS it's better to put it there. For each html attribute there is a mapping to a configuration property of the filepond instances.

and why you are using the `.filepond-input-multiple` class?

2023-09-23 17:46 UTC, LUGAMAFE commented on app/Views/admin/typeSolutions/SolutionCreate.php
> +                                    <input type="file" class="filepond filepond-input-multiple" name="image" data-allow-reorder="true" data-max-file-size="3MB" data-max-files="3">
```suggestion
                                    <input type="file" class="filepond" name="image">
```
same comment as above

2023-09-23 17:46 UTC, LUGAMAFE commented on src/js/pages/form-file-upload-img.init.js
Unlike chelo I do think there should be a filepond file for each page.
The problem is that before, your configurations looked similar, because you are not creating the instances correctly. 
Here is what the configuration file for the current page should look like:

```js
//Se registran los plugins necesarios de filepond, los suficientes para que esta pagina soluciones de medicion funcione.

// FilePond
FilePond.registerPlugin(
  // encodes the file as base64 data
  FilePondPluginFileEncode,
  // validates the size of the file
  FilePondPluginFileValidateSize,
  // corrects mobile image orientation
  FilePondPluginImageExifOrientation,
  // previews dropped images
  FilePondPluginImagePreview,
  FilePondPluginFileValidateType
);


//Se pone la configuracion inicial estandar para todas las nuevas instancias creadas con filepond
FilePond.setOptions({
  labelIdle:
    'Arrastra y suelta tu imagen o <span class="filepond--label-action"> Selecciona </span>',
  labelFileTypeNotAllowed: "Archivo no valido",
  fileValidateTypeLabelExpectedTypes: `Se espera {allTypes}`,
  allowReorder: true,
  maxFiles: 1,
  maxFileSize: "3MB",
});

//Since the input names should be unique, instances are created for each input that filepond will use.


FilePond.create(document.querySelector("input[name='icon']"), {
  //Notece que en esta instancia podemos sobrescribir la propiedad 'labelIdle' que es parte de la configuracion inicial de todas las instancias de filepond
  labelIdle:
    'Arrastra y suelta tu icono o <span class="filepond--label-action"> Selecciona </span>',
  //Solo aceptamos imagens svg  
  acceptedFileTypes: "image/svg+xml",
});

FilePond.create(document.querySelector("input[name='image']"), {
 //Aceptamos cualquier tipo de imagen
  acceptedFileTypes: "image/*",
});

```

The same above should be done for the categories page.

2023-09-23 20:19 UTC, Mauriciocr207 commented on src/js/pages/form-file-upload-img.init.js
@LUGAMAFE yes, that `!important` was by the initial configuration of velzon, is a file directly from velzon template.

2023-09-23 20:45 UTC, Mauriciocr207 commented on src/js/pages/form-file-upload-img.init.js
Also, I see a problem when you put a file over the drag and drop. When you do this, a circle appears on the box of drag and drop, but, when you change the theme to dark, looks like the circle disappear, and it seems you can´t put files.

![Captura de pantalla (1133)](https://github.com/loopcrack-org/Kinub/assets/70463645/4f980ac2-896f-4ce1-81b0-1d9c2f1a390a)
![Captura de pantalla (1134)](https://github.com/loopcrack-org/Kinub/assets/70463645/48365b45-d71e-4205-affd-875fe36e4c85)

That means it´s necessary to create a style for dark mode for this circle.  Checking on filepond [docs](https://pqina.nl/filepond/docs/api/style/), you can see that the class for this circle is `.filepond--drip-blob`, and for change the color you need to add a color to `background-color` property.
In your file `src\sass\admin\plugins\_filepond.scss` you can add, for example, the following code to add the corresponding styles:

```scss
[data-bs-theme="dark"] .filepond--drip-blob {
  background: #b7b7b7;}

}
```   
The `[data-bs-theme="dark"]` is because of the way we change the theme on html.

2023-09-23 20:49 UTC, Mauriciocr207 commented on src/js/pages/form-file-upload-img.init.js
And the path on the description may be `admin/soluciones/create`

2023-09-24 02:51 UTC, FernandoJoachin commented on app/Views/admin/typeSolutions/SolutionCreate.php
> +                                    <input type="file" class="filepond filepond-input-multiple" name="icon" data-allow-reorder="true" data-max-file-size="3MB" data-max-files="3">
My mistake of leaving the filepond-input-multiple thing

2023-09-24 20:08 UTC, LUGAMAFE approved these changes
Nice!

2023-09-24 21:16 UTC, CarlosJCD approved these changes

2023-09-24 21:29 UTC, CarlosMay7 approved these changes

2023-09-24 23:09 UTC, CarlosMay7 approved these changes

2023-09-24 23:10 UTC, Cristianpan approved these changes

2023-09-24 23:10 UTC, merged