KIN-237 Refactor navigation bar implementation
loopcrack-org/Kinub pull request #65
Opened 2023-09-23 21:00 UTC by CarlosMay7

## Summary

### Problem

The navigation bar implementation should be a block that does not change depending on the device size

### Solution

Change the HTML implementation so instead of being different blocks there is now only one that changes its styles dynamically

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] The navigation bar must have the same functionality 
- [ ] The navigation bar HTML implementation must be one block
- [ ] The link routing must redirect to the respective route
- [ ] There must not be a separation between the navigation bar and the "About Us" section

### Testing
- [ ] Manually checked the navigation bar behavior through different events like opening, resizing and redirecting
- [ ] Checked all the routes manually

## Resources

## Demo
Demo video
https://github.com/loopcrack-org/Kinub/assets/97546829/eac60b4d-db1c-41b8-a1df-8a16b06f09e9

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/8306148c-3838-4e4b-9143-9937486f5699)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/fe93a506-e637-4493-8d02-9779b4cbdb0b)

2023-09-24 03:42 UTC, CarlosJCD reviewed
Nice job as always, however, even if it works everything fine I think it is necessary to make an effort to generate a more maintainable and cleaner code. 

I left some suggestions on this, basically refactor to smaller functions with intention revealing names that helps the code readability. However there are a lot of this opportunity areas to improve

2023-09-24 03:42 UTC, CarlosJCD commented on src/js/public/menuMobile.js
> +    if (displayWidth<751) {
you could extract this to a function, something like "isMobileView".  Especially considering that you use this expression in more than once.

2023-09-24 03:42 UTC, CarlosJCD commented on src/js/public/menuMobile.js
> +        if(headerBackground.classList.contains("show")) {
you could refactor this event listener to its own function.

2023-09-24 03:42 UTC, CarlosJCD commented on src/js/public/menuMobile.js
> +            navigation.classList.add("show");
this four lines of this else statement could be its own function.

2023-09-24 03:42 UTC, CarlosJCD commented on src/js/public/menuMobile.js
> +        if(headerBackground.classList.contains("show")) {
you could change this to a function with a more intention revealing name

2023-09-24 03:52 UTC, CarlosJCD reviewed
Also a found a resolution where the navbar is not visible. I do not know if it is just in my computer, please check it out.
<img width="777" alt="Screenshot 2023-09-23 at 21 49 27" src="https://github.com/loopcrack-org/Kinub/assets/89323622/99c88a46-9298-4827-afd5-700b711a7b12">

2023-09-24 20:54 UTC, CarlosJCD approved these changes
excellent work, it is a lot more readable now!

2023-09-24 21:06 UTC, FernandoJoachin reviewed
Have you already solved the navigation problem?
Because what happens to me is that at a resolution lower than 767px the navigation is not visible.

[![imagen-2023-09-24-150241256.png](https://i.postimg.cc/3r6rJ4tW/imagen-2023-09-24-150241256.png)](https://postimg.cc/s1YCTXdR)

2023-09-26 00:02 UTC, CheloChidoone requested changes
Good Job @CarlosMay7, I didn't see the error @CarlosJCD and @FernandoJoachin mentioned about the navbar not being visible, for me it was visible in those resolutions, I tested in Chrome, Edge, and Firefox. I left some comments so you can improve the organization and simplify some parts of your .js

2023-09-29 04:37 UTC, Cristianpan commented
@CheloChidoone , Yes there is a small bug with the navigation bar. I'v attached a demo video of the bug.
[navbar bug](https://youtu.be/hW53pP0f3Y4).

I've been checking the mobileMenu.js script and found the "error". In this function I consider that it wouldn't be entirely correct to use  [`document.body.clientWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth)
, perhaps it would be better to use [`window.innerWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth).

```js 
function isMobile(){
    const displayWidth = document.body.clientWidth;
    return displayWidth<768;
}
```

2023-09-29 04:38 UTC, Cristianpan commented
> Good Job @CarlosMay7, I didn't see the error @CarlosJCD and @FernandoJoachin mentioned about the navbar not being visible, for me it was visible in those resolutions, I tested in Chrome, Edge, and Firefox. I left some comments so you can improve the organization and simplify some parts of your .js

@CheloChidoone , Yes there is a small bug with the navigation bar. I'v attached a demo video of the bug.
[navbar bug](https://youtu.be/hW53pP0f3Y4).

I've been checking the mobileMenu.js script and found the "error". In this function I consider that it wouldn't be entirely correct to use  [`document.body.clientWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth)
, perhaps it would be better to use [`window.innerWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth).

```js 
function isMobile(){
    const displayWidth = document.body.clientWidth;
    return displayWidth<768;
}
```

2023-10-12 05:35 UTC, CheloChidoone approved these changes

2023-10-13 18:31 UTC, Oswaldo-Chan approved these changes

2023-10-13 18:53 UTC, Oswaldo-Chan requested changes
Everything seems to be fine except for one thing, when I visit the page on a computer, it doesn't allow me to click on the elements of the page. This is because the `header__background` is overlaid and always visible.

2023-10-13 18:53 UTC, Oswaldo-Chan commented on src/public/sass/UI/header/_header.scss
> +    opacity: 0;
```suggestion
    visibility: hidden;
    opacity: 0;
```

2023-10-13 18:53 UTC, Oswaldo-Chan commented on src/public/sass/UI/header/_header.scss
> +      opacity: 1;
```suggestion
      visibility: visible;
      opacity: 1;
```

2023-10-14 16:05 UTC, LUGAMAFE commented on src/public/sass/UI/header/_header.scss
> +      opacity: 1;
yeap @Oswaldo-Chan thanks for the correction done!

2023-10-14 18:30 UTC, FernandoJoachin approved these changes

2023-10-14 18:35 UTC, Oswaldo-Chan approved these changes

2023-10-14 19:31 UTC, merged