KIN-242 Validation for Ladas
loopcrack-org/Kinub pull request #67
Opened 2023-09-24 20:35 UTC by FernandoJoachin

The validation of the telephone field was changed so that it validates Ladas

## Summary

### Problem

The form does not accept and valid Ladas

### Solution

Put a regular expression to accept and validate Ladas.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] The telephone field must allow placing and validating Lada.

### Testing

- [ ] Put a number with lada, for example: +52 9993777732

2023-09-24 23:18 UTC, CarlosMay7 commented on app/Validation/SupportEmailValidation.php
> +            "regex_match" => "El campo teléfono debe contener 10 dígitos numéricos y puede incluir una lada opcional"
```suggestion
            "regex_match" => "El campo teléfono debe contener 10 dígitos y puede incluir una lada opcional"
```
Todo muy bien, solo podrías cambiar esta parte ya que es algo reduntante, pues un dígito ya es numérico

2023-09-24 23:20 UTC, CarlosMay7 approved these changes

2023-09-25 01:15 UTC, LUGAMAFE requested changes
1. Guardar en Formato E.164:
Es aconsejable guardar los números en formato E.164: +CC NNNNNNNNNN, donde +CC es el código del país y NNNNNNNNNN es el número local.
El formato E.164 es estándar y es reconocido internacionalmente, lo que facilita el manejo de números internacionales.
2. No Guardar Formateo:
Evitar guardar espacios, guiones, paréntesis u otros caracteres de formateo.
El formateo se puede realizar en la aplicación al mostrar el número al usuario.
3. Lidiar con Números Locales:
Si recibes números locales sin código de país, podrías considerar agregar el código del país por defecto.
Asegurarte de que los usuarios sepan que deben ingresar el código de país si están proporcionando un número internacional.

2023-10-09 05:33 UTC, LUGAMAFE approved these changes
@FernandoJoachin hice un commit haciendo unas correcciones a tu codigo en vez de dejarte comentarios pero en resumen añadi [Async Validators](https://welisonmenezes.github.io/vanilla-validator/documentation/async-validators.html) que es parte de la documentacion del plugin que añadio @Oswaldo-Chan para mejorar la logica de lo que hiciste

2023-10-09 06:04 UTC, LUGAMAFE commented
@FernandoJoachin porfavor sube un video mostrando la demo de este PR hiciste no llenaste correctamente el template del PR ojo!

2023-10-10 03:50 UTC, Mauriciocr207 approved these changes

2023-10-10 04:11 UTC, Oswaldo-Chan approved these changes

2023-10-10 05:26 UTC, Mauriciocr207 requested changes

2023-10-10 05:26 UTC, Mauriciocr207 commented on src/public/js/support.js
> +        phoneInputField.value = phoneNumber;
I think, there´s a problem on the line 77 when it set the `phoneNumber` into `phoneInputField`. Here what I see:
First, if you try to pass to the next section of the form introducing wrong data into name and email inputs on first step of form, you clearly can not pass to the next step. 
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/a0dd8888-3385-4822-8274-004587d96c9b)

But, if you let the wrong data in the phone input, you **can pass** to next step
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/73429613-38dc-4188-8ec6-2a57833764e0)

![image](https://github.com/loopcrack-org/Kinub/assets/70463645/9e3458a9-0a53-4e46-821b-c1ccb499377d)

On the other hand, if you fill all the inputs on form, but you let the input number something like this: `123asdasdasd`, you receive a message saying your number is incorrect, but like I said before, you can pass the next step
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/f7c107e6-670b-4c16-b6e1-1e01123350fc)
and you continue filling all other inputs:
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/e85f89d3-bde9-4722-9663-2190a7ea2754)
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/8188b79b-faf2-499f-b0e9-5ed1a5ca95ac)

you recieve a message saying your email was sended
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/55373339-8c6f-4e8a-bd1e-6185d05bf80e)

And if you see the email, looks like if you have been sended a number, but you put `123asdasdasd` into your input number
![image](https://github.com/loopcrack-org/Kinub/assets/70463645/9e9a78d2-07f8-4c20-98d5-c965e1f25382)

2023-10-10 05:29 UTC, Mauriciocr207 commented on src/public/js/support.js
> +        phoneInputField.value = phoneNumber;
I forgot mentioned @LUGAMAFE @FernandoJoachin

2023-10-12 19:47 UTC, LUGAMAFE commented on src/public/js/support.js
> +        phoneInputField.value = phoneNumber;
Ready @Mauriciocr207

2023-10-12 21:08 UTC, Mauriciocr207 approved these changes

2023-10-12 21:47 UTC, CarlosJCD approved these changes

2023-10-12 22:18 UTC, merged