Kin-106 Certificates page layout
loopcrack-org/Kinub pull request #68
Opened 2023-09-26 18:11 UTC by CarlosMay7

## Summary

### Problem

The company needs a place to display all its certificates so the client can access each one

### Solution

Create a page where the company shows all the certificates and the user can take a link to each certificate

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

Each certificate will be displayed by means of a card with the following contents:

- [ ] Certificate preview

- [ ] Certificate name

- [ ] When you click on a certificate, it should redirect to a new tab with the certificate document.

- [ ] It must display a pagination

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Manually checked the links
- [ ] Manually checked the responsiveness

## Resources

## Demo

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/919d0901-b440-4932-b3e1-9fc3abf3bc8a)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/d9917fdd-4243-4fe0-8f4f-6180708a2438)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/6eb6ad45-de78-4843-b0ad-21e5c9733c83)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/208d9191-1c9b-45f2-852e-21d97b9b1a14)

## Navigation
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/98a798d0-a08d-4aab-ab27-1b5314c0f2c4)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/1f65e7d8-a0c4-4296-9e5e-4c349a7187cd)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/a0a73c68-2e1c-4c9a-afc4-886af3a91dbd)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/56c08551-fe7d-4bc3-a356-411db8eb4bf1)

2023-09-26 18:14 UTC, CarlosMay7 commented
use the bootstrap CDN while we agree on how to handle it

2023-09-26 23:47 UTC, CheloChidoone requested changes
We need to be careful with the bootstrap CDN css that you added like you mentioned and figure out what to do with it because it's affecting the style of the rest of the page, most notably in the header and the spacing between sections.

![image](https://github.com/loopcrack-org/Kinub/assets/38699927/b10568dd-b0d8-4d0e-8af2-93cb7fc9b39f)
Here in the title there needs to be more space between the header and the title of certificados and also there needs to be more space between the title certificados and the line under it, check the original design to see how the spacing should be.

![image](https://github.com/loopcrack-org/Kinub/assets/38699927/5b4f5fa7-7bf7-4fac-8ae2-f367d9be624e)
The font-weight of the names of the certifications should be a bit bolder like on the original design.

![image](https://github.com/loopcrack-org/Kinub/assets/38699927/786ae1be-d24b-4639-9bad-c51dbb9430ea)
There should be more space between the pagination buttons and the footer as well, check the original design to see the spacing for this too.

2023-09-28 23:37 UTC, CheloChidoone approved these changes
Looks much better @CarlosMay7, I also really like the new style you gave the paginator, it is nicer, be careful on the name of your PR, in this one you used some lowercase (Kin-106) letters on the ticket when the letters should always be uppercase (KIN-106)

2023-09-29 07:55 UTC, Cristianpan commented on src/public/sass/UI/_index.scss
> +@forward 'certificates';
Remember that now that the gulp configuration has been changed, you must create the CSS files for each page to avoid unnecessary loading of styles. Then I think it would be good that you make this change.

2023-09-29 07:55 UTC, Cristianpan commented on app/Views/public/certificates.php
> +<link rel="stylesheet" href="assets/css/public.min.css" type="text/css">
This path is invalid, remember that the output of the css files for the public part is now `assets/public/css/example.css`.

2023-09-30 03:41 UTC, CarlosJCD approved these changes
I really liked how the hover effect turned out. Nice job

2023-09-30 06:26 UTC, LUGAMAFE approved these changes
Change the border animation to a box shadow animation or remove the animation for the moment @CarlosMay7 please.

Good job for the moment!

2023-09-30 06:26 UTC, LUGAMAFE commented on src/public/js/menuMobile.js
> +
if this file is not used, why are you changing it?

2023-09-30 06:26 UTC, LUGAMAFE commented on src/public/sass/certificates.scss
> +    justify-content: space-between;
```suggestion
    justify-content: space-between;
    box-sizing: border-box;
    transition: box-shadow 500ms ease-in-out;
```
check the next comment

2023-09-30 06:26 UTC, LUGAMAFE commented on src/public/sass/certificates.scss
> +    }
$border-size: 3px;
    $border-blur: 0px;
    $border-spread: 0px; 

    &:hover {
        box-shadow: $border-size $border-size $border-blur $border-spread v.$aqua-blue , 
                    $border-size (-$border-size) $border-blur $border-spread v.$aqua-blue , 
                    (-$border-size) $border-size $border-blur $border-spread v.$aqua-blue , 
                    (-$border-size) (-$border-size) $border-blur $border-spread v.$aqua-blue ;
    }
    
    the animation of the border looks strange because of the grid layout, we can change the border animation to a box shadow animation for the moment

2023-09-30 17:25 UTC, CarlosMay7 commented on src/public/js/menuMobile.js
> +
I don't really know why it's changed, maybe I touched it while checking the file structure but it has the same content

2023-09-30 17:36 UTC, Cristianpan approved these changes

2023-09-30 18:58 UTC, merged