KIN-258 /implement database design
loopcrack-org/Kinub pull request #73
Opened 2023-09-30 03:03 UTC by CarlosJCD

## Summary

### Problem

What problem does this pull request aim to solve? Include relevant motivation and context.

### Solution

How does this pull request solve that problem? List any dependencies that are required for this change.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] Requirement A
- [ ] Requirement B

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Test A
- [ ] Test B

## Resources

- [Technical Design Document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/$END_POINT)

## Demo

If applicable, include screenshots and/or screen recordings associated with your solution

2023-09-30 03:17 UTC, CarlosJCD commented
The size of the PR is due to the number of changes made to many files, however, these changes were structured in commits so that it can be easier to review and the changes made were only name corrections so that they can match with the implemented database

2023-09-30 21:22 UTC, CheloChidoone commented on app/Models/CategoryModel.php
> +    protected $allowedFields    = ["name", "imageId", "iconId"];
Estos tres creo que deberian ser `categoryName`, `categoryImageId` y `categoryIconId`

2023-09-30 21:24 UTC, CheloChidoone requested changes
Check my comment @CarlosJCD and don't forget to add the corresponding labels to your PR.

2023-09-30 21:30 UTC, LUGAMAFE approved these changes

2023-10-03 22:46 UTC, CheloChidoone approved these changes

2023-10-06 05:40 UTC, FernandoJoachin approved these changes

2023-10-06 06:15 UTC, CarlosMay7 approved these changes

2023-10-07 03:42 UTC, FernandoJoachin approved these changes

2023-10-07 03:43 UTC, merged