Task/kin 239/fix routes language
loopcrack-org/Kinub pull request #76
Opened 2023-09-30 13:26 UTC by Mauriciocr207

## Summary

### Problem

There is inconsistency on some routes in relation to the language used. Some routes need to be defined in Spanish.

### Solution

Change the project routes to spanish if required or make a more descriptive routes; This on documentation and in project.

## Acceptance Criteria

### Requirements checklist

- [x] The routes on the routes document must be changed to be all on spanish.
- [x] The already implemented routes must be changed according to the updated routes document.

### Testing

- [x] In order to test routes on project, there´s a list with routes changed below. For test the route it´s necessary to access to all routes.

- `GET` `/login`
- `GET` `/password_reset`
- `GET` `/password_reset/(:any)`
- `POST` `/login`
- `POST` `/password_reset`
- `POST` `/password_reset/(:any)`
- `POST` `/logout`
- `GET` `/home/editar`
- `POST` `/home/editar`
- `GET` `/soluciones`
- `GET` `/soluciones/crear`
- `POST` `/soluciones/crear`
- `GET` `/soluciones/editar/(:num)`
- `POST` `/soluciones/editar/(:num)`
- `POST` `/soluciones/borrar`
- `GET` `/categorias`
- `GET` `/categorias/crear`
- `POST` `/categorias/crear`
- `GET` `/categorias/editar/(:num)`
- `POST` `/categorias/editar/(:num)`
- `POST` `/categorias/borrar`

2023-09-30 18:45 UTC, Cristianpan approved these changes

2023-09-30 18:57 UTC, FernandoJoachin requested changes
[![imagen-2023-09-30-125348089.png](https://i.postimg.cc/rmDMVY5J/imagen-2023-09-30-125348089.png)](https://postimg.cc/34QP91S4)
Ya no funciona el boton de cerrar sesión, hay que actualizar la ruta

2023-09-30 21:27 UTC, LUGAMAFE approved these changes
Apart from the logout problem, everything seems to be in order.

2023-10-04 00:42 UTC, CheloChidoone approved these changes

2023-10-06 05:46 UTC, FernandoJoachin approved these changes

2023-10-06 06:14 UTC, CarlosMay7 approved these changes

2023-10-07 01:56 UTC, merged