KIN-97 product page layout
loopcrack-org/Kinub pull request #87
Opened 2023-10-17 13:09 UTC by CarlosMay7

## Summary

### Problem

The company needs a place where it details the characteristics of a specific product

### Solution

Making a specific product page where the features of each specific product are detailed

## Acceptance Criteria

### Requirements checklist

- [ ] It must have a header with its related category and category image

- [ ] It must have an image/video carousel section.

- [ ] It must have a detailed product info section.

- [ ] It must have a “more info“ button

- [ ] It must have a navigation bar, that leads to the downloads, description and technical info sections

- [ ] It must have a section with the product description

- [ ] It must have a technical description section.

- [ ] It must have a download section.

### Testing

- [ ] Manually checked the navigation bar links
- [ ] Manually checked the video playing
- [ ] Manually checked the download area functionality

## Resources

## Demo

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/866126e4-fd44-4e9a-9d45-bb664433e96b)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/bd3c3d3a-ab6c-446d-8d43-feda8ddbbb55)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/9fee9c16-198f-40c1-9e1f-16f533937aae)

![image](https://github.com/loopcrack-org/Kinub/assets/97546829/183da283-cf25-4356-ba63-bec7898b8746)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/2bfffa84-5c79-4275-aad4-3544b98d0ae9)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/498d54f1-8ba2-484b-b846-b268ae3ed674)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/5b8c6637-549c-470f-a964-9096d3d3e757)
![image](https://github.com/loopcrack-org/Kinub/assets/97546829/b96a5116-6a7b-44e7-b566-af763c6d0a55)

2023-10-17 23:53 UTC, CheloChidoone requested changes
It's a really good start @CarlosMay7, here are some things to correct.

- Here the text is too clumped together in between each detail subtitle, for example in the first one there should be a space between `Frecuencia:` and `Lorem....` because you can see it looks pasted together without that spacing, and the same with all the other details. 
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/ca2e5a4a-08ae-47fd-bfac-e9d5e56b0f02)

- In the new navigation when clicking on `Descripcion` or `Especificaciones Tecnicas` some of the content of those sections hide, we need to make it so we see the section starting from the section title when we click without it hiding behind the header and nav.
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/20dfae7e-a29a-40a0-9dcb-238fc9ab22df)
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/bf1b2275-0dae-43df-b690-e5793241341d)

- In the new navigation you are still missing what Luis told you about that the light blue background should activate in each option only when that current section is active or visible in the page.

2023-10-21 01:05 UTC, CarlosJCD requested changes
Excellent work!. However i think there is a small detail that could be improved.

In the product navbar there is a small gap between the product navbar and the public view navbar. However it should be noted that this only the case on the safari web browser. 

<img width="1496" alt="Screenshot 2023-10-20 at 18 53 24" src="https://github.com/loopcrack-org/Kinub/assets/89323622/6348592a-9d0b-401c-a81d-3a2f7bd8cfd6">


I tested on Chrome 117.0.5938.92 and Safari 17.0 (19616.1.27.211.1)

2023-11-02 15:29 UTC, CarlosMay7 commented
Image carousel will be fixed in its own pull request

2023-11-03 00:50 UTC, LUGAMAFE commented
@Oswaldo-Chan if you were working on this or made commits to this repo you should not be approving the PR since some of the work is yours.

2023-11-03 15:17 UTC, FernandoJoachin reviewed
[![imagen-2023-11-03-091315139.png](https://i.postimg.cc/59CMPXYh/imagen-2023-11-03-091315139.png)](https://postimg.cc/Sjk5RNGd)

In the download area section, the items brochure, datasheet, and certificates do not have 'text-decoration: underline

[![imagen-2023-11-03-092253114.png](https://i.postimg.cc/Pq1tFKq8/imagen-2023-11-03-092253114.png)](https://postimg.cc/jWd0DHPs)
Furthermore, the images don't load for me in Chrome, but they do in Firefox.

2023-11-03 17:35 UTC, LUGAMAFE requested changes
Buen trabajo chicos solo hay que mejorar los nitpicks que deje!

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/UI/header/_header.scss
> +@use '../../base/mixins' as m;
```suggestion
@use 'sass:color';
@use '../../base/variables' as v;
@use '../../base/mixins' as m;
```


@CarlosMay7 the problem that you had is because you were not importing the sass:color utils

https://sass-lang.com/documentation/modules/
https://sass-lang.com/documentation/modules/color/

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/UI/header/_header.scss
> +}
```suggestion
```
Remove all this use color.adjust instead

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/UI/header/_header.scss
> +      background-color: custom-darken(v.$bright-blue, 20%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/UI/header/_header.scss
> +      color: custom-darken(v.$bright-blue, 20%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +}
```suggestion
```
Remove all this use color.adjust instead

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +    color: custom-darken(v.$gray, 20%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +      color: custom-darken(v.$gray, 10%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +  background-color: custom-darken(v.$bright-blue, 20%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +    background-color: custom-darken(v.$bright-blue, 20%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +    color: custom-darken(v.$bright-blue, 10%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +    color: custom-darken(v.$light-gray, 35%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +      color: custom-darken(v.$gray, 10%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +    color: custom-darken(v.$light-gray, 35%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/product.scss
> +      color: custom-darken(v.$gray, 10%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/sass/UI/header/_header.scss
> +        color: custom-lighten(v.$bright-blue, 20%);
use color.adjust please

2023-11-03 17:35 UTC, LUGAMAFE commented on src/public/js/product-page.js
> +createScrollMagicScene('#download-area', 'download-area', 'onCenter', '50%');
```suggestion
// Suponiendo que tienes una lista de secciones y un navbar con enlaces
const sections = document.querySelectorAll('.product-info');
const navLinks = document.querySelectorAll('.product-navigation__link-container');

// Función para actualizar el link activo
const updateActiveLink = (sectionId) => {
  navLinks.forEach((link) => {
    link.classList.remove('product-navigation__link-container--active');
    const href = link.getAttribute('href');
    if (href === `#${sectionId}`) {
      link.classList.add('product-navigation__link-container--active');
    }
  });
};

// Crear una escena ScrollMagic para cada sección
sections.forEach((section, index) => {
  let triggerHookValue = 0.5; // "Es lo mismo que onCenter" Valor predeterminado para la mayoría de las secciones

  // Si es la última sección, ajusta el triggerHook
  if (index === sections.length - 1) {
    triggerHookValue = 0.7;
  }
  new ScrollMagic.Scene({
    triggerElement: section, // elemento que dispara la escena
    duration: '100%', // la escena dura mientras el elemento está en el viewport
    triggerHook: triggerHookValue, // inicia la escena cuando el elemento está en el medio de la ventana
  })
    .on('enter', () => {
      section.classList.add('product-info--active');
      updateActiveLink(section.id);
    })
    .on('leave', (event) => {
      // Cuando la sección 'deja' el punto de disparo, queremos desactivar su enlace correspondiente
      // solo si estamos yendo hacia arriba en la página y el índice es mayor que 0
      if (event.scrollDirection === 'REVERSE' && index > 0) {
        const previousSectionId = sections[index - 1].id;
        updateActiveLink(previousSectionId);
        section.classList.remove('product-info--active');
      }
    })
    .addTo(controller); // añadir la escena al controlador
});
```
@Oswaldo-Chan i made a refactor of this code please check that it works correctly and now we can se the download-section active on all screen sizes

2023-11-03 17:36 UTC, Cristianpan requested changes

2023-11-03 18:02 UTC, LUGAMAFE requested changes
Other change

2023-11-03 18:02 UTC, LUGAMAFE commented on src/public/sass/UI/product/_product-info.scss
> +  scroll-margin-top: 11rem;
```suggestion
  scroll-margin-top: 13rem;
```
Add more margin on mobile views please

2023-11-03 20:07 UTC, CarlosJCD reviewed
The product navbar doesnt seem to work quite well on the safari browser:

- When maxed zoom out, the `areas de descarga` section doesn't get lighted on, as well as the navbar logo slightly overflows the page navbar.
Video: [https://drive.google.com/file/d/1n32RRLtTs-TXdJC9ecaZl6WYBJWBjuWe/view?usp=sharing](https://drive.google.com/file/d/1n32RRLtTs-TXdJC9ecaZl6WYBJWBjuWe/view?usp=sharing)

- When the zoom is default (100%) and i scroll constantly up and down it gets kinda broken the product navbar and it doesn't light up the correspondent section. This happens on safari and chrome as well. I am not sure how much of an issue is this, but i felt like i should note it.
Video: [https://drive.google.com/file/d/1mBucusLhBWpgLsV_2T6jOfC5NOP9FphV/view?usp=sharing](https://drive.google.com/file/d/1mBucusLhBWpgLsV_2T6jOfC5NOP9FphV/view?usp=sharing)


I am not sure if these are really important issues, but I have decided to at least comment on them. @LUGAMAFE

2023-11-03 22:33 UTC, Mauriciocr207 requested changes

2023-11-03 22:33 UTC, Mauriciocr207 commented on src/public/js/product-page.js
> +createScrollMagicScene('#download-area', 'download-area', 'onCenter', '50%');
This recommendations are good, declare links and sections as constants at the top of the script. Also, I see a strange behavior when you scroll to the last section. 
If you go to the last section, the respective link "Área De Descarga" turn on, but if you goes up a little, then the link "Descripción" turn on. Maybe this is for the `triggerHook` variable you pass. Maybe with the @LUGAMAFE recomendations this behavior dissapear.
![Captura de pantalla (1370)](https://github.com/loopcrack-org/Kinub/assets/70463645/351ae918-b1b0-48e6-8b1a-453683de5e1f)
In the screenshot before, you can see that i´m on the "Especificaciones Técnicas" section, but it is the "Descripción" section who is turn on.

2023-11-03 22:33 UTC, Mauriciocr207 commented on app/Views/public/product.php
> +</nav>
Same for product navigation

2023-11-03 22:33 UTC, Mauriciocr207 commented on app/Views/public/product.php
> +            <h2 class="details__heading">Medidor de nivel de radar 80G</h2>
This maybe needs a container because when you zoom out you can see that the `details__information` section goes to right a lot
![Captura de pantalla (1369)](https://github.com/loopcrack-org/Kinub/assets/70463645/11a009a0-444d-483c-9747-91a29ad77a80)

2023-11-03 22:35 UTC, Mauriciocr207 requested changes

2023-11-03 22:35 UTC, Mauriciocr207 commented on src/public/js/product-page.js
> +createScrollMagicScene('#download-area', 'download-area', 'onCenter', '50%');
> @Oswaldo-Chan i made a refactor of this code please check that it works correctly and now we can se the download-section active on all screen sizes

This recommendations are good, declare links and sections as constants at the top of the script. Also, I see a strange behavior when you scroll to the last section. 
If you go to the last section, the respective link "Área De Descarga" turn on, but if you goes up a little, then the link "Descripción" turn on. Maybe this is for the `triggerHook` variable you pass. Maybe with the @LUGAMAFE recomendations this behavior dissapear.
![Captura de pantalla (1370)](https://github.com/loopcrack-org/Kinub/assets/70463645/351ae918-b1b0-48e6-8b1a-453683de5e1f)
In the screenshot before, you can see that i´m on the "Especificaciones Técnicas" section, but it is the "Descripción" section who is turn on.

2023-11-04 06:28 UTC, Oswaldo-Chan commented
> [![imagen-2023-11-03-091315139.png](https://camo.githubusercontent.com/9751ad766d3e916f23f9fcc5ba3430fd5730bf97030b82e5e67c74988111568a/68747470733a2f2f692e706f7374696d672e63632f3539434d505859682f696d6167656e2d323032332d31312d30332d3039313331353133392e706e67)](https://postimg.cc/Sjk5RNGd)
> 
> In the download area section, the items brochure, datasheet, and certificates do not have 'text-decoration: underline
> 
> [![imagen-2023-11-03-092253114.png](https://camo.githubusercontent.com/5bdda6374f7de66aae6442da07b80f70b01703b23cd2297d66bbcd587fd55fe8/68747470733a2f2f692e706f7374696d672e63632f50713174464b71382f696d6167656e2d323032332d31312d30332d3039323235333131342e706e67)](https://postimg.cc/jWd0DHPs) Furthermore, the images don't load for me in Chrome, but they do in Firefox.

2023-11-06 17:40 UTC, CarlosJCD reviewed
Perfect!, I really like the final design. Just a little observation, I am not really sure that the tags should be anchors. Having the tags as anchors can mislead the user to think that something will happen if the tag is clicked on. I believe it would be better if it is changed to be just text.

2023-11-07 00:04 UTC, Mauriciocr207 requested changes
I see when you click over the description button, in some screen sizes (for example when you zoom out to 90% on chrome navigator), the button doesn´t  change its color. Probably because the hook set on javascript doesn´t activate due the size and the color never changes. It needs more logic to solve it, but it let it as a comment. 
![Captura de pantalla (1401)](https://github.com/loopcrack-org/Kinub/assets/70463645/3ab08f28-3017-4dfd-8398-abdad84c8537)

Also I see that the ``product_info` container goes to right a lot, as I commented in other request changes when the screen size is big.
![Captura de pantalla (1369)](https://github.com/loopcrack-org/Kinub/assets/70463645/35cf63b3-0e1d-4c7e-97ea-e83cb0269497)

CC: @CheloChidoone

2023-11-07 00:14 UTC, CheloChidoone reviewed
It's looking much better @CarlosMay7, but check Mau's comments and don't just mark them as solved.

2023-11-08 03:22 UTC, LUGAMAFE commented
> Perfect!, I really like the final design. Just a little observation, I am not really sure that the tags should be anchors. Having the tags as anchors can mislead the user to think that something will happen if the tag is clicked on. I believe it would be better if it is changed to be just text.

@CarlosJCD tags will take you to the categories page and automatically select the tag

2023-11-08 04:16 UTC, LUGAMAFE commented
> Image carousel will be fixed in its own pull request

https://github.com/loopcrack-org/Kinub/pull/87#issuecomment-1790961455

Hey I approve this, fix this later on his own ticket.

CC: @CheloChidoone @Mauriciocr207

2023-11-08 04:59 UTC, LUGAMAFE requested changes

2023-11-08 04:59 UTC, LUGAMAFE commented on src/public/js/product-page.js
> +  }
> I see when you click over the description button, in some screen sizes (for example when you zoom out to 90% on chrome navigator), the button doesn´t change its color. Probably because the hook set on javascript doesn´t activate due the size and the color never changes. It needs more logic to solve it, but it let it as a comment. ![Captura de pantalla (1401)](https://user-images.githubusercontent.com/70463645/280877979-3ab08f28-3017-4dfd-8398-abdad84c8537.png)
> https://github.com/loopcrack-org/Kinub/pull/87#pullrequestreview-1716542142

![image](https://github.com/loopcrack-org/Kinub/assets/24960025/fa65597d-42b5-4f5a-9f79-39aba5430476)

@Mauriciocr207 this is not a bug. This is how the scroll magic plugin works, basically there is a invisible division in the viewport (50%) so whenever the purple line or the specific top section reaches the green line, automatically trigger a new tab change. 

We can fix that bug adding this code:

```suggestion
  const mediaQuery = window.matchMedia('(min-width: 1920px)');
  let triggerHookValue = 0.5;
  if (mediaQuery.matches) triggerHookValue = 0.3;
  if (index === sections.length - 1) {
    triggerHookValue = 0.7;
  }
```

2023-11-08 04:59 UTC, LUGAMAFE commented on src/public/sass/UI/product/_product-info.scss
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/dd8079f0-efed-47c4-8b79-a5a19993b4dc)

Change the colors please before merge.

2023-11-08 23:40 UTC, Mauriciocr207 commented
> > Image carousel will be fixed in its own pull request
> 
> [#87 (comment)](https://github.com/loopcrack-org/Kinub/pull/87#issuecomment-1790961455)
> 
> Hey I approve this, fix this later on his own ticket.
> 
> CC: @CheloChidoone @Mauriciocr207

2023-11-08 23:50 UTC, CheloChidoone approved these changes

2023-11-08 23:50 UTC, Mauriciocr207 approved these changes
I aprove this pull request knowing the request changes on comment https://github.com/loopcrack-org/Kinub/pull/87#pullrequestreview-1716542142 are going to be fixed on other pull request

2023-11-09 00:27 UTC, CarlosJCD approved these changes
Nice Work!

2023-11-11 16:38 UTC, LUGAMAFE approved these changes
Nice Job @CarlosMay7 @Oswaldo-Chan!!

2023-11-12 20:45 UTC, Cristianpan approved these changes
Nice Job!! 👌

2023-11-12 21:07 UTC, merged