KIN-143 delete user alert
loopcrack-org/Kinub pull request #88
Opened 2023-10-17 13:58 UTC by FernandoJoachin

## Summary

### Problem

The project requires being able to give a warning before deleting a user via the users page.

### Solution

Create a modal window that shows an alert before deleting a user.

## Acceptance Criteria

### Requirements checklist

- [ ] It must show a modal window with a warning message saying that once the user is deleted, there is no way to recover it.
- [ ] It must have a cancel button.
- [ ] It must have a confirm button.
- [ ] It must show a response window after confirming the action, this response must indicate if the user was deleted successfully or not.

### Testing

- [ ] Delete a user

2023-10-18 00:10 UTC, CheloChidoone approved these changes
Very good @FernandoJoachin !

2023-10-20 17:24 UTC, CarlosMay7 requested changes
Very good but I left you a comment

2023-10-20 17:24 UTC, CarlosMay7 commented on src/admin/js/alert-deleteElement.js
> +        console.log("hola");
I think you forgot to remove this
```suggestion
```

2023-10-22 01:35 UTC, CarlosMay7 approved these changes

2023-10-23 05:43 UTC, Oswaldo-Chan approved these changes

2023-10-24 06:19 UTC, CarlosJCD approved these changes

2023-10-24 07:00 UTC, merged