KIN-275 create user account email
loopcrack-org/Kinub pull request #89
Opened 2023-10-17 21:23 UTC by FernandoJoachin

## Summary

### Problem

The project needs to notify the user that their account was successfully created and he need to reset their password

### Solution

Send an email to the user's email

## Acceptance Criteria

### Requirements checklist

- [ ] The email must contain a message indicating that is necessary to set a password before logging in.
- [ ] The email must have a button that redirects to the reset password page, allowing the user to set its new password

### Testing

- [ ] When creating a user it should show the message.

## Demo

[![imagen-2023-10-17-151715422.png](https://i.postimg.cc/rmnxmfXD/imagen-2023-10-17-151715422.png)](https://postimg.cc/KkTRprYb)

2023-10-18 00:16 UTC, CheloChidoone requested changes
Looks nice @FernandoJoachin, just a nitpick detail, there should be a space between the name and the last name. 
![image](https://github.com/loopcrack-org/Kinub/assets/38699927/af3aae35-f2b1-4caf-a274-2f7d8dafd4ac)

2023-10-19 22:41 UTC, CheloChidoone approved these changes

2023-10-20 17:34 UTC, CarlosMay7 approved these changes

2023-10-21 04:03 UTC, CarlosJCD approved these changes
Nice Job

2023-10-23 05:42 UTC, Oswaldo-Chan approved these changes

2023-10-23 09:18 UTC, merged