KIN-276 adapt login and reset password logic to confirmed accounts
loopcrack-org/Kinub pull request #90
Opened 2023-10-17 23:10 UTC by FernandoJoachin

## Summary

### Problem

With the user creation logic defined, we need to use a confirmed account mechanism, so we can have users set their own passwords instead of the admin user.

### Solution

Modify the login logic to check if the user account is confirmed, as well as modify the password reset logic so that the account is confirmed when the new password is set and the account has not been confirmed before.

## Acceptance Criteria

### Requirements checklist

- [ ] Validate when accounts are not confirmed

### Testing

- [ ] Sign in with an unconfirmed user
- [ ] Reset password with an unconfirmed user

## Resources

- [Technical Design Document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/$END_POINT)

## Demo

If applicable, include screenshots and/or screen recordings associated with your solution

2023-10-18 01:18 UTC, CheloChidoone requested changes
Good job @FernandoJoachin, it looks like the logic works correctly, I added a little comment about the error messages.

2023-10-18 01:18 UTC, CheloChidoone commented on app/Validation/PasswordEmailValidation.php
> +            throw new Exception("Tu cuenta no ha terminado de ser confirmada. Por favor, revisa tu correo electrónico para finalizar el proceso de confirmación de tu cuenta.");
I think the message here should be the same as the login one, it sounds better `Tu cuenta no ha sido confirmada` instead of `Tu cuenta no ha terminado de ser confirmada` because it makes me think I already started the confirmation process when I really haven't done the confirmation.
```suggestion
            throw new Exception("Tu cuenta no ha sido confirmada. Por favor, revisa tu correo electrónico para finalizar el proceso de confirmación de tu cuenta.");
```

2023-10-18 18:27 UTC, CarlosJCD reviewed
Excellent work, but please keep your PR description clean. The `Resources` and `Demo` section have the values of the PR description template. Please put its correct content, or remove those sections if there is no need of them.

2023-10-19 22:39 UTC, CheloChidoone approved these changes

2023-10-20 17:31 UTC, CarlosMay7 approved these changes

2023-10-21 04:31 UTC, CarlosJCD approved these changes
Thanks for the changes on the pr description. Nice Work

2023-10-23 05:43 UTC, Oswaldo-Chan approved these changes

2023-10-24 06:23 UTC, CarlosJCD approved these changes

2023-10-24 07:05 UTC, merged