KIN-269 Integration of database migrations
loopcrack-org/Kinub pull request #92
Opened 2023-10-18 07:29 UTC by CarlosJCD

## Summary

### Problem

It was needed to use a way more scalable and maintainable method for creating and modifying the database than an sql script.

### Solution

Implementing codeIgniter 4 migrations for database creation

## Acceptance Criteria

### Requirements checklist

- [ ] It must create all the same tables as the [sql script on the backups directory.](https://github.com/loopcrack-org/Kinub/blob/3210d00badba1353efa01d43d338e8df7eea8332/backup/Database.sql)
- [ ] The actual seeders (`UserSeeder`, `CategorySeeder`, `CategoryTagSeeder`, `EmailSeeder`) must work with the generated tables of the migrations file.

### Testing

#### IMPORTANT:

It is needed to first execute this sql script with your DBMS so that the seeders can work. This is planned to be fixed in a future PR, but right now this script is necessary to test the seeders.
```sql
INSERT INTO `email_types` (`emailTypeId`, `emailTypeName`) VALUES
(1, 'contacto'),
(2, 'soporte tecnico'),
(3, 'info producto');

INSERT INTO `files` (`fileId`, `fileRoute`, `uuid`, `fileName`, `fileDirectoryRoute`) VALUES
(1, '/assets/images/auth-one-bg.jpg', '79c4387d-c1cb-4e6f-b418-8c391d852e2c', 'auth-one-bg.jpg', '/assets/images/'),
(2, '/assets/images/drop.svg', '9d7b76e0-a31f-4e0f-9ac6-b71bc35f2ed4', 'drop.svg', '/assets/images/');

```

#### Testing Steps:

- [ ] Validate that the migrations file work by dropping your actual database and on the command line run: 
```sql 
php spark migrate
````
- [ ] Validate that the seeders are still working by using each of them:
    - [ ] User seeder
    ```sql
    php spark db:seed UserSeeder
    ```

    - [ ] Category Seeder
    ```sql
    php spark db:seed CategorySeeder
    ```

    - [ ] Category Tag Seeder
    ```sql
    php spark db:seed CategoryTagSeeder
    ```

    - [ ] Email Seeder
    ```sql
    php spark db:seed EmailSeeder
    ```

## Resources

- [Database Design Document](https://loopcrack.atlassian.net/wiki/spaces/Kinub/pages/1277953/Database+Design)

## Demo

<img width="652" alt="Screenshot 2023-10-18 at 1 27 58" src="https://github.com/loopcrack-org/Kinub/assets/89323622/98ed4dce-7544-41bc-ab33-4f352d280218">

2023-10-21 01:11 UTC, CheloChidoone requested changes
It looks good @CarlosJCD, I left you a comment about a small error that I think should be fixed

2023-10-21 01:11 UTC, CheloChidoone commented on app/Database/Migrations/2023-10-17-220959_Categories.php
> +                'null'           => false,
@CarlosJCD I don't think this line is necessary, this is the only id of any table where you added this line but it shouldn't be necessary.

2023-10-21 18:53 UTC, CheloChidoone approved these changes
Great Job @CarlosJCD!

2023-10-21 22:07 UTC, Cristianpan approved these changes

2023-10-24 22:41 UTC, CheloChidoone requested changes

2023-10-24 22:41 UTC, CheloChidoone commented on app/Database/Migrations/2023-10-17-224407_Users.php
> +            'isConfirmed' => [
@CarlosJCD I just noticed something new, now that @FernandoJoachin has added changes to the login logic from the ticket `KIN-276` this field from your migrations breaks the login and other new validations from that ticket; We need to decide if the field is now going to be `isConfirmed` then we need a new ticket for @FernandoJoachin to correct the login logic, the other option is that the name of this field stays just as `confirmed` like before.

CC: @LUGAMAFE @FernandoJoachin

2023-10-24 23:01 UTC, CarlosJCD commented on app/Database/Migrations/2023-10-17-224407_Users.php
> +            'isConfirmed' => [
My mistake!, I will change it back to `confirmed` asap

2023-10-25 21:10 UTC, CheloChidoone approved these changes

2023-10-26 19:27 UTC, CarlosMay7 approved these changes

2023-10-27 05:09 UTC, Mauriciocr207 reviewed
I see that the migrations do not generate the onDeleteCascase or the Collation to utf8mb4_unicode_c. Is this the expected behavior?

2023-10-27 06:35 UTC, CarlosJCD commented
> All good but I see that the migrations do not generate the onDeleteCascase or the Collation to utf8mb4_unicode_c. Is this the expected behavior?

no it is not!, it is supposed to generate a utf8mb4_unicode_c collation and the delete and update options are not supposed to be empty. I will fix it right away, thanks for the comment.

2023-10-27 16:58 UTC, LUGAMAFE requested changes
Hey @CarlosJCD could you delete the backup .sql file then if we now are going to use the migrations please

2023-10-27 16:58 UTC, LUGAMAFE commented on app/Database/Seeds/UserSeeder.php
> +                'isConfirmed'   => 1,
Based on what you discussed with Marcelo this field now should be called only `confirmed`. Cause this seed is not working. 
```suggestion
                'confirmed'   => 1,
```

2023-10-27 16:58 UTC, LUGAMAFE commented on app/Database/Seeds/UserSeeder.php
> +                'isConfirmed'   => 0,
Same comment as above

2023-10-27 17:07 UTC, Oswaldo-Chan approved these changes

2023-10-27 17:21 UTC, LUGAMAFE approved these changes
Ready @CarlosJCD thanks!

2023-10-27 17:42 UTC, merged