KIN-268 add delete user functionality
loopcrack-org/Kinub pull request #96
Opened 2023-10-24 14:21 UTC by FernandoJoachin

## Summary

### Problem

As an administrator of the admin panel, I need to be able to delete the records of the users so that I can restrict the access to those who i decide to delete. 

### Solution

Add functionality in controllers to delete users.

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] It must delete the register from the database
- [ ] It must return a response to the view indicating if it was successfully deleted or if it was an error on deleting the user.

### Testing

Describe any tests (manual or automated) executed to verify your changes

- [ ] Delete a user. Delete a user. This action should be reflected in the database and in the view.

2023-10-24 23:15 UTC, CheloChidoone approved these changes
It works well @FernandoJoachin, please remember to add everyone as reviewers for your PR because it looks like you forgot that this time but good job.

2023-10-25 17:14 UTC, CarlosMay7 approved these changes
Good Job! Just check the testing message, I think you repeated the first part of it

2023-10-26 05:43 UTC, CarlosJCD requested changes
There is a couple of issues with your current PR:

- On a mac device, the confirm alert when deleted an account or either it is not displayed or either it is displayed as an error even if the user was actually deleted.
- We should not be able to delete the account we are logged into, and furthermore an administrator account should not be able to be deleted.

2023-10-28 16:53 UTC, CarlosJCD approved these changes
Excellent work!

2023-10-29 00:26 UTC, CheloChidoone requested changes
@FernandoJoachin We found some changes for you to check

CC: @Mauriciocr207

2023-10-29 00:26 UTC, CheloChidoone commented on app/Controllers/CtrlUser.php
> +        if (! empty($user)) {
@FernandoJoachin Check that the user is not the super admin when deleting, even if the superadmin isn't on the users table the validation should also be done here just in case.

CC: @Mauriciocr207

2023-10-29 00:26 UTC, CheloChidoone commented on app/Views/admin/users/Users.php
> +                                    <?php if ($user['confirmed'] !== '1') { ?>
@FernandoJoachin This is wrong, I think you could filter out the superadmin user from the consultation instead of here on the view, but this is wrong anyway confirmed is not the correct field to filter out the superadmin.

CC: @Mauriciocr207

2023-10-29 00:30 UTC, Mauriciocr207 commented on app/Controllers/CtrlUser.php
> +        if (! empty($user)) {
Also, in your app/Controllers/CtrlUser.php you have
 ```php
public function viewUsers()
    {
        $userModel = new UserModel();
        $users     = $userModel->findAll();

        return view('admin/users/Users', ['users' => $users]);
    }
```
But you can modify the consult to not show the admin user, something like this
 ```php
public function viewUsers()
    {
        $userModel = new UserModel();
        $users     = $userModel->where("isAdmin", "0")->findAll();

        return view('admin/users/Users', ['users' => $users]);
    }
```

2023-10-29 20:01 UTC, Mauriciocr207 approved these changes

2023-10-29 20:01 UTC, Mauriciocr207 commented on src/admin/js/deleteElement.js
> +      const deleteButtonModal = document.getElementById('elementId');
Maybe here it´s better use 
```javascript
document.querySelector("#elementId");
```
querySelector is more remcomended for this situation.

2023-10-29 20:01 UTC, Mauriciocr207 commented on src/admin/js/deleteElement.js
> +      console.log(deleteButtonModal);
Don´t forget the `console.log`

2023-10-31 03:04 UTC, CheloChidoone approved these changes

2023-10-31 04:05 UTC, LUGAMAFE commented on src/admin/js/deleteElement.js
> +      const deleteButtonModal = document.getElementById('elementId');
No difference that is opinated recomendation

2023-10-31 04:06 UTC, LUGAMAFE approved these changes

2023-10-31 04:06 UTC, LUGAMAFE commented on src/admin/js/deleteElement.js
> +      console.log(deleteButtonModal);
Yes please @FernandoJoachin delete this

2023-11-01 15:28 UTC, CarlosMay7 approved these changes

2023-11-01 16:17 UTC, LUGAMAFE commented
@FernandoJoachin can we close this PR please

2023-11-02 15:31 UTC, CarlosMay7 approved these changes

2023-11-02 15:31 UTC, merged