KIN-267 do the create user functionality
loopcrack-org/Kinub pull request #97
Opened 2023-10-25 15:17 UTC by FernandoJoachin

## Summary

### Problem

As an admin panel administrator, I want to create a new user so that they have access to the admin panel.

### Solution

Create a new user creation form to register new users.

## Acceptance Criteria

### Requirements checklist

- [ ] It must validate the form inputs to not be empty.
- [ ] It must validate that the email has not been previously registered.
- [ ] It must return to the view a response indicating success in signing up a new user or, in case of being errors, it must return the errors.
- [ ] it must set a token for the reset password functionality.
- [ ] it must set null the user password.
- [ ] It must send an email to the user email account notifying him that it's account was created and it is needed to set a password.

### Testing

- [ ] Create a user. When creating the user it should show a success or error alert
- [ ] Enter an email that has already been registered in the database.
- [ ] Check that the created user cannot log in unless confirmed.
- [ ] Check that the email was sent correctly.

2023-10-25 20:07 UTC, CarlosMay7 requested changes
When I create an account and I have not assigned the password I must not be able to reset it but I can do it and I receive the mail as well, but when I click the set password link an error shows up

2023-10-26 05:08 UTC, CarlosJCD requested changes
Nice work!, however we detected an small bug when testing this feature:

- After loggin in with the admin account on the admin panel, if you directly go to create user and you create a valid user, Even if the emal to confirm password is sent and the user record is registered on the database, it does not shows the response confirming success and it does not occurs the redirection to the user page. This only happens with the first user created when loggin in.

2023-10-27 03:13 UTC, FernandoJoachin commented
> Nice work!, however we detected an small bug when testing this feature:
> 
> * After loggin in with the admin account on the admin panel, if you directly go to create user and you create a valid user, Even if the emal to confirm password is sent and the user record is registered on the database, it does not shows the response confirming success and it does not occurs the redirection to the user page. This only happens with the first user created when loggin in.

You're sure? Do you run the run dev command previously?

2023-10-27 17:24 UTC, CarlosJCD approved these changes

2023-10-28 13:02 UTC, CarlosMay7 approved these changes

2023-10-29 00:56 UTC, Mauriciocr207 commented on app/Controllers/CtrlUser.php
> +        }
I see that the edit user functionality can´t be reviewed because there is not a view for that functionality. Also, I think this feature is not part of this pull request.

CC: @CheloChidoone

2023-10-29 00:58 UTC, CheloChidoone commented on app/Controllers/CtrlUser.php
> +        }
@FernandoJoachin You shouldn't mix up what you are doing for each ticket, this PR should only have the create functionality and the other one KIN-285 should have only the edit functionality but you have everything in both.

2023-10-31 04:17 UTC, Cristianpan requested changes

2023-10-31 04:17 UTC, Cristianpan commented on app/Controllers/CtrlUser.php
> +                'message' => 'La cuenta se ha creado con éxito. Por favor, revise su correo electrónico para establecer su contraseña.',
The response to this message isn't correct. This should be something like "Por favor notifique al usuario para que revise su bandeja de entrada y confirme su cuenta"

2023-10-31 04:37 UTC, LUGAMAFE requested changes
Same comment as @Mauriciocr207 and @CheloChidoone https://github.com/loopcrack-org/Kinub/pull/97#discussion_r1375342913 we should avoid combine other tickets

2023-10-31 04:37 UTC, Cristianpan requested changes

2023-10-31 04:37 UTC, Cristianpan commented on app/Controllers/CtrlUser.php
> +            $token             = uniqid();
For this, create a Util class like TokerGegerator and create a method that does this functionality.

2023-10-31 16:27 UTC, CheloChidoone approved these changes
Thanks for the changes @FernandoJoachin, good job!

2023-11-01 01:01 UTC, LUGAMAFE approved these changes
Ready! thanks @FernandoJoachin

2023-11-01 16:17 UTC, LUGAMAFE commented
@FernandoJoachin can we close this PR please

2023-11-01 16:41 UTC, LUGAMAFE reviewed
Please correct this before merge the branch

2023-11-01 16:41 UTC, LUGAMAFE commented on app/Views/admin/users/UserCreate.php
> +<script src="/assets/admin/js/particles.app.min.js"></script>
```suggestion

```
Hey @FernandoJoachin me and @Cristianpan noticed that we dont need these scripts please remove them

2023-11-02 23:50 UTC, Cristianpan approved these changes

2023-11-03 13:09 UTC, merged