KIN-285 edit user functionality user page
loopcrack-org/Kinub pull request #98
Opened 2023-10-27 03:08 UTC by FernandoJoachin

## Summary

### Problem

As the administrator of the admin panel, I want to persist the changes made to the user credentials on the edit user view so that the changes made are stored on the database without the need of creating a new user and deleting the existing record.

### Solution

Adding the ability to modify database values to the Edit User form

## Acceptance Criteria

### Requirements checklist

Include a list of requirements necessary to consider this pull request complete

- [ ] It must validate that the given info is correct. a.The form must not be empty. b. It must validate that the email has the correct format.
- [ ] If the email was changed, it must validate that the new email it is not registered on the database.
- [ ] If it passes all validations, it must update the record on the database. a.if the email was changed, it the account must be unconfirmed and it must be sent a confirm email to the new email address.
- [ ] It must return a response to the view, the response will contain a message according to the following case: If the record was updated and the email of the user account wasn't changed, the message must indicate success on updating the user record. 
- [ ] It must return a response to the view, the response will contain a message according to the following case: If the record was updated and the email of the user account was changed, the message must indicate success on updating the user record and that it is necessary to confirm again the account. 
- [ ] It must return a response to the view, the response will contain a message according to the following case: If the new email is already registered on another account, it must return a response indicating that the new email address is already registered and because of that it is not possible to persist the changes. 
- [ ] It must return a response to the view, the response will contain a message according to the following case: If it occurred an error on the process, the message must indicate that it occurred an error and to try again later

### Testing

- [ ] Edit only first or last name fields
- [ ] Edit the email field but with one already registered
- [ ] Edit the email field with one that has not been registered

2023-10-31 16:49 UTC, CheloChidoone commented on app/Controllers/CtrlUser.php
> +                    'message' => 'La cuenta se ha actualizado con éxito. Por favor, revise su correo electrónico para establecer su contraseña.',
@FernandoJoachin Change message to this like on the create functionality `"Por favor notifique al usuario para que revise su bandeja de entrada y confirme su cuenta"`.

2023-10-31 16:50 UTC, CheloChidoone commented on app/Controllers/CtrlUser.php
> +                $POST['userToken']    = $token;
@FernandoJoachin Please use the token generator util class like you did in the create functionality too.

CC: @CarlosMay7

2023-10-31 16:51 UTC, CheloChidoone requested changes
@FernandoJoachin We left you a pair of comments to check.

CC: @CarlosMay7

2023-11-01 16:42 UTC, LUGAMAFE requested changes
@FernandoJoachin this Pr should not be open as we need to finish merge this https://github.com/loopcrack-org/Kinub/pull/97 first, also as you can notice this PR is not updated with the main branch. An it has conflicts.

2023-11-04 21:43 UTC, CarlosMay7 approved these changes

2023-11-04 21:43 UTC, CheloChidoone approved these changes
@FernandoJoachin Good job, it works well, thanks for making the changes.

2023-11-06 03:22 UTC, Oswaldo-Chan approved these changes

2023-11-06 17:53 UTC, CarlosJCD approved these changes
Nice Work!

2023-11-07 00:18 UTC, Mauriciocr207 approved these changes

2023-11-08 05:43 UTC, LUGAMAFE approved these changes
![image](https://github.com/loopcrack-org/Kinub/assets/24960025/7c4d6936-84d6-483e-8cae-5e5456d1ea43)
Hey @FernandoJoachin I found a problem related to the user table logic, a user who just confirmed his account and access to the admin panel and then to the user view, can delete himself as well as edit his own information. 
This should not be allowed. C
ould you please solve this problem in the future and ask @CarlosJCD  to create and follow up on this bug.

Good Job!

2023-11-09 19:56 UTC, merged