KIN-280: Improve database seeding
loopcrack-org/Kinub pull request #99
Opened 2023-10-27 14:35 UTC by CarlosJCD

[![KIN-280](https://badgen.net/badge/JIRA/KIN-280/blue)](https://loopcrack.atlassian.net/browse/KIN-280) ![Medium](https://badgen.net/badge/PR%20Size/Medium/yellow) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=loopcrack-org&utm_campaign=badge_info)

## Summary

### Problem

The current database seeders are confusing to use and not well designed

### Solution

Implement of better seeders as well of the implementation of a main seeder to run all of them.

## Acceptance Criteria

### Requirements checklist

- [x] All the seeders must run on the `InitSeeder`
- [x] There must be a seeder for each table on the database

### Testing

- [x] Run `php spark migrate:refresh` to empty the database on your CLI.
- [x] Then run `php spark db:seed InitSeeder` on your CLI.
- [x] See that all the tables have at least one tuple.

## Demo
### Expected output of `php spark db:seed InitSeeder`:
<img width="662" alt="Screenshot 2023-10-27 at 8 33 34" src="https://github.com/loopcrack-org/Kinub/assets/89323622/df900a3a-da4c-4132-8b7b-7c79f583eaf1" alt="Expected Output">

[KIN-280]: https://loopcrack.atlassian.net/browse/KIN-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-31 03:28 UTC, Mauriciocr207 approved these changes

2023-10-31 17:05 UTC, CheloChidoone requested changes
@CarlosJCD We left you a comment, but good job in general, it works well.

2023-10-31 17:05 UTC, CheloChidoone commented on app/Database/Seeds/HomePageSeeder.php
> +class HomePageSeeder extends Seeder
@CarlosJCD The Home Page data is getting created correctly but it creates with homePageId with value `0`, we believe this is because on the Home Page migration the homePageId field doesn't have `'auto_increment' => true` , we need to fix that so the data from the seeders gets created correctly.

CC: @CarlosMay7

2023-11-01 05:20 UTC, Oswaldo-Chan approved these changes

2023-11-01 05:25 UTC, Oswaldo-Chan approved these changes
Good job @CarlosJCD, but @FernandoJoachin and I have a question. We noticed that there's a migration for Emails, but it doesn't have a corresponding seeder since the 'EmailSeeder' file was deleted. Are you planning to recreate that seeder in another ticket, or was it removed by mistake?

2023-11-01 16:20 UTC, CarlosJCD commented
> Good job @CarlosJCD, but @FernandoJoachin and I have a question. We noticed that there's a migration for Emails, but it doesn't have a corresponding seeder since the 'EmailSeeder' file was deleted. Are you planning to recreate that seeder in another ticket, or was it removed by mistake?

I decided to delete the email seeder because of how are we managing them now. I figured that it would be more complex than it should be because now we are storing the html code of the emails, making them more complex to seed.

2023-11-01 17:04 UTC, Cristianpan reviewed
Hey @CarlosJCD  me and @LUGAMAFE  leave you some recommendations to consider before you make the merge

2023-11-01 17:04 UTC, Cristianpan commented on app/Database/Seeds/ProductSeeder.php
> +        $this->db->table('products')->insert($product);
Please add more productos to test this table

2023-11-01 17:05 UTC, LUGAMAFE approved these changes
Same comments as @Cristianpan Good Job!

2023-11-01 17:05 UTC, Cristianpan approved these changes

2023-11-02 16:37 UTC, CheloChidoone approved these changes
Good Job @CarlosJCD.

2023-11-02 16:37 UTC, CarlosMay7 approved these changes

2023-11-02 19:15 UTC, merged